### PR TITLE
[17.0][MIG] base_location_geonames_import: Migration to 17.0 

### PR DESCRIPTION
**Pull request by fredericgrall**

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review in runboat

**Comment by pedrobaeza** [comment]
/ocabot migration base_location_geonames_import

Depends on #1651

**Comment by HaraldPanten** [comment]
@fredericgrall base_location has been merged already. Could you rethink this migration PR, only migrating base_location_geonames_import and following the "commit rules" from OCA?

THX!

**Comment by pedrobaeza** [comment]
@fredericgrall that's not valid and you have conflicts. You have to restart the process (or maybe rebase), only bringing the commit history of `base_location_geonames_import`.

**Comment by HaraldPanten** [comment]
@fredericgrall will you continue the migration in a new PR?

If you don't, we'll do that. Don't worry. THX!

**Comment by HaraldPanten** [comment]
> @fredericgrall will you continue the migration in a new PR?
> 
> If you don't, we'll do that. Don't worry. THX!

Oops. I see you opened a new one.

**Pull request closed without merging**
