### PR TITLE
[11.0][MIG] base_vat_sanitized

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot..." commits

**Comment by astirpe** [comment]
Squashed!

**Review by pedrobaeza — APPROVED** [review]

**Comment by feketemihai** [comment]
@astirpe Isn't it easier to update the default methods from Odoo, please see 
https://github.com/odoo/odoo/blob/11.0/addons/base_vat/models/res_partner.py#L106
i agree that this one is only for Europe group and i don't thing is working since on europe it will fetch datas from Vies, i checked for Romania and didn't upper the country code...but i think it's easier and we will not need another field for sanitized_vat...

**Comment by astirpe** [comment]
@feketemihai this module is required by other modules (like `base_business_document_import`). I think that the reason why this module was created was to provide an alternative method to the one you mentioned. I guess the choice to keep it detached from the standard Odoo was made on purpose.
But I would turn your question to @alexis-via who is the author of this module and of the other modules that need this one.

**Review by njeudy — APPROVED** [review]
Ok code review + tests

**Review by alexis-via — APPROVED** [review]

**Comment by astirpe** [comment]
@feketemihai is it ok for you to merge? Other pending PRs require this one.

**Comment by feketemihai** [comment]
@astirpe Yes no problem, it was just a question if we can use vat field, not vat_sanitized.

**Pull request merged**
