### PR TITLE
[16.0][MIG] partner_employee_quantity

### PR DESCRIPTION
**Pull request by SoporteOperu**

### CODE REVIEW

**Comment by rafaelbn** [comment]
@EmilioPascual please review! I guess you have a task for this module 😄

**Comment by EmilioPascual** [comment]
@SoporteOperu can you make rebase? Runboat isn't run, with rebase it must run.

**Comment by fcvalgar** [comment]
@SoporteOperu can you make rebase? Runboat isn't run, with rebase it must run.

**Comment by rafaelbn** [comment]
Superseed by https://github.com/OCA/partner-contact/pull/1687

**Pull request closed without merging**
