### PR TITLE
[10.0][IMP] partner_identification: Add active toggle

### PR DESCRIPTION
**Pull request by rousseldenis**
Add active toggle button on identification categories

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @lmignon

**Review by lmignon — APPROVED** [review]
Makes sens. Thank you  @rousseldenis

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by skeller1 — APPROVED** [review]
:+1: LGTM

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
