### PR TITLE
[FIX] partner_multi_relation: Translation string couldn't be parsed correctly using str.format KeyError('kategori') issue

### PR DESCRIPTION
**Pull request by yankinmax**
This fix is needed to stop having `pre-commit` failing on other PR's.
- [ ] https://github.com/OCA/partner-contact/pull/1774

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
I'm fine with the change but it has to be implemented through weblate, because the post merge scripts will revert the translations (unless I'm mistaken, maybe @sbidoul can confirm) 

I made the change in weblate -> it should sync in a few hours.

**Comment by yankinmax** [comment]
@gurneyalex for me more important is to merge approved:
- [ ] https://github.com/OCA/partner-contact/pull/1774
If it can be merged without this fix I'm completely fine. Can it?

**Comment by gurneyalex** [comment]
It can't be merged now the CI will be red, and the oca bot will refuse to merge. 

I've just changed the translation in the weblate UI, it should get merged in the next run of the cron, at which point the issue will be fix. Let's check this again tomorrow.

**Comment by gurneyalex** [comment]
https://github.com/OCA/partner-contact/commit/677e517bf1147b9735cf3d212d045b0f8b036b66 fixed the issue

**Comment by sbidoul** [comment]
> I'm fine with the change but it has to be implemented through weblate, because the post merge scripts will revert the translations (unless I'm mistaken, maybe @sbidoul can confirm)

@gurneyalex weblate will not revert translations but may get into a git merge conflict if there are ongoing translations at the same time, and such merge conflicts are painful to resolve. That is why we strongly discourage pushing translations via git, but it can be done in some circumstances.

**Comment by sbidoul** [comment]
BTW, we should enable more checks in weblate to avoid these translation errors: https://github.com/OCA/oca-weblate-deployment/issues/12

**Pull request closed without merging**
