### PR TITLE
[14.0] [FIX] category in manifest files

### PR DESCRIPTION
**Pull request by primes2h**
immagine

### CODE REVIEW

**Comment by tafaRU** [comment]
`pre-commit`will be fixed with https://github.com/OCA/partner-contact/pull/1401

**Review by tafaRU — CHANGES_REQUESTED** [review]
Please split changes into two different commits, one per module, according to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#id48

The rest LGTM, thanks!

**Review by tafaRU — APPROVED** [review]
Code review :+1:

**Review by NL66278 — APPROVED** [review]
:+1:  Interesting discussion here: https://technicallywriteit.com/localization-vs-localisation-does-spelling-really-matter/

**Pull request merged**
