### PR TITLE
[15.0][MIG] base_location: Migration to 15.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Standard procedure
- Remove pylint warnings.
- Adjust translations for not losing them after one pylint warning.

TT32753

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Canario0 this is the migration. Please review it.

**Review by HaraldPanten — APPROVED** [review]
Couldn't test it in runbot but seems to be OK

**Review by Canario0 — APPROVED** [review]
LGTM. I have check it in the latest version of odoo 15.

**Pull request merged**
