### PR TITLE
[13.0] [MIG] partner_multi_relation

### PR DESCRIPTION
**Pull request by Rad0van**
OK, this is my second attempt at porting this to 13.0 Followed the guide for porting that @pedrobaeza and @NL66278 pointed to to my best abilities.

There are few things that are not finished though:

- **colors** attribute in _views/res_partner_relation_all.xml_: `<record id="tree_res_partner_relation_all" model="ir.ui.view"> <field name="model">res.partner.relation.all</field> <field name="arch" type="xml"> <tree string="Partner Relations" colors="gray:not active; blue:date_start &gt; current_date" editable="top" >` Didn't know how to find proper replacement. Help needed here.
- `with self.env.do_in_draft():` used in _tests/test_partner_relation.py_ and _tests/test_partner_relation_all.py_ fails tests. Also don't know hot to replace this and with what.
- It suffers from the same bug as 12.0. - namely the one that #899 tries to fix.

Also ran into the same issue as #877  Solved by changing `class ResPartnerRelation(models.AbstractModel)` into `class ResPartnerRelation(models.Model)` in _res_partner_relation.py_ Is that correct?
Any suggestions are welcome.

### CODE REVIEW

**Comment by Rad0van** [comment]
Well I am obviously missing/not understanding something. The build fails at flake8 complaining it's missing whitespace after comma. When I do that it fails on black complaining the whitespace shouldn't be there. @NL66278 or @pedrobaeza would you be so kind to help me here please?

**Comment by NL66278** [comment]
@Rad0van also remove the comma and you should be good to go.

**Comment by Rad0van** [comment]
> @Rad0van also remove the comma and you should be good to go.

Thank you so much @NL66278 !!! Now it only fails on thins I knew it would fail and I need some assistance - namely do_in_draft().

**Comment by Rad0van** [comment]
I'd need some help/guidelines on how to port self.env.do_in_draft() so that the tests pass. The bug with smart button is getting partially correct patch so that should be OK somewhat.

**Comment by NL66278** [comment]
Hi, do_in_draft() no longer exists. I think it will be best to remove it (and unindent the lines under it). The intention of do_in_draft according to the 12.0 documentation was to change things only in cache. It probably will not matter, as changes in test environment are rolled back anyway.

**Comment by rousseldenis** [comment]
> Hi, do_in_draft() no longer exists. I think it will be best to remove it (and unindent the lines under it). The intention of do_in_draft according to the 12.0 documentation was to change things only in cache. It probably will not matter, as changes in test environment are rolled back anyway.

I think do_in_draft() can be replaced by protecting : https://github.com/odoo/odoo/blob/13.0/odoo/api.py#L647

**Comment by NL66278** [comment]
@Rad0van is the hint given by @rousseldenis enough for you to make the needed adjustments?

**Comment by Rad0van** [comment]
> @Rad0van is the hint given by @rousseldenis enough for you to make the needed adjustments?

@NL66278 I don't know how to use protecting. Without it when using without do_in_draft() tests fail for me. Don't know if it's the result of using model.Model instead of model.AbstractModel

So to summarize it's probably above my current (very limited) knowledge and skills. Would love to help though.

**Comment by BT-shautz** [comment]
@Rad0van I've done my own migration PR, but since this is the one currently on development it has been closed.
Maybe some improvements you need can be found there #932 (I'm missing the do_in_draft() too though...)

**Comment by Rad0van** [comment]
> @Rad0van I've done my own migration PR, but since this is the one currently on development it has been closed.
> Maybe some improvements you need can be found there #932 (I'm missing the do_in_draft() too though...)

@BT-shautz if you do what rousseldenis suggested about do_in_draft() (simply use the code without it) do your tests pass? If so I'd be happy to close this one in favor of yours.

**Comment by BT-shautz** [comment]
> @BT-shautz if you do what rousseldenis suggested about do_in_draft() (simply use the code without it) do your tests pass? If so I'd be happy to close this one in favor of yours.

At the moment I haven't gone so far.
But I do have the missing colors of the "tree_res_partner_relation_all" view for example.
If I do any progress I will let you know.

**Comment by Rad0van** [comment]
> > @BT-shautz if you do what rousseldenis suggested about do_in_draft() (simply use the code without it) do your tests pass? If so I'd be happy to close this one in favor of yours.
> 
> At the moment I haven't gone so far.
> But I do have the missing colors of the "tree_res_partner_relation_all" view for example.
> If I do any progress I will let you know.

@BT-shautz the colors are fine - great to know how to do that. The important thing is whether the automatic tests will pass. Without that it can be hardly expected it will be allowed to be merged. For me it didn't work so far.

**Comment by BT-shautz** [comment]
> @BT-shautz the colors are fine - great to know how to do that. The important thing is whether the automatic tests will pass. Without that it can be hardly expected it will be allowed to be merged. For me it didn't work so far.

If you remove the "with self.env.do_in_draft():" and run the tests what errors do you get? Maybe I can help you there.

**Comment by Rad0van** [comment]
> > @BT-shautz the colors are fine - great to know how to do that. The important thing is whether the automatic tests will pass. Without that it can be hardly expected it will be allowed to be merged. For me it didn't work so far.
> 
> If you remove the "with self.env.do_in_draft():" and run the tests what errors do you get? Maybe I can help you there.

I'll let you know in more detail. But generally attributes were not containing expected values so some of the tests (esp. the one previously running in do_in_draft()) were failing.

**Comment by NL66278** [comment]
@Rad0van I looked into the semantics of protecting and I have to say the proper use or workings of it are completely dark to me as well. It is only used by Odoo internally in the fields.py and models.py python modules. As far as I can see its purpose there is to prevent recomputation of some field values. So I would also advise to just leave out the do_in_draft calls, and if any problem crops up, we deal with it in another way.

**Comment by Rad0van** [comment]
> @Rad0van I looked into the semantics of protecting and I have to say the proper use or workings of it are completely dark to me as well. It is only used by Odoo internally in the fields.py and models.py python modules. As far as I can see its purpose there is to prevent recomputation of some field values. So I would also advise to just leave out the do_in_draft calls, and if any problem crops up, we deal with it in another way.

@NL66278 You can see now the tests fail on asserts. My guess would be this is not really due to removal of do_in_draft() but more because of changing class ResPartnerRelation(models.AbstractModel) into class ResPartnerRelation(models.Model) in res_partner_relation.py Without that change the module fails on transitive dependencies as described in #877 Maybe using TransientModel would solve this? Update: it wouldn't...

**Comment by NL66278** [comment]
As the original developer of this module I feel a duty to help resolving this. I have planned to do this starting next monday.  Thanks for all attempts so far!

**Comment by Rad0van** [comment]
> As the original developer of this module I feel a duty to help resolving this. I have planned to do this starting next monday. Thanks for all attempts so far!

@NL66278 thanx a lot. I remade this module into product_multi_relation and currently have opened PR here: https://github.com/OCA/product-attribute/pull/605 However @rousseldenis asks for some substantial changes and also some questions I am not able to answer in a good way. If you'd be so kind and have a look and maybe provide some guidance. Originally I wanted to keep the source as close to the original partner_multi_relation to be able to transfer changes from there. So I am a bit hesitant to start big changes. Would you please have a look there as well?

**Comment by NL66278** [comment]
@Rad0van I took up your work, added the commits missing from 12.0 and then solved the remaining problems. See here: https://github.com/OCA/partner-contact/pull/936. It is all working, except for some complaints about decreased coverage, but tests are running fine. Do you mind if I close this PR?

**Comment by Rad0van** [comment]
> @Rad0van I took up your work, added the commits missing from 12.0 and then solved the remaining problems. See here: #936. It is all working, except for some complaints about decreased coverage, but tests are running fine. Do you mind if I close this PR?

@NL66278 not at all. Thank you very much. If you could maybe have a look at https://github.com/OCA/product-attribute/pull/605 and provide some guidance / advice. Thanx again.

**Comment by Rad0van** [comment]
Closing as #936 done by @NL66278 is far superior to this :-)

**Pull request closed without merging**
