### PR TITLE
added cheking by states

### PR DESCRIPTION
**Pull request by trolka**
In Ukraine there are many settlements in different regions with the same names. When importing data from geonames there are errors.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers and explain the rationale for this

**Comment by NL66278** [comment]
Check wether close/open will resolve travis error

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
