### PR TITLE
15.0 mig partner pricelist search

### PR DESCRIPTION
**Pull request by vince-dynapps**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@vince-dynapps Thanks for this. I think you are missing migration commit :smiley:

**Review by victoralmau — CHANGES_REQUESTED** [review]
Code review OK, please, rebase

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
The branch needs rebase, and lots of conflicts when rebasing

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/partner-contact/pull/1350

**Comment by rousseldenis** [comment]
@vince-dynapps Do you mind if we close this ? Can you review #1350 ?

**Comment by MiquelRForgeFlow** [comment]
This should be closed.

**Pull request closed without merging**
