### PR TITLE
[16.0] [IMP] partner_ref_unique: Update fr.po

### PR DESCRIPTION
**Pull request by sofien-moalla**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do the translations on Weblate.

https://odoo-community.org/page/translate

**Comment by sofien-moalla** [comment]
I have already completed the translation, but it's still pending been a few days.

https://translation.odoo-community.org/translate/partner-contact-16-0/partner-contact-16-0-partner_ref_unique/fr/

**Comment by pedrobaeza** [comment]
Manually committed and pushed from Weblate. @sbidoul do you know why the auto-update is not working?

**Comment by sofien-moalla** [comment]
The module is not updated on pypi.org the version is 16.0.1.0.0.5 published at June 3, 2023

**Comment by pedrobaeza** [comment]
I can't say about pypi. I always use source code.

**Comment by sofien-moalla** [comment]
I use this to be able to add the module in my project's requirements.txt file with git-autoshare.

**Comment by sbidoul** [comment]
@sofien-moalla manual merges are upload to PyPI with the nightly jobs. It will be there tomorrow.

**Pull request closed without merging**
