### PR TITLE
[14.0][MIG] partner_external_map

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by hparfr — APPROVED** [review]
LGTM

**Review by manuelregidor — APPROVED** [review]
LGTM

**Comment by alexis-via** [comment]
If someone with the super-powers can handle this...

**Comment by pedrobaeza** [comment]
I think MQT is not working, but let's try:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
It worked!

**Pull request merged**
