### PR TITLE
[15.0][FIX] base_location_geonames_import: Fix development_status

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Depends on:
- [x] https://github.com/OCA/partner-contact/pull/1206

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@pedrobaeza  it's something wrong with the pre-commit/action@v2.0.0? it have some error with the setuptools library.

**Comment by pedrobaeza** [comment]
Not sure if it has started to fail at some point, and it's a temporary glitch, or maybe the other repo has a newer version. Can you check?

**Comment by ValentinVinagre** [comment]
humm... the "pre-commit-config.yaml" file I see it same that l10n_spain :/ . I guess it will be a temporary glitch.

**Comment by pedrobaeza** [comment]
We haven't merge any there. Please check on the account_tax_balance one

**Pull request merged**
