### PR TITLE
[13.0][IMP] partner_company_group: Add one2many counterpart for company_group_id

### PR DESCRIPTION
**Pull request by carlosdauden**
It serves for being used at ORM level in extensions with no side costs.

@Tecnativa TT34815

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Good for being used in ORM. Please change commit message to:
```
[IMP] partner_company_group: Add one2many counterpart for company_group_id

It serves for being used at ORM level in extensions with no side costs.
```

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@carlosdauden please change the commit message and I'll merge it.

**Comment by carlosdauden** [comment]
@pedrobaeza changed

**Pull request merged**
