### PR TITLE
[14.0][MIG] partner_phonecall_schedule: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Please @Yajo and @joao-p-marques can you review it?

@Tecnativa TT30293

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@Yajo @joao-p-marques it seems there's a new problem with pre-commit:

https://github.com/OCA/partner-contact/runs/4166717724?check_suite_focus=true#step:4:112

can you check?

**Comment by victoralmau** [comment]
Can you retry again? (If the problem with pre-commit is already solved).

**Pull request merged**
