### PR TITLE
[9.0][FIX] partner_contact_job_position: error loading form view.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
**Current behavior:**
Error raises when trying to open form view of a children partners from a company partner.
image

**Desired behavior:**
No error raises.

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Not sure why merging these 2 patches in the same PR, but in any case I like both

**Comment by LoisRForgeFlow** [comment]
@yajo the second one was a minor thing I wouldn't likely open a PR for, but since I open this one and I was working with both modules I took the occasion to also fix the little string issue.

**Comment by pedrobaeza** [comment]
Please change module version number in both (each one in its commit).

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Done!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
