### PR TITLE
[IMP] mute logger in test

### PR DESCRIPTION
**Pull request by hbrunn**
otherwise, we keep a warning in the log

### CODE REVIEW

**Review by lasley — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Which is the warning?

**Comment by hbrunn** [comment]
this: https://github.com/OCA/partner-contact/blob/8.0/partner_contact_birthdate/models.py#L51
and yes, i fucked up here. that's what i meant before with making it simple for the reviewer. this PR is a very good example of how you should not do it

**Comment by hbrunn** [comment]
this PR is enigmatic enough to have you asking, the title could tell more. and there's no reason advocated at all why it's a good thing that's proposed

**Comment by hbrunn** [comment]
we should acknowledge that we're to some degree an old boy's network and we need to fix this

**Comment by lasley** [comment]
Yeah honestly my 👍  was just based on assuming you know what you're doing + verifying that there was in fact a warning on the build that is no longer here. That's probably a bad thing in hindsight

**Comment by pedrobaeza** [comment]
On v10 it has been not silently ignored the problem: https://github.com/OCA/partner-contact/blob/10.0/partner_contact_birthdate/models/res_partner.py#L33

Maybe it's better to remove that try artifact

**Comment by hbrunn** [comment]
I was hesitating to do that because it's a kind of API change (thing break when assigning incorrect dates vs it's skipped silently). I don't mind which way, if @lasley also agree with this change, I'll be happy to do so

**Comment by lasley** [comment]
I think I agree with @hbrunn on this one - adding an exception where something once wasn't could have cascading effects on systems that are working fine in production.

I agree from a conceptual standpoint that we shouldn't be covering the error up (v10 is the correct way), but that's the way it was released in this version so I think we need to keep with it.

**Comment by pedrobaeza** [comment]
OK, but Travis still needs to be fixed...

**Comment by lasley** [comment]
Hrm I didn't think new lints were supposed to fail on old branches. That's a bit annoying

**Comment by pedrobaeza** [comment]
OK, if this is because the new flake8 version, we froze it, so restarting Travis should be enough.

**Comment by lasley** [comment]
Restarted; we'll see!

**Comment by NL66278** [comment]
@hbrunn If you put licence key in manifest as well, you should get rid of the lint error in travis

**Comment by hbrunn** [comment]
thanks for the reminder, also fixed a few other lints

**Comment by pedrobaeza** [comment]
Travis is still red

**Comment by NL66278** [comment]
But new errors have not nothing to with this PR: 
```openerp.addons.partner_identification.tests.test_partner_identification: ` Dummy CRUD test
2018-04-11 07:14:51,228 22525 ERROR openerp_test openerp.sql_db: bad query: INSERT INTO "res_partner_id_number" ("id", "active", "partner_id", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_partner_id_number_id_seq'), true, 6, '1234', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/sql_db.py", line 247, in execute
res = self._obj.execute(query, params)
IntegrityError: null value in column "category_id" violates not-null constraint
DETAIL:  Failing row contains (4, null, null, null, 2018-04-11 07:14:51.19689, 1234, 1, null, null, 1, 2018-04-11 07:14:51.19689, t, null, null, 6, null).```
```

**Review by NL66278 — APPROVED** [review]
:+1: LGTM and working in practice

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
