### PR TITLE
[10.0] partner_email_check: Multiple email check

### PR DESCRIPTION
**Pull request by Abranes**
Check multiple emails separated by semicolon.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`;` is not the only possible separator. @Yajo isn't standard RFC already supports multiple emails and its separators?

**Comment by fuentes73** [comment]
AFAIK Odoo is handling this job, it gets partner emails and uses email.utils [formataddr](https://docs.python.org/2/library/email.util.html#email.utils.formataddr) and  [getaddresses](https://docs.python.org/2/library/email.util.html#email.utils.getaddresses) from python in order to build a valid (RFC) To or Cc headers.

We've tested and it works, if you have multiple emails in a partner saparated by `;` Odoo sends an email to those emails.

**Comment by pedrobaeza** [comment]
Yeah, but `,` also works as valid email separator. Does module in previous state fail with commas?

**Comment by fuentes73** [comment]
Yes, it failed without this changes.
I think that / it's also a valid separator. Abraham can handle those characters too. What do you think?

**Comment by pedrobaeza** [comment]
That's why I ask for the valid separators according RFC standard, so that we handle all of them at once.

**Comment by yajo** [comment]
https://stackoverflow.com/questions/12120190/what-is-the-best-separator-to-separate-multiple-emails#12120203

**Comment by fuentes73** [comment]
@Abranes please, change the code to use as separator commas instead of semicolon.

**Comment by Abranes** [comment]
@fuentes010 Done! Now the only accepted separator is comma.

**Comment by Abranes** [comment]
@pedrobaeza @Yajo @fuentes010 changed the separator according RFC standard.
Any other suggestions for change or is ready to merge?

**Review by pedrobaeza — APPROVED** [review]

**Review by fuentes73 — APPROVED** [review]

**Pull request merged**
