### PR TITLE
[8.0][base_location_geonames_import] Added option to convert retreived names to Title Case.

### PR DESCRIPTION
**Pull request by ivantodorovich**
Added an option to convert retreived names to Title Case.
If checked, it applies .title() on retreived city and state names.

_This is my first contribution to the OCA. Please let me know if I need to fix anything.
Also, I didn't know whether to modify the i18n files or not. Just in case I didn't._

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please check PEP8 error:

```
base_location_geonames_import/wizard/geonames_import.py:49:7: E121 continuation line under-indented for hanging indent
```

And other nice to fix (although not yours):

```
base_location_geonames_import/__openerp__.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`
base_location_geonames_import/__openerp__.py:26: [C8103(manifest-deprecated-key), ] Deprecated key "active" in manifest file
```

And finally, please sign the CLA.

**Comment by pedrobaeza** [comment]
Remember also to change version number to a higher second level one (as this requires to update the module): https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Comment by ivantodorovich** [comment]
Thank you for your help, @pedrobaeza !

**Comment by pedrobaeza** [comment]
:+1:

Thanks for your contribution.

**Comment by ivantodorovich** [comment]
@pedrobaeza , what's the right way of submitting a translation string to the field I've added?

**Comment by pedrobaeza** [comment]
You have several ways:
- Include it in the `es.po` file in this PR.
- Or wait for the PR to be merged, and then translate it in Transifex, which will go back to the repository when synchronized (every weekend).

**Comment by ivantodorovich** [comment]
Thanks! I'll wait for the PR to be merged and translate it in Transifex.

I see ci/runbot is failing, but I don't really understand what's wrong. Let me know if there is anything else to correct.

**Comment by pedrobaeza** [comment]
Runbot is failing due to a recent update. One guy is in charge of taking care about it. In the other side, it's strange that Travis didn't run. Please try to rebase and force push again to force it to rerun.

**Comment by ivantodorovich** [comment]
@pedrobaeza I did the rebase, as you suggested, and now it works.

coverage is also failing, but I have no idea how to fix it.

**Comment by pedrobaeza** [comment]
Coverage is failing because you have added more code that is not tested, but this case is nothing specially critical, so :+1:

**Comment by ivantodorovich** [comment]
@pedrobaeza, do I need to change anything else?

**Comment by pedrobaeza** [comment]
No, it needs another positive review to be merged.

**Comment by pedrobaeza** [comment]
@yvaucher, can you review this one?

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
