### PR TITLE
13.0 mig base vat sanitized

### PR DESCRIPTION
**Pull request by StephanRozendaal**

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by astirpe — APPROVED** [review]
Code review OK

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM!

**Comment by astirpe** [comment]
@pedrobaeza is it ok to merge this one?

**Comment by alexis-via** [comment]
I think it was a mistake to port this module, because the feature is now native in v13. The native code that handles this feature is located in the base_vat module, in models/res_partner.py at the very end of the file: it inherits write and create and calls the compact method of the stdnum lib, cf https://github.com/odoo/odoo/blob/13.0/addons/base_vat/models/res_partner.py#L466

So, what shall we do ?
I think we should remove the module, but maybe some people have already installed it, so maybe we should just add a note in the README and keep it like that.
At least, we won't use it in OCA/edi. The only thing to handle is data migration for those who upgrade from v12... but I guess it is something to handle in openupgrade.

**Comment by alexis-via** [comment]
I made a small PR to add a note in the README about it https://github.com/OCA/partner-contact/pull/862

**Pull request merged**
