### PR TITLE
[16.0][MIG] partner_contact_birthdate

### PR DESCRIPTION
**Pull request by carmenbianca**
Ping @PierrickBrun

### CODE REVIEW

**Comment by marielejeune** [comment]
Depends on https://github.com/OCA/partner-contact/pull/1377

**Review by marielejeune — APPROVED** [review]
Code review done

**Review by PierrickBrun — APPROVED** [review]
code review + test ( with https://github.com/OCA/partner-contact/pull/1377)

**Comment by carmenbianca** [comment]
@gurneyalex Can you check the CLA please? :tada:

**Comment by gurneyalex** [comment]
CLA manually checked

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
