### PR TITLE
[17.0][MIG] partner_contact_birthplace

### PR DESCRIPTION
**Pull request by Borruso**
Migration from 14.0 to 17.0

Issue: #1599

### CODE REVIEW

**Comment by salvorapi** [comment]
Need migrate to 16.0 :)

**Comment by Borruso** [comment]
> Need migrate to 16.0 :)

ecco a te https://github.com/OCA/partner-contact/pull/1734

**Review by luisDIXMIT — APPROVED** [review]
LTGM!

**Review by qgroulard — APPROVED** [review]
LGTM

**Pull request merged**
