### PR TITLE
[10.0][FIX] base_location_geonames_import: Fix url

### PR DESCRIPTION
**Pull request by rousseldenis**
Fix url and iso country code position

### CODE REVIEW

**Comment by rousseldenis** [comment]
fixes #905

**Comment by pedrobaeza** [comment]
URL is correct. The one you are mentioning has other different format. The problem is that from time to time, Geonames screws up its export scripts, and they are not available in some hours. It's an annoyance, but tests should be that way. I will expand more in the issue you have opened, but for now, let's close this.

**Comment by rousseldenis** [comment]
> URL is correct. The one you are mentioning has other different format. The problem is that from time to time, Geonames screws up its export scripts, and they are not available in some hours. It's an annoyance, but tests should be that way. I will expand more in the issue you have opened, but for now, let's close this.

That's why we shouldn't rely on external url for tests. So, if you don't want this, please fix tests as main branch should go green

**Comment by pedrobaeza** [comment]
Please read my full explanation, and no, tests can't be green as this is failing, although it relies in something external.

**Comment by rousseldenis** [comment]
> Please read my full explanation, and no, tests can't be green as this is failing, although it relies in something external.

I did. Unit tests should be run in any cases as tests should be reproductible in any case. We should either mock requests library and provide a fake zip file...

See: https://en.wikipedia.org/wiki/Unit_testing

> To isolate issues that may arise, each test case should be tested independently. Substitutes such as method stubs, mock objects,[4] fakes, and test harnesses can be used to assist testing a module in isolation.

**Comment by pedrobaeza** [comment]
I don't agree. Who says these are unit tests? These are tests for being sure the module works. Simply. And this is want I want to know: that today I'm not able to use this module.

**Comment by rousseldenis** [comment]
> I don't agree. Who says these are unit tests? These are tests for being sure the module works. Simply. And this is want I want to know: that today I'm not able to use this module.

So, if geonames never fix it, we cannot run tests anymore on this repo... let me laugh

**Comment by pedrobaeza** [comment]
No, we should fix the module for changing the new way the module should work. Imagine Geonames closes and this is no more available. What a mocked test serves? The module is useless, and then it should deactivated, or switch to other service, etc. The same applies if Geonames changes the format.

This temporary glitch is that, a temporary annoyance. If tomorrow this continues the same, then we can decide to do other action (like temporary excluding it in tests, or other thing), but the important thing is that test is serving its purpose: the feature of the module is not working (no matter what is the reason why it doesn't work).

This branch 10.0 is 3 years old and if this is the first time you notice this, this is not happening very frequent, isn't it?

**Comment by rousseldenis** [comment]
> Who says these are unit tests?

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#tests

**Comment by NL66278** [comment]
I have seen this breaking before. I understand @pedrobaeza in the tests not making sense if no real connection is made. I can also understand @rousseldenis problem with having PR's randomly failing tests because some external website not being available. Would it be an option to move this module - at some stage - to its own repository?

**Comment by rousseldenis** [comment]
> I have seen this breaking before. I understand @pedrobaeza in the tests not making sense if no real connection is made. I can also understand @rousseldenis problem with having PR's randomly failing tests because some external website not being available. Would it be an option to move this module - at some stage - to its own repository?

The general idea with tests is that they should run in isolated environment. You test your code, not the presence of the file... That's the responsability of the external provider(aka geonames) not yours. If you move the module to another repo, the problem should occur if there are pending PR's like today.

**Comment by lmignon** [comment]
It's no the responsibility of OCA to check that the geoname server is available and working properly... Our responsibility is to check that our code works properly with the informations (the file) produced by the geoname service.  ~~IMO, the @rousseldenis proposal makes sens and should not be rejected.~~
IMO We should mock the call to provide the result expected by the call.

Mocking the call to an external resource help to improve the tests coverage since we can check how our code works if the external resources is unavailable or if the format received is not the one expected or ....

**Comment by rousseldenis** [comment]
ocabot merge blocked due to geonames... What a pity

**Comment by pedrobaeza** [comment]
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#tests doesn't state anything about that needs to be what you call "unit tests". Any way, as said, you think about the mocking, and I don't want that as said. Just wait a bit and if tomorrow continues the same, then we take another decision. Can you wait 24 hours?

**Pull request closed without merging**
