### PR TITLE
[13.0][ADD] company_default_partner_pricelist

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
This module allows assigning a default pricelist for partners per each
company in the system.

If set, the default pricelist will be used for partners unless the value
is modified by the user.

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, thanks for updating the test case. LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, thanks for updating the test case. LGTM!

**Pull request merged**
