### PR TITLE
[13.0][IMP] base_location_geonames_import: Try/except is added to remove cities and postal codes

### PR DESCRIPTION
**Pull request by victoralmau**
Try/except is added to remove cities and postal codes.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT33464

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Not sure on why runboat is failiing

**Comment by pedrobaeza** [comment]
`External ID not found in the system: contacts.res_partner_menu_config` in `partner_contact_age_range`. No `contacts` dependency put, but the main problem is that there's no Travis here, and I don't know why.

**Comment by pedrobaeza** [comment]
I don't think this is the solution to the main problem, which is possible cities not being able to be removed. Maybe you can include a flag for not removing them, or try to remove them in global with a try, and if not possible, remove one by one if possible.

**Comment by victoralmau** [comment]
> I don't think this is the solution to the main problem, which is possible cities not being able to be removed. Maybe you can include a flag for not removing them, or try to remove them in global with a try, and if not possible, remove one by one if possible.

One possibility would be to add an `is_custom` field (boolean) both to the cities and zip codes and to the domain, add
`('is_custom', '=', False)` to not remove those. What do you think about it?

**Comment by pedrobaeza** [comment]
I prefer the other options.

**Comment by victoralmau** [comment]
Changes done, it's ready to review again.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Cherry-picked for v14 in 1709a66c9e7badf965728ef98ca4c2b0af2a753d and in v15 in 759f40a13bbdf04e9f4109771367ac3798ef5352

**Pull request merged**
