### PR TITLE
[12.0][MIG] partner_iterative_archive: Migration to 12.0

### PR DESCRIPTION
**Pull request by joscanog**
Standard migration from 13.0 to 12.0.

### CODE REVIEW

**Comment by azucenatrey** [comment]
LGTM

**Review by azucenatrey — APPROVED** [review]
LGTM

**Review by rlizana — APPROVED** [review]
:+1:

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
@joscanog The merge fails on this in pre-commit:
```
Please check-in the following files:
setup/partner_iterative_archive/odoo/addons/partner_iterative_archive
setup/partner_iterative_archive/setup.py
Error: Process completed with exit code 1.
```
Can you add these files to your commit and then push again?

**Comment by cubells** [comment]
@NL66278 

I see this error on tests is not problem of that module.

Can you recheck this PR?

Thanks!

**Pull request merged**
