### PR TITLE
[MIG] base_country_state_translateable: Migration to 16.0

### PR DESCRIPTION
**Pull request by deu-dev**
#1353

### CODE REVIEW

**Review by NL66278 — CHANGES_REQUESTED** [review]
Please follow the method that preserves commit history:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by AungKoKoLin1997** [comment]
@deu-dev Can you please update this PR with the method that preserves commit history?

**Comment by AungKoKoLin1997** [comment]
@deu-dev Do you have a plan to fix this PR? If not, you can hand over this migration to me and I will create new PR. @NL66278 How do you think?

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Please just go ahead and create a new PR.

**Pull request closed without merging**
