### PR TITLE
[14.0] Update from copier template

### PR DESCRIPTION
**Pull request by tafaRU**
…A/oca-addons-repo-template/pull/170

### CODE REVIEW

**Review by primes2h — APPROVED** [review]
LGTM

Thanks!

**Comment by primes2h** [comment]
P.S.: runboat and Odoo/OCB tests are :red_circle:, not related anyway.

**Review by NL66278 — APPROVED** [review]
:+1:  LGTM Runbout problem indeed not related

**Comment by pedrobaeza** [comment]
Please cherry-pick https://github.com/OCA/partner-contact/pull/1394/commits/ff1844044055cfa19aaf89c418702875b0978b72 for fixing that part.

**Pull request merged**
