### PR TITLE
[15.0][mig]-partner_exception

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by GuillemCForgeFlow** [comment]
Hi @JuanyDForgeflow , could you also include this fix: https://github.com/OCA/partner-contact/pull/1511?

**Comment by NelioNextGen** [comment]
@GuillemCForgeFlow It's Added

**Comment by JuanyDForgeflow** [comment]
@GuillemCForgeFlow It's added now

**Pull request merged**
