### PR TITLE
[12.0] Switch to GH actions

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Comment by simahawk** [comment]
~~I have to fix some details, did too much in a rush~~

**Comment by NL66278** [comment]
@simahawk Can you have another commit with changes needed to pass pre-commit? I think it is mainly correcting some website keys in manifest files.

**Comment by simahawk** [comment]
> @simahawk Can you have another commit with changes needed to pass pre-commit? I think it is mainly correcting some website keys in manifest files.

@SilvioC2c will take care, see https://github.com/OCA/partner-contact/pull/1399#issuecomment-1318681295  :wink:

**Comment by SilvioC2C** [comment]
@NL66278 @simahawk please check this PR (I wasn't allowed to push the commit onto this branch directly): https://github.com/OCA/partner-contact/pull/1404

**Pull request merged**
