### PR TITLE
13.0 mig partner contact gender

### PR DESCRIPTION
**Pull request by Daemo00**
Standard migration, plus a little refactor due to a pylint warning.

Depends on:

- [x] #788

### CODE REVIEW

**Comment by Daemo00** [comment]
Depends on #788

**Comment by ermannognan** [comment]
Hi, can you include this module in the official v 13.0 branch? I need for it to complete my application! Thanks.

**Comment by Daemo00** [comment]
Hi @ermannognan, in order to speed up the merge process (that is, having this module in branch `13.0`), you can review the module: https://odoo-community.org/page/review

**Review by StephanRozendaal — APPROVED** [review]
Depending PR is merged.

Code looks good.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
