### PR TITLE
[ADD] partner_contact_access_link: reach contact full form

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of the partners form
and to allow you to click on a button and open the full contact form
while watching a company form.

@Tecnativa TT24492 TT24498

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Tested on runbot :+1:

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍  nice functionality

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by pedrobaeza — DISMISSED** [review]
The chosen icon suggest that the form is going to be opened as popup, which is not true. I prefer the icon used in `web_tree_many2one_clickable`. I also have the doubt about what happen when you click on edit mode.

**Comment by HaraldPanten** [comment]
> I also have the doubt about what happen when you click on edit mode.

Clicking edit mode is working fine.

**Review by rafaelbn — APPROVED** [review]
Functionally tested in runbot :+1:

**Comment by yajo** [comment]
@pedrobaeza That icon could be intuitive in list views, but TBH I don't see it fits well in a form context like this. :thinking:  See how it looks:

Captura de pantalla de 2020-06-26 09-38-02

I think the previous one was better. I don't think most users relate that icon specifically to a floating view, but more with the fact that you can click on that icon and see the full details of related records. Would you reconsider this?

**Comment by pedrobaeza** [comment]
Indeed it's not the best looking one, but I prefer that you find another one then, as the icon is clearly used in Odoo for opening in popup, so it's a mix of concepts. How does it look with 2/3 repetitions of the latter icon?

**Comment by HaraldPanten** [comment]
> @pedrobaeza That icon could be intuitive in list views, but TBH I don't see it fits well in a form context like this. 🤔 See how it looks:
> 
> Captura de pantalla de 2020-06-26 09-38-02
> 
> I think the previous one was better. I don't think most users relate that icon specifically to a floating view, but more with the fact that you can click on that icon and see the full details of related records. Would you reconsider this?

IMHO I prefer the last one or a new one instead of this other.

**Comment by yajo** [comment]
OK I found https://fontawesome.com/icons/external-link-square. I like it because it's similar to https://fontawesome.com/icons/external-link-alt but not exactly equal. That's our case: if you click there, you'll get a similar behavior but not exactly the same. It also looks good on the form:

Captura de pantalla de 2020-06-26 10-03-13

**Comment by pedrobaeza** [comment]
Yeah, I also like that one!

**Comment by HaraldPanten** [comment]
Looks good 👍

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
