### PR TITLE
[16.0] [FIX] partner_company_default: fix warning about create method in batch

### PR DESCRIPTION
**Pull request by ivantodorovich**
fix warning about create method in batch

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by AungKoKoLin1997 — APPROVED** [review]
LGTM.

**Review by RodrigoBM — APPROVED** [review]

**Comment by RodrigoBM** [comment]
can @dreispt re-merge it? thanks

**Comment by RodrigoBM** [comment]
can @yostashiro merge it?

**Comment by yostashiro** [comment]
> can @yostashiro merge it?

Sorry, I don't have the authority to do so.

@ivantodorovich I'm not sure what the issue was in https://github.com/OCA/partner-contact/pull/1712#issuecomment-2119324522, but could you perhaps rebase so that @dreispt can try to merge again.

**Pull request merged**
