### PR TITLE
[14.0] [MIG] [MV] website_partner_contact

### PR DESCRIPTION
**Pull request by miguel-S73**
Module website_portal_contact, migrated to v14 and moved from [OCA/website](https://github.com/OCA/website/tree/10.0) to [OCA/partner-conatct](https://github.com/OCA/partner-contact/tree/14.0) and renamed as poratl_contact_mgmt

Ref : https://github.com/OCA/website/pull/822

### CODE REVIEW

**Review by hildickethan — APPROVED** [review]

**Comment by miguel-S73** [comment]
@yajo @pedrobaeza  Can you review this PR, please?

**Comment by pedrobaeza** [comment]
/ocabot migration website_partner_contact

Sorry, we are not using this module anymore.

**Comment by yajo** [comment]
Me neither. You can consider [adopting the module](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_maintainer_role.rst), so you get merge rights.

**Comment by francesco-ooops** [comment]
@miguel-S73 can you rebase to trigger runboat rebuild?

**Pull request closed without merging**
