### PR TITLE
[15.0][MIG] partner_contact_role: Migrate to version 15.0

### PR DESCRIPTION
**Pull request by hailangvn**
This is standard migration.

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1:  LGTM

**Review by cyrilmanuel — APPROVED** [review]
LGTM

**Comment by hailangvn** [comment]
Thanks all for your support.

Hi @simahawk, this has been re-based and pre-commit is green. So I hope next merging will be successful.

**Comment by hailangvn** [comment]
Thanks @simahawk for your quick help. The flake8 error can be fixed by last commit. :pray:

**Pull request merged**
