### PR TITLE
[15.0][MIG] partner_contact_department: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT44158

@chienandalu please review!

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
- Check tests issues (maybe temporary)
- Squash some commits

**Comment by chienandalu** [comment]
Re-enable tests and see if they pass

**Comment by stefan-tecnativa** [comment]
@chienandalu still not working

**Comment by chienandalu** [comment]
Ok, re-comment it then and let's move on

**Review by chienandalu — APPROVED** [review]

**Comment by rafaelbn** [comment]
Please @stefan-tecnativa solve "This branch has conflicts that must be resolved"

thank you!

**Comment by stefan-tecnativa** [comment]
Now it should be okay @rafaelbn

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
