### PR TITLE
[16.0][IMP] base_country_state_translatable: make state code also translatable

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
👍🏽

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please explain the rationale behind this

**Comment by JordiMForgeFlow** [comment]
> Please explain the rationale behind this

Odoo loads chinese states using the chinese characters. We want to add a translation for them based on https://en.wikipedia.org/wiki/ISO_3166-2:CN

**Comment by pedrobaeza** [comment]
But this provokes hard side effects: if a code is incorrect, next time it's changed, translations will have an incorrect value. This should be done on your custom, not here in the module.

**Comment by JordiMForgeFlow** [comment]
> But this provokes hard side effects: if a code is incorrect, next time it's changed, translations will have an incorrect value. This should be done on your custom, not here in the module.

You are right, the side effect is not worth adding it in OCA. Thank you for the review @pedrobaeza :)

**Pull request closed without merging**
