### PR TITLE
14.0 mig base_country_state_translatable

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by fshah-initos — APPROVED** [review]

**Review by fshah-initos — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@dsolanki-initos you should squash your commits first

**Comment by HaraldPanten** [comment]
Why do you have 2 [IMP] black, isort, prettier commits?

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM

**Comment by dsolanki-initos** [comment]
@OCA-git-bot Is it possible to merge this module?

**Pull request merged**
