### PR TITLE
[14.0] backport partner_bank_acc_type_constraint from 16 to 14

### PR DESCRIPTION
**Pull request by alexis-via**
Simple backport, no code change.

### CODE REVIEW

**Comment by rafaelbn** [comment]
@alexis-via CI is 🔴 could you take a quick look?

@legalsylvain @rousseldenis could you please make a quick review?

**Comment by alexis-via** [comment]
@rafaelbn This module adds a constraint on res.partner.bank, so it blocks the demo data of some modules. I think we should exclude it from automated tests, unless if someone has a better idea.

**Comment by alexis-via** [comment]
@rafaelbn  Did you close the PR by mistake, or was it intentional ?

**Comment by rafaelbn** [comment]
By mistake @alexis-via ! Sorry! 🙏🏼

**Review by hbrunn — APPROVED** [review]
wouldn't it be sufficient to add this to the rebel modules?

**Review by dreispt — APPROVED** [review]

**Pull request merged**
