### PR TITLE
[15.0][MIG] partner_disable_gravatar: Migration to 15.0

### PR DESCRIPTION
**Pull request by kwoychesko**
Migration changes done using the 16.0 migration from 14.0 as a guide. Squashed commits as best as I could figure out.

### CODE REVIEW

**Comment by kwoychesko** [comment]
The PR for the 16.0 migration also failed this Codecov check:
https://github.com/OCA/partner-contact/pull/1388/files#diff-054d420646b403f2217cf5ba24dceea88982dc15112f8de3c96cf9730a43b5f8

Is this okay or is this something I need to take care of?

**Comment by kwoychesko** [comment]
Hey team! I got a notice that this is going stale -- is it okay to merge?

**Comment by jans23** [comment]
Yes, this should be ready to be merged.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
