### PR TITLE
[9.0][ADD] partner_ref_unique module

### PR DESCRIPTION
**Pull request by cubells**
This module allows to add an unique constraint to partner ref field

cc @Tecnativa

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Please squash the first 2 commits together

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Please change to OCA icon

**Comment by cubells** [comment]
@rousseldenis done.

**Review by rousseldenis — APPROVED** [review]
:+1: Code review

**Pull request merged**
