### PR TITLE
[MIG] base_partner_sequence: Migration to 16.0

### PR DESCRIPTION
**Pull request by deu-dev**
#1353

### CODE REVIEW

**Review by NL66278 — CHANGES_REQUESTED** [review]
Please follow the method that preserves commit history:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by marielejeune** [comment]
Hi @deu-dev , do you plan to fix your PR? Thanks

**Comment by Nikul-OSI** [comment]
Supersede #1453

**Comment by Nikul-OSI** [comment]
@NL66278 @dreispt can you please close this PR?

**Pull request closed without merging**
