### PR TITLE
[14.0][MIG] partner_contact_lang: Migration to 14.0

### PR DESCRIPTION
**Pull request by newtratip**
Standard Migration

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@newtratip Could you squash your commits or do you want to let it as is ?

**Comment by newtratip** [comment]
@rousseldenis, I squash my commits already, Could you please check again ?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
