### PR TITLE
[13.0][MIG] base_location: Migration to 13.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa TT19707

### CODE REVIEW

**Review by schout-it — APPROVED** [review]
lgtm

**Review by i-vyshnevska — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@moylop260 why 13.0 is not admitted in pylint-odoo yet? I thought https://github.com/OCA/pylint-odoo/pull/249 was for that.

**Comment by moylop260** [comment]
pylint is supporting 13.0

The lint travis build is green
https://travis-ci.org/OCA/partner-contact/jobs/591521616

I think it is another tool

**Comment by rousseldenis** [comment]
@pedrobaeza  @sbidoul is looking into this now

**Comment by pedrobaeza** [comment]
Great, thanks

**Comment by pedrobaeza** [comment]
@sbidoul I created https://odoo-community.org/web#id=847934&action=468&active_id=2&model=project.task&view_type=form&menu_id=748 for all the things to do on a new version, so if there's something for the bot, please indicate it there

**Comment by sbidoul** [comment]
@pedrobaeza thanks for the initiative. Updated.

**Pull request merged**
