### PR TITLE
[BACKPORT][8.0] partner_financial_risk

### PR DESCRIPTION
**Pull request by andhit-r**
Backport to 8.0

### CODE REVIEW

**Comment by andhit-r** [comment]
cc @tecnativa

**Comment by andhit-r** [comment]
@mikevhe18 @azmimr67 @m-sani would you kindly help reviews. Many thanks.

**Comment by m-sani** [comment]
👍

**Comment by mikevhe18** [comment]
:+1:

**Comment by andhit-r** [comment]
@carlosdauden @tecnativa as original author would you kindly review this PR. Many thanks.

**Comment by pedrobaeza** [comment]
All green and 2 positive reviews. Merging.

**Pull request merged**
