### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by yvaucher** [comment]
pylint to make green is error already addressed ?

**Comment by pedrobaeza** [comment]
Remove travis_run_flake8 line and ${VERSION} part in travis_run_tests line.

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Although the 4 pylint errors can be handled also in this PR

**Comment by tafaRU** [comment]
I'm about to do a PR on **_yvaucher:8.0-separate-lint**_ that fixes the 4 pylint errors.

**Comment by tafaRU** [comment]
@yvaucher  https://github.com/yvaucher/partner-contact/pull/1

**Comment by tafaRU** [comment]
**_test_server failed**_ (but the related builds were already red) while **_test_flake8**_ and **_test_pylint**_ now are green so :+1:

**Pull request merged**
