### PR TITLE
[MIG] portal_partner_data_no_edit

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@JoelZilli Thanks for this. Could you check your CLA and tests ?

**Comment by JoelZilli** [comment]
@rousseldenis I`m checking the CLA. But for the tests, do you have any suggestion on how to proceed with the error? Because it says that it comes from the "Odoo Tour" test and i have never did anything with that kind on functionality.

**Comment by rousseldenis** [comment]
Maybe @chienandalu @pedrobaeza can help as I'm not doing so much portal.

**Comment by sergio-teruel** [comment]
@CarlosRoca13 Can you take a look at it?

**Comment by sergio-teruel** [comment]
This migration is not worked as expected

1.- I block de edition in portal
image


2.- I can update my data (See the gif)
Peek 2022-11-03 22-02

**Review by chienandalu — CHANGES_REQUESTED** [review]
Hi @JoelZilli 

The tours are meant to test the module features as the user should experience. They use a headless browser and javascript scripts that follow that steps (go to a page, click on this link, assert that an element is visible or not, etc)

As a reference, you can check Odoo's docs on that matter: https://www.odoo.com/documentation/15.0/developer/reference/backend/testing.html#integration-testing

In the other hand, a simple functional review by a human showed up that the module doesn't do what was meant to do...

**Comment by pedrobaeza** [comment]
Superseded by #1393

**Pull request closed without merging**
