### PR TITLE
[ADD] animal

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@max3903 Is the gender field not mandatory?

image

**Comment by max3903** [comment]
@marcelsavegnago Good catch, thanks. Fixed.

**Comment by rvalyi** [comment]
> @max3903 Is the gender field not mandatory?

then how do you do when your pet shop sells say jellyfish?
Nah...

**Comment by max3903** [comment]
@rvalyi You add the gender...

**Comment by max3903** [comment]
@marcelsavegnago @rvalyi Any other feedback before merging?

**Comment by marcelsavegnago** [comment]
@max3903 Will the colors be registered by breed?

**Comment by rvalyi** [comment]
Hello @max3903 aside from the easy joke I have no strong opinion on this one to approve the PR or not. Nothing seems wrong for me that's all I can say.
When introducing new models like this, I advise to look for standards 1st. I searched on schema.org but could not find anything conclusive about animals. Only this PR showing their internal debate about such modelling:
https://github.com/schemaorg/schemaorg/issues/746
I guess some other people may be more qualified to validate the PR.

**Comment by max3903** [comment]
> @max3903 Will the colors be registered by breed?

Yes, they are.

**Comment by marcelsavegnago** [comment]
@max3903 For now I suggest including the size, weight and date of birth. And also if the animal is neutered.

**Comment by max3903** [comment]
> @max3903 For now I suggest including the size, weight and date of birth. And also if the animal is neutered.

@marcelsavegnago Done!

**Comment by marcelsavegnago** [comment]
@max3903 In some forms I saw a field to record the type of fur on the animal.

**Review by marcelsavegnago — APPROVED** [review]
LGTM. I believe that the animal's history and anamnesis will be implemented in another module. Right?

**Comment by max3903** [comment]
@marcelsavegnago Yes, they could be implemented in separate modules, but I only need this module and this one #974 for now.

**Comment by marcelsavegnago** [comment]
@max3903 
image

I didn't realize that you put the neutered attribute in the gender field. I was referring to whether the animal was castrated or not.

**Comment by marcelsavegnago** [comment]
I would appreciate it if a pivot table was included :)

**Pull request merged**
