### PR TITLE
[10.0] Port partner_external_map

### PR DESCRIPTION
**Pull request by alexis-via**
Remove Yahoo Maps
Update URLs for MapQuest

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot. Some tests would be welcome.

**Comment by alexis-via** [comment]
This module has unittests... you are the author of them ! The tests work fine, that's why I didn't change them (apart from the "import" line that I updated).

**Comment by pedrobaeza** [comment]
Yeah, but the coverage drops, so they are not enough! Anyway, it's enough for now.

**Comment by alexis-via** [comment]
I changed didn't add nor remove any line of python code, so I don't see why the coverage drops.

**Comment by pedrobaeza** [comment]
Looking at coveralls, the problem is that the test doesn't include street, street2 and other fields, and that lines remain untested. Not your fault, but as the coverage up to now was so high, it means that drop.

**Review by lasley — APPROVED** [review]
Thanks @alexis-via 

I agree that more tests would be awesome, but non-blocking for me due to the previous code already being untested in production

**Pull request merged**
