### PR TITLE
[ADD] partner_financial_risk 9.0 Port to 10.0

### PR DESCRIPTION
**Pull request by salvatoretrimarchi**
App port from 9.0 to 10.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by pedrobaeza** [comment]
You haven't respected commit history using migration guide. You have to send also the CLA.

**Comment by max3903** [comment]
Hi @salvatoretrimarchi,

Are you planning to fix this pull request and sign the CLA? 

Let us know and we can either wait for you, continue the work from your branch or redo the migration...

**Comment by max3903** [comment]
Hi @salvatoretrimarchi 

Can you make an effort and let us know, please?

Thanks!

**Comment by rafaelbn** [comment]
Hi @salvatoretrimarchi , last news were on 19 Dec 2016 . Please let us know if you are going to continue, thanks!

**Comment by rafaelbn** [comment]
6 months without answer

**Pull request closed without merging**
