### PR TITLE
[FIX] partner_phonecall_schedule: Allow partner managers to use addon

### PR DESCRIPTION
**Pull request by yajo**
Avoids users receiving message:
image

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
groups should be put at view level, not page level.

**Comment by yajo** [comment]
Why? The purpose is to avoid the error message if you cannot edit records for any reason.

**Comment by pedrobaeza** [comment]
For avoiding to give extra permission to everyone that access res.partner form view. Although the page is invisible, the fields are loaded. Same as https://github.com/OCA/account-financial-tools/pull/537

**Comment by yajo** [comment]
OK I get it, it's fixed now.

**Review by carlosdauden — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
