### PR TITLE
[17.0][MIG] partner_second_lastname

### PR DESCRIPTION
**Pull request by AntoniRomera**
- [x] #1606

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]
lgtm

**Review by FernandoRomera — APPROVED** [review]
Test in runboat Ok.

**Comment by FernandoRomera** [comment]
@gurneyalex 
Can you merge this PR?

**Review by gurneyalex — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@gurneyalex fixed

**Comment by AntoniRomera** [comment]
@gurneyalex Can you try again?

**Comment by AntoniRomera** [comment]
@pedrobaeza can you merge?

**Pull request merged**
