### PR TITLE
[13.0] [MIG] portal_partner_data_no_edit: MIgration to v13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT28272

please @chienandalu @sergio-teruel review this.

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Fix travis

**Review by chienandalu — CHANGES_REQUESTED** [review]
Functional test ok but you must fix tests

**Comment by CarlosRoca13** [comment]
@chienandalu @sergio-teruel tests fixed

**Review by chienandalu — APPROVED** [review]
Great! :+1:

**Review by sergio-teruel — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
