### PR TITLE
[17.0][MIG] base_partner_company_group: Migration to 17.0

### PR DESCRIPTION
**Pull request by pedroguirao**

### CODE REVIEW

**Review by ConesaJM — APPROVED** [review]
Works OK

**Review by arquero20022 — APPROVED** [review]
Works OK

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok !!

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please split the changes in 2 commits according the migration guide [1], one for the automatic changes, and the other for the manual ones, and not everything in the `[IMP] base_partner_company_group: pre-commit auto fixes` commit.

[1] https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch

**Comment by MohamedOsman7** [comment]
@pedroguirao still working on it?

**Comment by pedroguirao** [comment]
Thx and sorry for delay.

**Review by MohamedOsman7 — APPROVED** [review]
LGTM

**Review by CRogos — COMMENTED** [review]
Could you also squash commits like these:
Instructions: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

image

**Comment by MohamedOsman7** [comment]
@pedroguirao

**Comment by pedrobaeza** [comment]
Superseded by #1745

**Pull request closed without merging**
