### PR TITLE
[15.0][ADD] partner_user

### PR DESCRIPTION
**Pull request by nikunjantala**

### CODE REVIEW

**Review by cesar-tecnativa — APPROVED** [review]

**Comment by rousseldenis** [comment]
@nikunjantala Why "status" in the module name ?

**Comment by nikunjantala** [comment]
@rousseldenis runboat built because of error from animal module. That we can't fix from our module. Can you please look into it.
Selection_999(263)

**Comment by rousseldenis** [comment]
@nikunjantala Could you rebase as this have been fixed ?

**Pull request closed without merging**
