### PR TITLE
[15.0] [MIG] partner contact gender

### PR DESCRIPTION
**Pull request by lfreeke**

### CODE REVIEW

**Comment by houssine78** [comment]
@lfreeke could you rebase to try to make checks green ? thanks

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
thanks @lfreeke

**Comment by NL66278** [comment]
This is the runbot error, no idea where it comes from:
Unable to find image 'oca-partner-contact:716e2f4_env_1_job_1' locally
docker: Error response from daemon: pull access denied for oca-partner-contact, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Review by Daemo00 — APPROVED** [review]
Thanks!
Code review: looks good to me.

About runbot: can you try rebasing on `15.0`?

**Comment by jappi00** [comment]
Any news on this?

**Comment by dreispt** [comment]
@lfreeke @jappi00 This needs fixing. There is a chance that a rebase on latest 15.0 fixes it.

**Comment by Daemo00** [comment]
> @lfreeke @jappi00 This needs fixing. There is a chance that a rebase on latest 15.0 fixes it.

@dreispt just for your info, it can be done from maintainers with
> /ocabot rebase

(ref. https://github.com/OCA/oca-github-bot#commands)

**Comment by Daemo00** [comment]
Thanks for the rebase, now the CI is complaining because the PR is missing the setup files and folders, you can generate them using https://github.com/acsone/setuptools-odoo#setuptools-odoo-make-default-helper-script

**Review by dhx — APPROVED** [review]
Seems to work ok

**Pull request merged**
