### PR TITLE
[MIG][move] website_portal_conatct : Migration to v14 and moved from …

### PR DESCRIPTION
**Pull request by chandni299**
Module `website_portal_contact`, migrated to v14 and moved from  [OCA/website](https://github.com/OCA/website/tree/10.0) to [OCA/partner-conatct](https://github.com/OCA/partner-contact/tree/14.0) and renamed as `poratl_contact_mgmt`

Ref : [PR #822](https://github.com/OCA/website/pull/822)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems the commit history hasn't been preserved.

**Comment by chandni299** [comment]
> It seems the commit history hasn't been preserved.

I am following the [Migration Doc of OCA](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0), from that when I try to run 
`git format-patch --keep-subject --stdout origin/14.0..origin/10.0 -- website_portal_contact | git am -3 --keep` 
on repo "OCA/partner-contact", It will not apply the patch on it.

Am I missing something?

**Comment by pedrobaeza** [comment]
Yes, you need to tweak the remotes for matching your situation that you are moving the module from another repo. Instead of both being `origin`, you need to create another remote pointing to OCA/website.

**Comment by chandni299** [comment]
> tweak



> Yes, you need to tweak the remotes for matching your situation that you are moving the module from another repo. Instead of both being `origin`, you need to create another remote pointing to OCA/website.

Could you please guide me on how I can do it or do we have any OCA documentation I should follow? I am new to the OCA family

**Comment by pedrobaeza** [comment]
```
$ git clone https://github.com/OCA/partner-contact -b 14.0
$ git checkout -b 12.0-mig-$MODULE origin/12.0
$ git remote add oca-website https://github.com/OCA/website
$ git fetch oca-website 9.0
$ git format-patch --keep-subject --stdout origin/14.0..oca-website/9.0 -- $MODULE | git am -3 --keep
```

**Comment by chandni299** [comment]
> ```
> $ git clone https://github.com/OCA/partner-contact -b 14.0
> $ git checkout -b 12.0-mig-$MODULE origin/12.0
> $ git remote add oca-website https://github.com/OCA/website
> $ git fetch oca-website 9.0
> $ git format-patch --keep-subject --stdout origin/14.0..oca-website/9.0 -- $MODULE | git am -3 --keep
> ```

Yeah. It is working. Thank you for your help :+1:

**Comment by kos94ok-3D** [comment]
Can be closed because it continued here: https://github.com/OCA/partner-contact/pull/1057

**Pull request closed without merging**
