### PR TITLE
[15.0][MIG] portal_partner_data_no_edit: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36489

supersed of https://github.com/OCA/partner-contact/pull/1343

please @sergio-teruel @chienandalu review this

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
I have kept @JoelZilli's migration commit and fixed the issue so that the module works normally

**Comment by CarlosRoca13** [comment]
The problems are something related with `animal` module

**Review by sergio-teruel — APPROVED** [review]
Functional and code review!!

**Review by chienandalu — APPROVED** [review]
Tested. Thanks! :+1:

**Pull request merged**
