### PR TITLE
[MIG] [16.0] partner_address_street3

### PR DESCRIPTION
**Pull request by SodexisTeam**

### CODE REVIEW

**Review by atchuthan — APPROVED** [review]

**Review by amkarthik — APPROVED** [review]

**Review by amkarthik — APPROVED** [review]

**Comment by atchuthan** [comment]
@alexis-via @nbessi @gurneyalex Could you review and merge this PR?

**Comment by atchuthan** [comment]
@OCA/crm-sales-marketing-maintainers Could you review and merge this PR?

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by simahawk — APPROVED** [review]

**Pull request merged**
