### PR TITLE
[15.0][mig]-partner_stage

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
