### PR TITLE
[12.0][ADD] partner_secondary_address: new module

### PR DESCRIPTION
**Pull request by robinkeunen**
This module adds fields for a secondary address on partners.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's no README in the module + I'm not sure about the approach. You are denormalizing data structure, where each `res.partner` record represents an address, so you link to other partner if you need a secondary address instead of adding field.

For me, this is :-1:

**Comment by robinkeunen** [comment]
I thought the readme would be generated by from the `readme` directory.

The use case: within a housing cooperative (similar to real estate), partners may have primary and secondary residencies.

**Comment by pedrobaeza** [comment]
But that's reflected with a parent partner + a child contact with the second residency, indicating in the contact name exactly that. And you can have third residence, forth...

**Comment by robinkeunen** [comment]
Ok, thank you for the suggestion, I'll have a look.

**Pull request closed without merging**
