### PR TITLE
[Update] Partner usps address validation

### PR DESCRIPTION
**Pull request by ckolobow**
Reformatting has been done to ensure OCA compliance.

### CODE REVIEW

**Comment by ckolobow** [comment]
@patrickrwilson

**Comment by cesar-tecnativa** [comment]
Please review pre-commit

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This should go to OCA/l10n-usa

**Comment by patrickrwilson** [comment]
@pedrobaeza we will move this to l10n-usa

**Comment by patrickrwilson** [comment]
Moved to OCA/l10n-usa: https://github.com/OCA/l10n-usa/pull/89
@ckolobow can you close this PR please? It doesn't give me the option.

**Pull request closed without merging**
