### PR TITLE
[18.0] [MIG] partner_firstname: Migration to 18.0

### PR DESCRIPTION
**Pull request by SonoDavid**

### CODE REVIEW

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by xaviedoanhduy** [comment]
> For being easily searchable and avoiding to duplicate efforts, please name the pull request following this pattern: [18.0][MIG] <module>: Migration to 18.0.

**Review by xaviedoanhduy — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by SonoDavid** [comment]
The merge failed, should I do any action in order to make it succeed?

**Comment by SonoDavid** [comment]
I made an update to the commit, maybe this one will succeed on merge

**Comment by SonoDavid** [comment]
Fixed testing and linting issues in this new MR (functionally the same) @rousseldenis

**Pull request merged**
