### PR TITLE
[15.0][MIG] partner_tz

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Just imgrate partner_tz version 14.0 to 15.o

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
> Hey @TheerayutEncoder, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: https://odoo-community.org/page/cla Here is a list of the users:
> 
> * @TheerayutEncoder (login unknown in OCA database)
> 
> Appreciation of efforts, OCA CLAbot

I have signed with CLA now !

**Comment by newtratip** [comment]
@TheerayutEncoder Please rename title to [15.0][MIG] partner_tz

**Comment by rousseldenis** [comment]
@TheerayutEncoder Thanks for this. As @newtratip said, it's better for reviewer to have a meaningful PR's title like suggested.

I've migrated to 16.0 too, with the addition of tests.

You can directly cherry-pick the corresponding commit here : https://github.com/OCA/partner-contact/pull/1464

**Comment by ivilata** [comment]
@newtratip (or any other PSC member), I reviewed the code and it looks good to me. An equivalent update works for us, so maybe the "no stale" label should be applied, the PR reopened and we'd gladly review the code. Thanks a lot!

**Pull request closed without merging**
