### PR TITLE
[7.0] [IMP] partner_relations_in_tab. Clean Code.

### PR DESCRIPTION
**Pull request by NL66278**
Solves problem with tabs for left side relations.

Also:
- Add tests;
- No more need for _register_hook;
- Handles deletions and other changes in relation types directly on loading view.

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hi @NL66278 , maybe @hbrunn codul review here ... this is v7 ! :atom:

**Comment by NL66278** [comment]
@hbrunn Maybe have a look at this old one also. For a long time working now in production for Bisdom.

**Comment by hbrunn** [comment]
/ocabot merge
i trust your approvals for a direct merge, but I'm curious how ocabot reacts to ancient code

**Comment by NL66278** [comment]
I think we should give up on the ocabot merge for 7.0. It is failing now on modules that have nothing to do with this one, because of a version string format that got mandatory long after 7.0 was available, so nearly no module would be compliant.

**Comment by rousseldenis** [comment]
> I think we should give up on the ocabot merge for 7.0. It is failing now on modules that have nothing to do with this one, because of a version string format that got mandatory long after 7.0 was available, so nearly no module would be compliant.

That's a possibility. Note that some processes are done by the bot (publishing to pypi, ...).

That depends if we want to invest time in such old branches (to fix such errors).

**Comment by NL66278** [comment]
@rousseldenis I do not think people will invest time in this. So for PR's < 8.0 I will force merge if appropiate.

**Pull request merged**
