### PR TITLE
[17.0][MIG] partner_contact_access_link: Migration to 17.0

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
LGTM

**Review by CRogos — COMMENTED** [review]
Could you cleanup the commit history according to: 
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

This would also trigger the rebuild because the runboat database is not available anymore, so I could not test. 

LGTM so far

**Comment by rov-adhoc** [comment]
@CRogos Hey! Please let me know if now its ok.
Best regards

**Review by CRogos — COMMENTED** [review]
The module is working fine, but it looks like some of the pre-commit changes are now in the translation commit. 

And also the yellow commits should be merged into the commit above.

image

**Review by igallart — APPROVED** [review]

**Review by CRogos — CHANGES_REQUESTED** [review]
@rov-adhoc are you still working on this?

**Comment by rov-adhoc** [comment]
@CRogos Hey! I have just made the modification. Please let me know if it looks okay now.

Thanks in advance!

**Comment by CRogos** [comment]
@rov-adhoc unfortunate not.
The changes which should be in the "[IMP] partner_contact_access_link: pre-commit auto fixes" commit are in the commit above. 

image

And also the oca-* commits are not squashed.
image

**Comment by CRogos** [comment]
@rov-adhoc are you still working on this?

**Comment by HaraldPanten** [comment]
@CRogos We'll open a new migration PR to manage this. Leave us it in our hands 👍

**Comment by pedrobaeza** [comment]
Superseded by #1758

**Pull request closed without merging**
