### PR TITLE
[16.0][MIG] sale_customer_rank: Migration to 16.0

### PR DESCRIPTION
**Pull request by amarcosg**

### CODE REVIEW

**Review by aliciagaarzo — APPROVED** [review]
Code review LGTM.

**Review by hugo-cordoba — APPROVED** [review]
LGTM (Code Review)

**Comment by hugo-cordoba** [comment]
Hi @rafaelbn, could you take a look and merge? 

Thanksss! Best regards!

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by hugo-cordoba** [comment]
Hello @rafaelbn, it seems that the merge command was not executed correctly, can you try again?

Thankss !!

**Comment by hugo-cordoba** [comment]
thanks @dreispt!

**Pull request merged**
