### PR TITLE
[15.0][FW][IMP] base_partner_sequence: improve write performance

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
FW of https://github.com/OCA/partner-contact/pull/1443

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
Hi @rousseldenis 

Could we reopen this FW and get it merged?

**Review by aliciagaarzo — APPROVED** [review]
LGTM!

**Comment by NL66278** [comment]
@JordiMForgeFlow Please rebase so test will rerun....

**Pull request merged**
