### PR TITLE
[ADD] partner_contact_nutrition_activity_level

### PR DESCRIPTION
**Pull request by max3903**
#335 

Depends on #337

### CODE REVIEW

**Review by lasley — APPROVED** [review]
LGTM thanks @max3903

**Review by susport — COMMENTED** [review]
This is 👍  But I would like the activity level to be a Many2one field to a model example ActivityLevel with this default data already loaded. Thank you.

**Comment by max3903** [comment]
@susport Can we keep that for version 2 of the module? I have run out of time.

**Comment by susport** [comment]
@max3903 yes no problem, it was only a suggestion that can be taken in v2.

**Review by susport — APPROVED** [review]
👍

**Comment by max3903** [comment]
#346

**Pull request merged**
