### PR TITLE
[MIG] partner contact nationality: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Thanks for porting this module. 

Dont understand the design. Nationality should be a many2many, don't you think ?

**Comment by FernandoRomera** [comment]
@legalsylvain 
The nationality must be a single country, as well as the VAT number.

Nationality is for individuals, and it is true that they can have more than one, but if we manage it we would have to start administering more than one VAT number and associate it to each nationality.

**Comment by legalsylvain** [comment]
It is possible to add a constrain, dont you think ?
If it is a company, limit to 1 value.

**Comment by FernandoRomera** [comment]
This is a migration pull request, I had not planned to add functionality. Once this one is approved, we can decide what is right.

**Comment by rousseldenis** [comment]
> It is possible to add a constrain, dont you think ? If it is a company, limit to 1 value.

I don't see the use case as for a company, the nationality has to be the country used for its address (legally)

**Comment by rousseldenis** [comment]
For the multiple instances case, why not using partner_identification_number module and add a country field ?

**Comment by FernandoRomera** [comment]
Nationality is only for individuals, not for companies.  The dependency of this module is clearly identified: partner_contact_personal_information_page

**Review by DoDoViVi — APPROVED** [review]
Tested on Runboat,
work as expected
LGTM
Thanks for the contribution

**Review by MRomeera — APPROVED** [review]
Ok

**Review by AntoniRomera — APPROVED** [review]

**Comment by rousseldenis** [comment]
@legalsylvain Could you update your review ?

**Comment by legalsylvain** [comment]
Thanks for the ping.

Well, AFAIK, this module is only for individuals contact, as it depends on ``partner_contact_personal_information_page`` module. Right ? So no problem with VAT and other stuff, as individual contact doesn't have VAT number. And as @rousseldenis for the companies, we should use the field ``country_id`` of the address part.

In that case, the field should be a M2M. Don't you think ? 
Once decided, the question is when to do that changes. Now or in another PR.

**Comment by FernandoRomera** [comment]
I think it is best to leave this module for those use cases where the primary or sole nationality is identified. In case you want to be able to assign more than one nationality to the partner, you would have to use the module "partner_identification" and not this one.

**Review by MRomeera — APPROVED** [review]
Ok

**Comment by rafaelbn** [comment]
Please @yajo make here a review as original author, it could be of your interest. thank you!

**Comment by FernandoRomera** [comment]
@yajo 
it looks like it's up to you, that this pr will merge. You could check it and then we can move forward. And #1422

**Comment by rousseldenis** [comment]
@FernandoRomera In fact, I see this is a duplicate of #1380

**Comment by FernandoRomera** [comment]
@rousseldenis 
Sorry, we did not see the PR with the migration to 16.0.
For us you can merge the previous PR and we close this one.

**Comment by yajo** [comment]
Closing in favor of #1380. Code there is more up to date.

**Comment by yajo** [comment]
BTW people here: please go there and approve to merge.

**Pull request closed without merging**
