### PR TITLE
[FIX] partner_second_lastname: False value should be set on lastname2

### PR DESCRIPTION
**Pull request by luistorresm**
not firstname

before this commit the following error happen:
name = 'Van-Eyck Jan'

this was converted to

firstname = False
lastname= 'Van-Eyck'
lastname2 = 'Jan'

and it should be like

firstname = 'Jan'
lastname= 'Van-Eyck'
lastname2 = False

### CODE REVIEW

**Comment by luistorresm** [comment]
Hello @moylop260 @pedrobaeza 

This is a fowardport from v10, is necessary to get the approbations?

Regards

**Review by moylop260 — APPROVED** [review]

**Comment by moylop260** [comment]
It is a pre-approved change in other branch

So, maybe we can fast-track it

But let's wait for review

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
