### PR TITLE
[16.0][MIG] partner_priority

### PR DESCRIPTION
**Pull request by KM-joel**
Migration to version 16.0

- the module partner_priority works very well nothing to change just the version that I changed.

### CODE REVIEW

**Comment by KM-joel** [comment]
Hey @patrickrwilson @newtratip @rvalyi 

Request review.

**Review by victor-champonnois — APPROVED** [review]
LGTM

**Review by simahawk — COMMENTED** [review]
LG. Can you please squash your last commit on the migration one?

**Pull request closed without merging**
