### PR TITLE
[8.0][FIX] partner_financial_risk: change view dependency

### PR DESCRIPTION
**Pull request by agaldona**
The credit_limit field is not defined in base, it is defined in account.

### CODE REVIEW

**Review by Daniel-CA — APPROVED** [review]

**Comment by oihane** [comment]
cc @pedrobaeza @Yajo @nbessi @andhit-r @lasley 
Can anyone check this out please, is a minor change. You can see the inherited view and field following this [link](https://github.com/OCA/OCB/blob/8.0/addons/account/partner_view.xml#L156)
Thanks in advance

**Comment by pedrobaeza** [comment]
There's a refactoring pending in #540 that contains this fix I think.

**Comment by oihane** [comment]
@pedrobaeza no, it does not

**Comment by pedrobaeza** [comment]
Please change module version number

**Review by andhit-r — APPROVED** [review]

**Comment by agaldona** [comment]
Version number changed :smile:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
