### PR TITLE
[13.0][MIG] partner_capital

### PR DESCRIPTION
**Pull request by kongrattapong**
Standard Migration.

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by rousseldenis** [comment]
@kongrattapong Could you check pre-commit ?

**Comment by NL66278** [comment]
@kongrattapong It seems pre-commit got even stricter. Please run again...

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
