### PR TITLE
[14.0][MIG] partner_default_sale_discount

### PR DESCRIPTION
**Pull request by lbelorgey**
Migration to 14.0

### CODE REVIEW

**Review by quannguyen1560 — APPROVED** [review]
LGTM!

**Review by FranciscoExposito — APPROVED** [review]
Functional test ok

**Comment by christian-ramos-tecnativa** [comment]
@pedrobaeza Could be possible to reopen this PR? It was even approved and looks ok to me

**Comment by pedrobaeza** [comment]
Sorry, GitHub is not allowing me to reopen the PR. Maybe @lbelorgey or you can propose it again and pinging me, I will take care of the merge.

**Pull request closed without merging**
