### PR TITLE
[11.0] Port of enhancement of geonames import from 10.0 branch

### PR DESCRIPTION
**Pull request by FrancoTampieri**
Port of the #529

### CODE REVIEW

**Comment by FrancoTampieri** [comment]
@pedrobaeza Here I'am again ;)

**Review by pedrobaeza — APPROVED** [review]
Travis + runbot error is unrelated.

**Comment by FrancoTampieri** [comment]
@pedrobaeza can I help to solve the problem on Travis/Runbot?

**Comment by pedrobaeza** [comment]
Well, it's a problem with partner_contact_in_several_companies module. That module shouldn't be merged without rebasing. It was in https://github.com/OCA/partner-contact/pull/507

**Comment by FrancoTampieri** [comment]
@pedrobaeza I've rebased my local repo, so do you suggest to make a branch for partner_contact_in_several_companies to fix all the problems?

**Comment by pedrobaeza** [comment]
OK

**Comment by pedrobaeza** [comment]
You can rebase now.

**Comment by FrancoTampieri** [comment]
@pedrobaeza Here it is :)

**Comment by pedrobaeza** [comment]
The rebase hasn't been correct, as it's includes the changes in `partner_contact_in_several_companies`

**Comment by FrancoTampieri** [comment]
@pedrobaeza doh! mmm How can i Fix that? Is necessary to rollback that changes and rebase again?

**Comment by pedrobaeza** [comment]
Rebase interactively for removing that commits

**Comment by FrancoTampieri** [comment]
@pedrobaeza Thank you man as soon as possible I'll do it!

**Comment by FrancoTampieri** [comment]
@pedrobaeza fixed and rebased 👍

**Review by pedrobaeza — APPROVED** [review]
I fast-track, as this has been approved on 10.0

**Comment by FrancoTampieri** [comment]
👍 Thank you @pedrobaeza

**Pull request merged**
