### PR TITLE
[MIG] base_country_state_translatable: Migration to 17.0

### PR DESCRIPTION
**Pull request by imlopes**

### CODE REVIEW

**Review by jcoux — CHANGES_REQUESTED** [review]
Can you re-organize the commits please?

You did the migration changes on the "[IMP] base_country_state_translatable: pre-commit auto fixes" [commit](https://github.com/OCA/partner-contact/pull/1795/commits/0f2ac621d7bc8fecef4a46e5bb136dc8d00b6f5c).

**Review by yankinmax — APPROVED** [review]

**Review by jcoux — COMMENTED** [review]
Why did you removed the following deb files during the migration?

* pandoc-3.1.12.1-1-amd64.deb
* pandoc-3.1.12.3-1-amd64.deb
* pandoc-3.1.9-1-amd64.deb

Seems not linked to your module and they are already present on 17.0 branch.

**Comment by imlopes** [comment]
> Why did you removed the following deb files during the migration?
> 
>     * pandoc-3.1.12.1-1-amd64.deb
> 
>     * pandoc-3.1.12.3-1-amd64.deb
> 
>     * pandoc-3.1.9-1-amd64.deb
> 
> 
> Seems not linked to your module and they are already present on 17.0 branch.

It's wrote here : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by yankinmax** [comment]
@jcoux we need to remove `deb` binaries

**Review by jcoux — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I wrote it due to this: https://github.com/OCA/oca-addons-repo-template/issues/262

But it's worst than expected, as it has already landed in a lot of repositories. I'm afraid we must do https://github.com/OCA/oca-addons-repo-template/issues/262#issuecomment-2166554143

**Review by Deriman-Alonso — APPROVED** [review]
LGTM 👍.

**Pull request merged**
