### PR TITLE
[14.0][MIG] partner_data_vies_populator

### PR DESCRIPTION
**Pull request by alexis-via**
I made several improvements in the module:
- Improve error handling to avoid crash when Internet connectivity is down
- Read country code from VIES, not from VAT number
- No update of partner when VAT number is invalid
- Improve tests

### CODE REVIEW

**Comment by bosd** [comment]
Is this one ready for review?
Can you trigger a runboat creation?

**Review by rafaelbn — APPROVED** [review]
Thanks @alexis-via

**Comment by rafaelbn** [comment]
@alexis-via could you please rebase to check it it builds runboat?

**Comment by pedrobaeza** [comment]
The `rebase` command doesn't work when the PR has been done from an organization branch, and it's due to GitHub not allowing to repository maintainers to do that although the mark is checked (don't know why this nonsense limitation). Take into account that the rebase is done by the bot, not by you. You only launch the command.

**Review by bosd — APPROVED** [review]

**Review by Shide — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Review by Shide — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Pull request merged**
