### PR TITLE
[IMP] base_partner_company_group: Add one2many counterpart for company_group_id

### PR DESCRIPTION
**Pull request by yankinmax**
Depends on:
- [x] https://github.com/OCA/partner-contact/pull/1324

### CODE REVIEW

**Comment by yankinmax** [comment]
@gurneyalex this is one of the added features to `partner_company_group` that we should take into consideration.

**Review by gurneyalex — APPROVED** [review]

**Review by victoralmau — COMMENTED** [review]
Code review OK.

**Review by victoralmau — APPROVED** [review]
Code review OK

**Pull request merged**
