### PR TITLE
[ADD] 14.0 partner_google_reviews

### PR DESCRIPTION
**Pull request by PierrickBrun**
This allow to integrate google maps reviews on a contact

### CODE REVIEW

**Comment by PierrickBrun** [comment]
The development is not 100% finished, I will squash the commits before the merge

**Comment by PierrickBrun** [comment]
The PR is ready now

**Comment by minhthie** [comment]
Hi, could you please provide an instruction on how to test this? Because I added a google map link but it didn't get the review. Maybe I didn't do it correctly.
Thanks
image

**Comment by PierrickBrun** [comment]
@minhthie You shouldn't have to put the google URL manually, it will be searched via the partner name and city when you click on the "Get Google Reviews" button.

You will also need to put a Google Maps API key in your general settings for it to work

**Pull request closed without merging**
