### PR TITLE
Beautify manifest author list

### PR DESCRIPTION
**Pull request by sbidoul**
This is a rare case where Black needs some human help to produce a beautiful output.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But all the manifests in the rest of the rpos are now modified to the other format. Should we care about this and start introducing specific tweaks?

**Comment by sbidoul** [comment]
I don't care very much :) I made this PR mostly to show an example of how to help Black produce a more readable output in some exotic cases (i.e. by adding the parentheses manually).

**Comment by pedrobaeza** [comment]
What we can do is to open an issue in black itself... 

@Yajo you are the expert in opening issues everywhere :stuck_out_tongue_closed_eyes: would you?

**Comment by yajo** [comment]
How can I know the Black version used?

**Comment by pedrobaeza** [comment]
Isn't the latest one?

**Comment by sbidoul** [comment]
Versions are pinned in .pre-commit-config.yaml

Le mar. 15 oct. 2019 à 14:19, Pedro M. Baeza <notifications@github.com> a
écrit :

**Comment by yajo** [comment]
Thank you. Reported in https://github.com/psf/black/issues/1067.

**Review by yajo — APPROVED** [review]

**Comment by NL66278** [comment]
Ocabot failes because of unrelated error. Website fro geolocations import was not available. Is it possible to just retry the ocabot merge command?

**Comment by pedrobaeza** [comment]
Yes: /ocabot merge

**Pull request merged**
