### PR TITLE
[FIX] partner_industry_secondary: remove a migration script

### PR DESCRIPTION
**Pull request by kos94ok-3D**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you removing this? It's needed.

**Comment by kos94ok-3D** [comment]
Core does not do it?

**Comment by pedrobaeza** [comment]
Not for this

**Comment by kos94ok-3D** [comment]
Maybe it was fixed in core.
I tried installing the module on clean DB - all OK
I tried to migrate from 12 to 13 - all OK

**Comment by pedrobaeza** [comment]
`parent_path` is only computed on save, but it doesn't work like a computed field. Maybe you have retriggered the computation through any action (or a record creation), but it' not done by regular ORM. Anyway, this is not very heavy, so what's the problem?

**Pull request closed without merging**
