### PR TITLE
[15.0][MIG] company_default_partner_pricelist

### PR DESCRIPTION
**Pull request by SergiCForgeFlow**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
CI failing due to https://github.com/OCA/partner-contact/issues/1557.

**Comment by LoisRForgeFlow** [comment]
Rebased after https://github.com/OCA/partner-contact/pull/1559 got merged.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Functional review, it seems that is not working as expected.

I have set a pricelist as de default for a new company:

image

Then I created a new partner and a different pricelist was applied:

image

**Comment by SergiCForgeFlow** [comment]
> Functional review, it seems that is not working as expected.
> 
> I have set a pricelist as de default for a new company:
> 
> image
> 
> Then I created a new partner and a different pricelist was applied:
> 
> image

This is true. Just commited the fix to this error (forwardport of [#1568](https://github.com/OCA/partner-contact/pull/1568)).

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request closed without merging**
