### PR TITLE
[9.0] partner_sector: allow to use in individuals

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
By default only companies have sectors. To activate sectors in individuals also,
you need to activate the following setting:

* Go to *Settings > General Settings > Sector in contacts > Use sector in individuals*

Or, if you have *Sales* or *CRM* modules installed:

* Go to *Sales > Configuration > Settings > Partner Sector > Use sector in individuals*

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@rafaelbn @pedrobaeza I am intending to migrate this feature to 10.0 and 11.0 after this PR is merge. Do you agree with the proposal?

**Review by pedrobaeza — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
code review and tested on runbot :+1:

**Comment by LoisRForgeFlow** [comment]
Travis errors are unrelated.

**Comment by JordiBForgeFlow** [comment]
I renamed the group from "Use sector in individuals" to "Use sector for individuals". Was bad english...

**Comment by MiquelRForgeFlow** [comment]
repo greenifyed :green_apple: 😎

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Wow, how was the runbot to work fine?

**Pull request merged**
