### PR TITLE
[16.0][MIG] base_location_geonames_import: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Standard procedure.
- Convert to private certain tool methods.
- Store and pass as argument recordsets instead of IDs.
- Remove translations quirks as we now have JSONB storage.
- Fix wizard view.

@Tecnativa TT39980

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Tested that the import is blazing fast without the lang quirks, but it takes more than a blink of eye I'm afraid.

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rousseldenis maybe you want to review this one as you did with the base one.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by pedrobaeza** [comment]
Thanks, let's continue with the list of dependencies!

/ocabot merge nobump

**Pull request merged**
