### PR TITLE
[17.0][MIG] account_partner_company_group: Migration to 17.0

### PR DESCRIPTION
**Pull request by MohamedOsman7**
Follow-up PR for #1689

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
Code + Functional review LGTM

**Comment by CRogos** [comment]
@ConesaJM could you review this new PR as well?

**Comment by CRogos** [comment]
@pedroguirao, @Christian-RB could you make a review on these *_company_group modules?

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
