### PR TITLE
[15.0][MIG] partner_contact_birthdate: Migration to 15.0

### PR DESCRIPTION
**Pull request by holdenrehg**
Migration of `partner_contact_birthdate` to 15.0.

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@holdenrehg could you make a rebase and see if it make runboat and oca-ci green again ?

**Comment by rafaelbn** [comment]
Hello @holdenrehg , could you please review https://github.com/OCA/partner-contact/pull/1183#issuecomment-1042347495 thank you!

**Comment by HaraldPanten** [comment]
> /ocabot rebase

Didn't know that the command was working! 🤓

**Comment by houssine78** [comment]
Hi @pedrobaeza the checks are green but the merge instruction fails on the pre-commit step. Do you have an idea on how to fix this ?

image
image

**Comment by pedrobaeza** [comment]
It seems a temporary glitch. Let's retry:

/ocabot merge nobump

**Comment by houssine78** [comment]
Good to know ! Thanks @pedrobaeza ! :)

**Pull request merged**
