### PR TITLE
[17.0][MIG] partner_contact_gender: Migration to 17.0

### PR DESCRIPTION
**Pull request by quoc-pn**

### CODE REVIEW

**Review by smcqueen81 — APPROVED** [review]
Functional Ok

**Review by Daemo00 — CHANGES_REQUESTED** [review]
Thanks for the PR!
I reviewed the code and it looks good 😄

This is missing the translation https://github.com/OCA/partner-contact/commit/e1ae8850b98f5ab06cf3896ff2ffcec5bba04893 of last week, could you please include it?

Could you please also squash the bot commits as explained in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate?

**Comment by quoc-pn** [comment]
@Daemo00 
The missing commit has been added to this pull request, and the bot commits have been squashed.

**Review by Daemo00 — APPROVED** [review]
Thanks!

**Pull request merged**
