### PR TITLE
[15.0][MIG] partner_socialmedia

### PR DESCRIPTION
**Pull request by eabquina**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@eabquina Thanks for this.

Could you follow migration guide ? Especially the full process part ? Thanks

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by rousseldenis** [comment]
Module exists in v12.

Some migration PR's exist too : 

https://github.com/OCA/partner-contact/pull/1284

https://github.com/OCA/partner-contact/pull/1281

**Comment by andres-pcg** [comment]
Hello @eabquina , 

Thank you for your contribution.

Can you please take a look at @rousseldenis comments?

**Comment by andres-pcg** [comment]
Hello @eabquina, 

Have you gotten a chance to check on my previous message? 

Regards,

**Comment by eabquina** [comment]
thanks @rousseldenis @andrp92 for the comment. I haven't found the time to work on this yet. But I would like to do so.

**Pull request closed without merging**
