### PR TITLE
[15.0][MIG] partner_employee_quantity: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36969

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Code review

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Comment by cesar-tecnativa** [comment]
@carlosdauden please review

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
