### PR TITLE
[MIG] crm_deduplicate_by_ref > partner_deduplicate_by_ref: Migration to 12.0

### PR DESCRIPTION
**Pull request by chienandalu**
- Moved and renamed from OCA/crm `crm_deduplicate_by_ref`

cc @Tecnativa TT20201

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks for handling the full renaming

**Comment by chienandalu** [comment]
Thanks to you for the tips :wink:

**Review by ernestotejeda — APPROVED** [review]
:+1:

**Pull request merged**
