### PR TITLE
[MIG] Migration of 'base_continent' module to v10

### PR DESCRIPTION
**Pull request by qtheuret**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
You seem to have missed improvements of this module in the 8.0 branch (while the module was never ported to the 9.0 branch).

Please follow the recommended procedure to migrate modules (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto) with an extra step to also include the latest changes in the 8.0 branch.

**Comment by StefanRijnhart** [comment]
Ah, I see you did take these changes (I was thinking of https://github.com/OCA/partner-contact/pull/462/commits/a9ab617b23efe507bafc880708897b3d1ad17b33 specifically) but you lost the original author on the way. So please try again using `git format-patch`.

**Comment by qtheuret** [comment]
@StefanRijnhart I did `git format-patch .` but I don't know what should be done with the different patch files. Can you explain me the procedure ?

**Comment by StefanRijnhart** [comment]
If you look closely at the code on https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto, you can see that the output of `git format-patch` is piped to `git am`, which commits the changes to the working branch.

I noticed that when running
```
git format-patch --keep-subject --stdout origin/9.0..origin/8.0 -- base_continent | git am -3 --keep
```
there are a lot of conflicts in translation files, because they have been updated independently on the 9.0 and the 10.0 branch. It should be safe to run `git am --skip` to skip those particular patch. After having skipped 8 of those patches, the resulting branch looks very good. After that, run the same command for the changes from 9.0
```
git format-patch --keep-subject --stdout origin/10.0..origin/9.0 -- base_continent | git am -3 --keep
```
and you are good to go.

**Comment by qtheuret** [comment]
Can you check if it's now ok for you ?

**Comment by StefanRijnhart** [comment]
There is something that I don't understand: if you apply the migration process on a fresh checkout, you would get this commit, https://github.com/OCA/partner-contact/commit/d7a950e0ea9531098502bf99c60d0fb9de7ef845#diff-715e5618bd546683c8552854b88d60ba, and it would be assigned to Alexis De Lattre. Your commits contain the same code, but it seems that the changes to the code were applied manually. Did you in fact apply the git-patch process on a fresh checkout of the main branch, or did you apply it on the work that you had already done in your branch?

**Comment by qtheuret** [comment]
I applied on the work that I had already done in my branch.

**Comment by StefanRijnhart** [comment]
I'm afraid you need to start again, from a fresh checkout.

**Comment by qtheuret** [comment]
Ok @StefanRijnhart , I'll start again today

**Pull request closed without merging**
