### PR TITLE
[14.0] [MIG] [MOVE] website portal contact

### PR DESCRIPTION
**Pull request by chandni299**
Module `website_portal_contact`, migrated to v14 and moved from  [OCA/website](https://github.com/OCA/website/tree/10.0) to [OCA/partner-conatct](https://github.com/OCA/partner-contact/tree/14.0) and renamed as `poratl_contact_mgmt`

Ref : [PR #822](https://github.com/OCA/website/pull/822)

### CODE REVIEW

**Comment by chandni299** [comment]
Do we need here any improvement?

**Review by benbrich — APPROVED** [review]
Just finished a functional review on runbot. Everything works as I think it should. Thanks for the migration!

**Comment by MeetKD** [comment]
Sorry @chandni299 i didn't see the  referenced PR in partner contact.

**Comment by hildickethan** [comment]
re-opened here https://github.com/OCA/partner-contact/pull/1391

**Pull request closed without merging**
