### PR TITLE
15.0 mig partner contact department

### PR DESCRIPTION
**Pull request by Galoperd**

### CODE REVIEW

**Comment by Galoperd** [comment]
Hi, I did  "snap install pre-commit --classic"  is there another recommended pre-commit install process ?

**Comment by luisg123v** [comment]
@Galoperd you're touching files of other modules.

**Comment by rousseldenis** [comment]
Hi @Galoperd Thanks for this. Could you follow this migration guide:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by Galoperd** [comment]
Hi, sorry to bother all of you, I solved my problem with python env and pre-commit tool install so I will start over again with a new PR and close this one, thanks !

**Pull request closed without merging**
