### PR TITLE
[16.0][IMP] base_partner_sequence: improve write performance

### PR DESCRIPTION
**Pull request by aliciagaarzo**
Prevent forcing to do record by record write always and for all the records, and only do it when needed.

Implement improvement https://github.com/OCA/partner-contact/pull/1452

### CODE REVIEW

**Review by amarcosg — APPROVED** [review]
LGTM!

**Review by dalonsofl — APPROVED** [review]
LGTM!

**Comment by imoralesc** [comment]
Hello @pedrobaeza, we have an improvement to avoid forcing the write record by record always, and do it only when necessary. Could you take a look at it and merge it?

**Comment by pedrobaeza** [comment]
OK. I think this module is over-engineered, checking on each write for the sequence, while it should be only on create, but this performance improvement is welcome not touching the main reason of the bottleneck.

Anyway, I don't use this module in any of my customers, as the partner reference is something anachronistic, and I recommend you to recheck its need. It's hard at the beginning to convince old users about its lack of need, but they won't miss it in few weeks.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Can you please rebase to see if the CI is OK?

**Comment by amarcosg** [comment]
Thanks for the feedback @pedrobaeza, I just did the rebase and the error has to do with being February 29th in the test of partner_contact_age_range.

Bad luck i guess, i will try again tomorrow :disappointed:

**Comment by pedrobaeza** [comment]
Well, the test should be designed for not having that problems...

Usually, it's a problem of the test having "variable dates" based on today, and it's bypassed freezing the date with `freezegun`, but if it's showcasing a problem in the feature itself that won't work on this day, then it should be correctly programmed.

I know it's not your module, but if you want to explore this as exercise, go ahead.

If not, ping me tomorrow to launch again the merge command.

**Comment by amarcosg** [comment]
Sure no problem, I've already made the change so we can make sure it doesn't happen again.

**Comment by pedrobaeza** [comment]
Great, thanks, but you have forgotten to put the module name in the commit message. And have you checked if the problem is in the tests or in the inner feature?

**Comment by amarcosg** [comment]
Right, I have already added the module name. I have not entered to validate the functionality of the module to check if the problem is in the inner feature, I have limited myself only to the test

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
