### PR TITLE
[18.0] [MIG] partner_contact_personal_information_page: Migration to 18.0

### PR DESCRIPTION
**Pull request by Borruso**
Migration from 17.0 to 18.0

Issue: https://github.com/OCA/partner-contact/issues/1856

### CODE REVIEW

**Review by houssine78 — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]

**Comment by Sanazzzmi** [comment]
@rousseldenis @OCA-git-bot 
Hello. Could you please assist with migrating this module? I would greatly appreciate your help.

Thank you!

**Comment by mostafabarmshory** [comment]
@OCA-git-bot  @pedrobaeza @rousseldenis

Hello. I need this module. Please merge it for version 18 as soon as possible. Thanks

**Review by Sanazzzmi — APPROVED** [review]

**Review by mostafabarmshory — APPROVED** [review]

**Pull request merged**
