### PR TITLE
[15.0] Migration base_partner_sequence

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@dreispt can you please merge this PR? thanks

**Comment by ghost** [comment]
@dreispt can you please try to merge again this PR? thanks

**Comment by rousseldenis** [comment]
@OpenCode Could you rebase ?

**Comment by OpenCode** [comment]
> @OpenCode Could you rebase ?

Done

**Review by rousseldenis — APPROVED** [review]
@OpenCode Thanks for this. Next time can you follow migration guide as version change for instance should be in migration commit.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

**Comment by OpenCode** [comment]
> @OpenCode Thanks for this. Next time can you follow migration guide as version change for instance should be in migration commit.
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

I actually followed that guide. Where is the wrong step? Can you help me to understand?

**Comment by rousseldenis** [comment]
> > @OpenCode Thanks for this. Next time can you follow migration guide as version change for instance should be in migration commit.
> > https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch
> 
> I actually followed that guide. Where is the wrong step? Can you help me to understand?

I think you omit the --no-verify option. If so, the commit will reformat and you had the error that said your module version is wrong.

image

So, you included the version change in the first commit and not the migraiton one. But nitpicking

**Review by BT-aestebanez — APPROVED** [review]

**Pull request merged**
