### PR TITLE
Add ondelete option to parent_id, runbot fails to lack of attribute.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
@OCA/crm-sales-marketing-maintainers Allow travis and runbot greenify.

**Comment by pedrobaeza** [comment]
I prefer to keep children department with null as parent. Why this new behaviour?

**Comment by feketemihai** [comment]
@pedrobaeza Should i change it then to 'restrict' ...

**Comment by pedrobaeza** [comment]
I would let it as is. The default is "set null", which seems perfectly fine for me.

**Comment by feketemihai** [comment]
@pedrobaeza Seems to be a new check in creating parent on the server side, please see https://runbot.odoo-community.org/runbot/build/3140208 errors...

**Comment by feketemihai** [comment]
https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L2757

**Comment by pedrobaeza** [comment]
Uhm, I didn't know about that one. Then I see better 'restrict' for avoiding accidental lose of data.

**Comment by StefanRijnhart** [comment]
It's because the parent store is otherwise not properly updated upon a deletion. :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yajo** [comment]
:+1:

**Pull request merged**
