### PR TITLE
[15.0][FIX] base_location: Fix development_status

### PR DESCRIPTION
**Pull request by ValentinVinagre**

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten @pedrobaeza other more 🍡 .

**Comment by ValentinVinagre** [comment]
@sbidoul is anything wrong with pre-commit/action@v2.0.0? An error related to setuptools library is being shown.
Should we change setuptools version in .pre-commit-config file to 3.0.5?

**Comment by pedrobaeza** [comment]
On the latest copier template, it was changed to 2.0.3 (https://github.com/OCA/oca-addons-repo-template/commit/2ed3a162cb4c78658dd6405abffe6857e8906178). Try to put that here to see.

**Comment by ValentinVinagre** [comment]
> On the latest copier template, it was changed to 2.0.3 ([OCA/oca-addons-repo-template@2ed3a16](https://github.com/OCA/oca-addons-repo-template/commit/2ed3a162cb4c78658dd6405abffe6857e8906178)). Try to put that here to see.

Same error :/

**Comment by sbidoul** [comment]
@ValentinVinagre @pedrobaeza see https://github.com/OCA/oca-addons-repo-template/pull/101

**Comment by HaraldPanten** [comment]
> @ValentinVinagre @pedrobaeza see [OCA/oca-addons-repo-template#101](https://github.com/OCA/oca-addons-repo-template/pull/101)

Seems that Simone's test did work in EDI repository.

@ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
@pedrobaeza you have "the last word" on it.

**Comment by ValentinVinagre** [comment]
@sbidoul :D thanks

**Comment by pedrobaeza** [comment]
@sbidoul is the token again expired/rejected?

**Comment by sbidoul** [comment]
The token is just fine, it does not have permission to change github workflows.
But the issue has been fixed upstream so the workflow change should not be necessary anymore.

**Comment by pedrobaeza** [comment]
Ah, right. @ValentinVinagre can you please undo such change?

**Comment by ValentinVinagre** [comment]
> Ah, right. @ValentinVinagre can you please undo such change?

Done

**Comment by ValentinVinagre** [comment]
ue :D

**Pull request merged**
