### PR TITLE
All modules provided with initial de.po within folder i18n for german language

### PR DESCRIPTION
**Pull request by rschnapka**
basic translation create file de.po for each module. If any header-info should differ, please give me a hint... thanks.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase your branch, because this can be automatically merged. I think this is because you have duplicated one of the translation that it's already merged.

**Comment by rschnapka** [comment]
(Happy new year)
I am not quite sure about what i need to do here. I tried a rebase - git says it's up to date... do i need to close this pull request and initiate a new one? Issue most probably is/was the template-translation file base_continent/i18n/base_continent.po → base_continent/i18n/base_continent.pot
that i renamed from *.po to *.pot - which i presume should be done or?
In the worst case i would just fork again and add the translations again...
thank you for the assistance here!

**Comment by pedrobaeza** [comment]
You can start from a fresh branch just pulled, make the additions (or moves), and push against this branch with -f option to force the overwritting, and thus you don't need to close this PR.

**Comment by rschnapka** [comment]
I hope the branch now is clean for an automatic pull... still awaiting approval of my OLA - I believe the runbot mechanisms fail due to that missing.

**Comment by yvaucher** [comment]
to rebase some translation are conflicting

**Comment by rafaelbn** [comment]
@rschnapka are you agree to close this PR? It look you are not going to continue it. Let me know please

**Comment by rschnapka** [comment]
Yes, I agree. Thanks.

**Pull request closed without merging**
