### PR TITLE
13.0 mig partner address street3 v2

### PR DESCRIPTION
**Pull request by jcdrubay**
Trying to finalize #823 (second attempt replacing https://github.com/OCA/partner-contact/pull/1064)

### CODE REVIEW

**Comment by jcdrubay** [comment]
@NL66278 Do I really need to add extra automatic tests for this PR? Could we skip that with a development status on the module?

**Comment by NL66278** [comment]
@jcdrubay Extra tests would be helpful, but I will not block the PR on that.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM Thanks for quickly taking up comments.

**Comment by jcdrubay** [comment]
Thank you @NL66278 

Unless some reviewers submits any blocking point, we just need to wait 5 days for the merge I guess. 

(I don't expect 3 reviews before these 5 days ;) )

**Review by kos94ok-3D — APPROVED** [review]
LGTM

**Pull request merged**
