### PR TITLE
[16.0][MIG] partner_contact_birthplace

### PR DESCRIPTION
**Pull request by Borruso**
Migration from 14.0 to 16.0

Issue: https://github.com/OCA/partner-contact/issues/1353

### CODE REVIEW

**Review by salvorapi — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by enriquemartin — APPROVED** [review]

**Review by Deriman-Alonso — APPROVED** [review]
LGTM 👍.

**Review by lorenzoallegrucci — APPROVED** [review]

**Review by amosdisabatino — APPROVED** [review]

**Review by matteoopenf — APPROVED** [review]

**Comment by matteoopenf** [comment]
@pedrobaeza  is possibile to merge?

**Pull request merged**
