### PR TITLE
[11.0][MIG] partner_coc

### PR DESCRIPTION
**Pull request by astirpe**
Porting of partner_coc to V11. Some tests added.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by astirpe** [comment]
@pedrobaeza done

**Review by hieulucky111 — APPROVED** [review]

**Review by novawish — APPROVED** [review]
Looks good to me overall

**Comment by astirpe** [comment]
Thanks!

**Pull request merged**
