### PR TITLE
[17.0][MIG] partner_company_group: Migration to 17.0

### PR DESCRIPTION
**Pull request by MohamedOsman7**

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
Code review LGTM

**Comment by CRogos** [comment]
@pedroguirao, @Christian-RB could you make a review on these *_company_group modules?

**Comment by gurneyalex** [comment]
Depends on:

- [x] https://github.com/OCA/partner-contact/pull/1745
- [x] https://github.com/OCA/partner-contact/pull/1753
- [x] https://github.com/OCA/partner-contact/pull/1730
- [x] https://github.com/OCA/partner-contact/pull/1727

**Review by gurneyalex — APPROVED** [review]

**Comment by MohamedOsman7** [comment]
@gurneyalex Could you merge please

**Comment by CRogos** [comment]
@pedrobaeza can you merge, thank you.

**Comment by pedrobaeza** [comment]
@gurneyalex has been following this module suite and I think it should be him who does the honors.

**Pull request merged**
