### PR TITLE
[10.0][FIX] Added is_company field for the domain constraint

### PR DESCRIPTION
**Pull request by thinkwelltwd**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't that field already present? Please explain your steps to reproduce an error.

**Comment by thinkwelltwd** [comment]
>Please explain your steps to reproduce an error.

1. Installed the module
2. Clicked "Edit" on a company
3. In the Contacts & Addresses tab, clicked "Create".
4. Get the traceback below.

```
Uncaught Error: Unknown field is_company in domain [["is_company","=",true]]

http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:1766
Traceback:
Error: Unknown field is_company in domain [["is_company","=",true]]
    at Object.compute_domain (http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:1766:42)
    at Class.compute_domain (http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:2187:344)
    at Class.<anonymous> (http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:2221:364)
    at Class.trigger (http://localhost:8069/web/content/5796-d5f2679/web.assets_common.js:3099:180)
    at Class.trigger (http://localhost:8069/web/content/5796-d5f2679/web.assets_common.js:3103:148)
    at Class.on_form_changed (http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:2137:98)
    at Array.<anonymous> (http://localhost:8069/web/content/5944-a0e895c/web.assets_backend.js:2134:6)
    at Array.<anonymous> (http://localhost:8069/web/content/5796-d5f2679/web.assets_common.js:547:681)
    at fire (http://localhost:8069/web/content/5796-d5f2679/web.assets_common.js:541:299)
    at Object.add [as done] (http://localhost:8069/web/content/5796-d5f2679/web.assets_common.js:542:467)
```

So I added the `is_company` field which fixed my problem.

**Comment by thinkwelltwd** [comment]
Actually, it looks like v9 has the same problem. I didn't look before sending in to PR, but #514 makes the identical field addition.

**Comment by pedrobaeza** [comment]
Please change module version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Review by pedrobaeza — APPROVED** [review]
Well, it's a change that requires update, but it's not the most important thing to rise intermediate version number.

**Review by yajo — APPROVED** [review]

**Pull request merged**
