### PR TITLE
[14.0][MIG] base_partner_sequence: migration to 14.0

### PR DESCRIPTION
**Pull request by gbaumgartner-callino**
Working as intended.

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
Can be closed #1075 had already been merged.

**Comment by rousseldenis** [comment]
> Can be closed #1075 had already been merged.

@CasVissers-360ERP Done in 2020 :smile:

**Comment by CasVissers-360ERP** [comment]
https://www.youtube.com/watch?v=-Kobdb37Cwc

**Comment by rousseldenis** [comment]
> https://www.youtube.com/watch?v=-Kobdb37Cwc

Nice reference !!

**Pull request closed without merging**
