### PR TITLE
[17.0] [IMP] partner_contact_gender: improve readme and icon

### PR DESCRIPTION
**Pull request by polchampion**
OCA Days workshop - improving documentation by fucntionals

### CODE REVIEW

**Review by remi-filament — APPROVED** [review]
Looks good,
Thanks for this first contribution !
Maybe commits should be squashed during merge to keep history clean ?

**Comment by polchampion** [comment]
@gurneyalex Do you think this can be merged?

**Comment by polchampion** [comment]
@TumbaoJu My OCA Days PR seems stuck... how should I proceed?

**Comment by houssine78** [comment]
@polchampion you're missing some approvals to allow the merge. Could squash your commits into one as asked by Rémi? ping me back when it's done I'll approve the PR.

**Comment by TumbaoJu** [comment]
@remi-filament @houssine78  : As discussed during the OCA Days, the commit squash is not required for Read me PR.

Non-technical persons wrote those PR and have not the knowledge to be able to squash the commits so we agreed that for Read me PR, it would not be mandatory.

Thank you in advance for your help.
@polchampion : FYI

**Review by TumbaoJu — APPROVED** [review]

**Comment by houssine78** [comment]
Hi @TumbaoJu ,

Thanks for the info, I wasn't aware of this.

**Review by houssine78 — APPROVED** [review]
small non technical changes.

**Comment by houssine78** [comment]
Hi @pedrobaeza this PR is ready for merging

**Review by rousseldenis — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash both icon commits into one. About the icon itself, I understand the motivations for changing it, but I think the icon is not self-representative. It can be easily confused with a country flag, and it's also not incorporating a contact representation. It can be at least a merge of the avatar icon (like https://github.com/OCA/partner-contact/blob/16.0/partner_contact_lang/static/description/icon.png) with the flag in one corner.

**Pull request merged**
