### PR TITLE
Port base_location_geonames_import to v10

### PR DESCRIPTION
**Pull request by alexis-via**
Add option to put city name all upper case

- [x] This PR requires #317

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Restarted builds now that the dependency is merged.

**Comment by pedrobaeza** [comment]
@moylop260, the error in this runbot is very weird (https://runbot.odoo-community.org/runbot/static/build/3276641-320-bf1b2f/logs/job_20_test_all.txt):
```
command:  /entrypoint_image
sed: can't read /root/*/openerp/cli/server.py: No such file or directory
```

**Comment by moylop260** [comment]
The real error is 
`2016-12-30 16:33:57,252 187 ERROR openerp_test odoo.modules.graph: module base_location_geonames_import: Unmet dependencies: base_location`
Maybe a missing oca_dependency or a renamed of module?

**Comment by moylop260** [comment]
Wait... travis is not present this error.
Let me see...

**Comment by lasley** [comment]
`base_location` in this branch is set to not installable. Perhaps needs a rebase on current 10?

https://github.com/akretion/partner-contact/blob/bf1b2f5041365b1956ae4a83bd8248ebf2efa3a7/base_location/__manifest__.py#L52

**Comment by pedrobaeza** [comment]
Rebased

**Comment by pedrobaeza** [comment]
I have changed the menu entry and improve tests for full coverage, so this is ready to be reviewed.

**Review by moylop260 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
