### PR TITLE
[15.0][MIG] partner_deduplicate_by_ref: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36478

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@pedrobaeza could you please review?

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 could you please review?

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Comment by cesar-tecnativa** [comment]
@sergio-teruel please review

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
