### PR TITLE
[15.0][MIG] partner_company_group: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @CarlosRoca13 and @cesar-tecnativa can you review it?

@Tecnativa TT36476

### CODE REVIEW

**Review by CarlosRoca13 — COMMENTED** [review]
Code review :+1:

**Review by CarlosRoca13 — APPROVED** [review]

**Review by cesar-tecnativa — APPROVED** [review]

**Comment by rousseldenis** [comment]
@victoralmau Could you address this in a separate commit (we could backport) ? Thanks

https://github.com/OCA/partner-contact/issues/1325

**Comment by victoralmau** [comment]
> @victoralmau Could you address this in a separate commit (we could backport) ? Thanks
> 
> #1325

Changes done.

**Review by pedrobaeza — APPROVED** [review]

**Comment by gurneyalex** [comment]
See https://github.com/OCA/partner-contact/issues/1345

**Pull request merged**
