### PR TITLE
[14.0][MIG] portal_partner_select_all: Migration to 14.0

### PR DESCRIPTION
**Pull request by skeller1**
Standard migration to V14

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by skeller1** [comment]
BTW: Is there a problem with the oca runbots. Can't access them from the runbot dashboard. Always redirecting to runbot.odoo-community.org

**Comment by pedrobaeza** [comment]
Yes, it seems so cc @sbidoul @gurneyalex

**Comment by HaraldPanten** [comment]
> BTW: Is there a problem with the oca runbots. Can't access them from the runbot dashboard. Always redirecting to runbot.odoo-community.org

yep

**Review by ioans73 — APPROVED** [review]
Functional review

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
