### PR TITLE
[15.0][MIG] base_location_geonames_import: Migration to 15.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Standard procedure

@Tecnativa TT32981

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Works fine for me.

**Review by victoralmau — APPROVED** [review]
Code review OK.

**Comment by pedrobaeza** [comment]
@gurneyalex @sbidoul can we avoid now the runbot triggering in 15.0 branches for not seeing the ugly red that may confuse contributors?

**Pull request merged**
