### PR TITLE
[14.0][REF] partner_tier_validation: do not archive, depend on partner_stage

### PR DESCRIPTION
**Pull request by dreispt**
Major change.
Supersedes #1142 

- [x] Depends (bundles) #1192

### CODE REVIEW

**Comment by vongoethe** [comment]
I tested this pull. When I created a new contact, I can use it freely without validation. and the validation rule has been already set and unarchived. The depends of partner_stage has already been installed.
Is this normal? How is the validation process mean?

**Comment by dreispt** [comment]
Try using the demo user.

**Comment by vongoethe** [comment]
> Try using the demo user.
> […](#)
> No dia 02/02/2022, às 09:50, vongoethe ***@***.***> escreveu: ﻿ I tested this pull. When I created a new contact, I can use it freely without validation. and the validation rule has been already set and unarchived. The depends of partner_stage has already been installed. Is this normal? How is the validation process mean? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.

Yes, I tested again with the test1 user name.
And what I mean is the validation process does run smooth. But without validation confirmed, I can still choose the new created contact (in 'to approve' stage) in the sales order and purchase order or so. And the new contacts with no validation confirmed are still shown in the Contact list.
So I need to add a filter to limit users to use unapproved contacts in sales order and other modules?
Thank you

**Comment by dreispt** [comment]
That needs to be implemented in a separate module, not done yet.

If the you tested the approval process, please submit a review, to allow this being merged.

Thanks 

--dr

**Review by vongoethe — APPROVED** [review]
Works great!

**Comment by dreispt** [comment]
@vongoethe can you please add a review to #1192?

**Comment by vongoethe** [comment]
> @vongoethe can you please add a review to #1192?

Sure.

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
@dreispt the README could be improved in the usage section. I haven't been able to test it with demo user following it

> [Usage](http://oca-partner-contact-14-0-pr1216-4f93a0666b4a.runboat.odoo-community.org/web?#id2)
> 
> A regular user creates a new Contact and sends it for approval:
> 
>    Create a Contact triggering at least one “Tier Definition”. The Contact will be in Draft state and marked as Archived until approved.
>     Click on Request Validation button.
>     In the Reviews section, at the bottom of the form, inspect the pending reviews and their status.
> 
> The approver reviews Contacts to approve:
> 
>    Navigate to the Contacts app, and select the filter “Needs my Approval”
>     Open the Contact form to approve. It will display a “This Records needs to be validated” banner, with “Validate” and “Reject” options.
>     The approver can change the state to “Active”. This will automatically unarchive the record and make it available to be used.
> 
> The Approve/Reject actions do not automatically change the State. This could be a future improvement.

**Comment by dreispt** [comment]
@rafaelbn I'm sorry, this merge was too fast. I'll create a PR soon to address your comments.

**Comment by dreispt** [comment]
@rafaelbn see https://github.com/OCA/partner-contact/pull/1233

**Pull request merged**
