### PR TITLE
[16.0][IMP] partner_contact_address_default: set default contact

### PR DESCRIPTION
**Pull request by LauraCForgeFlow**
Implement the possibility to add a default contact along with the delivery and invoice addresses for partners.

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Review by MarinaAForgeFlow — APPROVED** [review]
Code review. LGTM.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
