### PR TITLE
[17.0][MIG] partner_disable_gravatar

### PR DESCRIPTION
**Pull request by remi-filament**

### CODE REVIEW

**Review by DorianMAG — APPROVED** [review]
LGTM.
Thx for the migration

**Comment by DorianMAG** [comment]
@flotho @gaelTorrecillas
Can you make a review plz?

**Review by gaelTorrecillas — APPROVED** [review]

**Review by amh-mw — APPROVED** [review]

**Comment by amh-mw** [comment]
@OCA/crm-sales-marketing-maintainers Merge?

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
