### PR TITLE
[16.0] [MIG] partner_contact_nationality

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by marielejeune** [comment]
Depends on https://github.com/OCA/partner-contact/pull/1379

**Comment by marielejeune** [comment]
https://github.com/OCA/partner-contact/issues/1353

**Comment by rafaelbn** [comment]
Hello @marielejeune , are you active with this PR? As is duplicated with https://github.com/OCA/partner-contact/pull/1421 we can merge that one (already reviewed) or review here. You PR, this one has preference. Thank you!

**Review by yajo — APPROVED** [review]

**Comment by marielejeune** [comment]
Hi  @rafaelbn, yes I'm still active on this PR, waiting for more reviews.

**Review by FernandoRomera — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
