### PR TITLE
[13.0][MIG] partner company type

### PR DESCRIPTION
**Pull request by Laurent-Corron**

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
Thank you @Laurent-Corron for the migration.
Nevertheless can you remove the `goup_no_one` on the menu to get access to the list of company types. This group prevents members having access to the Configuration menu into contacts to get access to the company types sub menu https://github.com/OCA/partner-contact/blob/a1a1d8215237e927ff27998f9389cf31c0f97230/partner_company_type/views/res_partner_company_type.xml#L52

**Comment by Laurent-Corron** [comment]
@lmignon fixed!

**Review by lmignon — APPROVED** [review]
Thank you @Laurent-Corron (Functional + code)

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Pull request merged**
