### PR TITLE
8.0 add missing oca icons

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1: let's see how many modules this breaks...

**Comment by pedrobaeza** [comment]
hehe, we have now another CI testing with static folders...

**Comment by yvaucher** [comment]
@pedrobaeza @hbrunn :smile:

**Pull request merged**
