### PR TITLE
[9.0][PORT] port base location

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe you can take the occasion to make some tests for this module.

**Comment by charbeljc** [comment]
@pedrobaeza I would tend to merge as is, and focus on adding coverage reports first, so :+1:

**Comment by pedrobaeza** [comment]
The coverage reports are already there... via coveralls.io

**Comment by charbeljc** [comment]
hum, can't see it on this page ?

**Comment by pedrobaeza** [comment]
It can be due to the high-traffic that is happening because the 9.0 branch migration, but it was working fine.

**Comment by yvaucher** [comment]
@pedrobaeza Here we go all onchanges tested

**Comment by pedrobaeza** [comment]
Thank you very much! Waiting for Travis result, :+1:

**Comment by yvaucher** [comment]
Travis is :green_heart:

**Comment by pedrobaeza** [comment]
Perfect, I merge then

**Pull request merged**
