### PR TITLE
[10.0] hide better_zip_id if not in edit mode

### LINKED ISSUE #527: [10.0] hide better_zip_id in res.company if not in edit mode
in res.company form better_zip_id is visible even if not in edit mode

### PR DESCRIPTION
**Pull request by 2zx**
as done on partner_view.xml
fixes #527

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I want to see it. Why hide it?

**Comment by 2zx** [comment]
Because in my configuration the field duplicates the addresses information.
The company's form shows field better_zip_id + city + state_id + zip + country_id
The partner's form (which also uses better_zip_id) hide that field in view mode.

**Comment by pedrobaeza** [comment]
But this is very opinionated. Let's see what others think.

**Comment by 2zx** [comment]
ok, thanks.
In my opinion it is a matter of consistency with the partner's form

**Comment by yajo** [comment]
Could you post pictures of the bug and the fix please?

**Comment by 2zx** [comment]
res.company form with better_zip_id not hidden (view mode), address info is duplicated

no_fix

res.company form with better_zip_id hidden (view mode)

fix

**Review by yajo — APPROVED** [review]

**Review by NL66278 — APPROVED** [review]
:+1: LGTM and I agree that duplication of information in the form is not desirable.

**Pull request merged**
