### PR TITLE
7.0 no context no crash

### PR DESCRIPTION
**Pull request by NL66278**
Got errors when configuring auditlog for relation. However the problem was in two name_get routines in partner_relations.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And this one?

**Comment by NL66278** [comment]
@pedrobaeza And yes, this one is also still relevant

**Comment by pedrobaeza** [comment]
There are several pylint errors related to your module:
```
************* Module partner_relations.__openerp__
partner_relations/__openerp__.py:21: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
partner_relations/__openerp__.py:21: [C8106(manifest-version-format), ] Wrong Version Format "1.1" in manifest file. Regex to match: "(7.0)\.\d+\.\d+\.\d+"
************* Module partner_relations.model.res_partner_relation_all
partner_relations/model/res_partner_relation_all.py:55: [E8103(sql-injection), ResPartnerRelationAll._auto_init] Use of "%" operator in execute database method. Better use parameters instead. - More info https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#no-sql-injection
partner_relations/model/res_partner_relation_all.py:122: [W8106(method-required-super), ResPartnerRelationAll.write] Missing `super` call in "write" method.
************* Module partner_relations.model.res_partner_relation_type_selection
partner_relations/model/res_partner_relation_type_selection.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`
partner_relations/model/res_partner_relation_type_selection.py:33: [W7950(odoo-addons-relative-import), ] Same Odoo module absolute import. You should use relative import with "." instead of "openerp.addons.partner_relations"
partner_relations/model/res_partner_relation_type_selection.py:61: [E8103(sql-injection), ResPartnerRelationTypeSelection._auto_init] Use of "%" operator in execute database method. Better use parameters instead. - More info https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#no-sql-injection
```

**Comment by NL66278** [comment]
I do not understand the runbot error. I do not see anything wrong in the logs.

**Comment by pedrobaeza** [comment]
It's due to these warnings:
```
2017-01-11 16:31:26,565 184 INFO openerp_test openerp.modules.loading: module partner_relations: loading view/res_partner_relation_type.xml
2017-01-11 16:31:26,567 184 WARNING openerp_test openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.
2017-01-11 16:31:26,572 184 WARNING openerp_test openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.
2017-01-11 16:31:26,576 184 INFO openerp_test openerp.modules.loading: module partner_relations: loading view/menu.xml
2017-01-11 16:31:26,587 184 INFO openerp_test openerp.modules.loading: module partner_relations: loading security/ir.model.access.csv
2017-01-11 16:31:26,615 184 INFO openerp_test openerp.modules.loading: module partner_relations: loading data/demo.xml
2017-01-11 16:31:26,661 184 INFO openerp_test openerp.modules.module: module partner_relations_in_tab: creating or updating database tables
2017-01-11 16:31:26,712 184 INFO openerp_test openerp.modules.loading: module partner_relations_in_tab: loading view/res_partner_relation_type.xml
2017-01-11 16:31:26,714 184 WARNING openerp_test openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.
```

**Comment by NL66278** [comment]
I think it is ready to merge now...

**Review by pedrobaeza — APPROVED** [review]
OK, merging as well

**Pull request merged**
