### PR TITLE
10.0 mig base continent

### PR DESCRIPTION
**Pull request by qtheuret**
Following problems described in https://github.com/OCA/partner-contact/pull/462 I made a new pull request to fix them.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks for this new version! The migration seems fine now. I see you added a small functional extension: a code field on the continents. You also added codes to the continents in the data, but this won't be processed when people migrate from 9.0 to 10.0 because the data is noupdate. Can you add a migration script that adds the codes to continents upon migration to version 10.0.1.0.1?

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please squash together adjacent "OCA Transbot..." commits? The one removing en.po can be squashed together as well.

**Comment by qtheuret** [comment]
Ok, done. I hope I did it correctly.

**Comment by pedrobaeza** [comment]
I'm afraid not:

seleccion_003

and now there's even a lot of more commits...

**Comment by qtheuret** [comment]
@pedrobaeza It seems good now but there is an error with Travis. Did I missed something ?

**Comment by pedrobaeza** [comment]
The squash still is not good, as you have joined all the string at the beginning, but there should be 2 commits. You only need to squash adjacent commits.

About Travis, it was a temporary flick. I have restarted and for sure it will be correct now.

**Pull request closed without merging**
