### PR TITLE
Fix imports at top of file.

### PR DESCRIPTION
**Pull request by feketemihai**
Allow to greenify 8.0 PR's

Still i don't get it why we should have a function in the init file...

### CODE REVIEW

**Comment by feketemihai** [comment]
@OCA/crm-sales-marketing-maintainers Allow travis and runbot greenify.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by feketemihai** [comment]
@Yajo @StefanRijnhart Can you review this please to greenify the repo...

**Comment by yajo** [comment]
Runbot error not related. :+1:

**Pull request merged**
