### PR TITLE
Update better_zip.py

### PR DESCRIPTION
**Pull request by ghost**
Bugfixing => name_get, cast to str.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why do you need the casting?

**Comment by ghost** [comment]
@pedrobaeza : this method collects all the information to be shown in a list (name)  and later it executes:  ", ".join(name).

The problem is that the information in this list may contain Boolean values.  When we  try to perform the operation it crashes. 

Test example:
", ".join(['anything', False])

Solution: To cast to str before executing join.

**Comment by pedrobaeza** [comment]
But the only condition to appear False is because city field is empty (the rest are checked), and this field is mandatory (https://github.com/OCA/partner-contact/blob/8.0/base_location/better_zip.py#L35), so there's no such possibility.

**Comment by ghost** [comment]
@pedrobaeza : I agree with you

**Comment by pedrobaeza** [comment]
OK, so can I close this PR?

**Comment by ghost** [comment]
Thank you I did it

2014-12-05 13:37 GMT+01:00 Pedro M. Baeza notifications@github.com:

> OK, so can I close this PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/partner-contact/pull/58#issuecomment-65784392.

## 

_César Andrés PhD Computer Science brain-tec AG | Überlandstrasse 10,
CH-3900 Brig Tel: +41 27 552 02 20 | Dir: +41 27 552 02 11_
http://www.brain-tec.ch/   cesar-andres.sanchez@brain-tec.ch
http://www.brain-tec.ch/

**Pull request closed without merging**
