### PR TITLE
[FIX][10.0] base_location :  "better_zip_ids" field set colspan="2" in state view

### PR DESCRIPTION
**Pull request by kitcharoenp**
for proper view in form
in `state_view.xml` change `colspan="4"` to `colspan="2"`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you put snapshots of the before and after?

**Comment by kitcharoenp** [comment]
Before
screenshot from 2017-01-11 09-57-26

After

screenshot from 2017-01-11 09-59-09

**Review by pedrobaeza — APPROVED** [review]
Please sign CLA if not yet

**Review by petrus-v — APPROVED** [review]
:+1: Thanks for that!

**Pull request merged**
