### PR TITLE
[MIG] partner_tz: Migration to 14.0

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
LG but please squash commits (I know you are preserving them but they got merged like this by error very likely). Thanks!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by dzungtran89** [comment]
hi @simahawk , I think you meant about squashing the fixup commits, could you please have a look on the updates?

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@dzungtran89 yes, thanks!

/ocabot merge nobump

**Pull request merged**
