### PR TITLE
[16.0][IMP] partner_manual_rank: Set default value based on res_partner_search_mode context

### PR DESCRIPTION
**Pull request by amarcosg**
Port to 16.0 of 14.0 PR https://github.com/OCA/partner-contact/pull/1533 

- [ ] https://github.com/OCA/partner-contact/pull/1533
- [ ] https://github.com/OCA/partner-contact/pull/1535

### CODE REVIEW

**Comment by luisg123v** [comment]
Let's wait for #1533 first to be merged, as that one has comments.

**Comment by rafaelbn** [comment]
Thank you! please review previous PR first! Thank you! ❤️

**Review by ypapouin — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
It seems a rebase is needed to greenify runboat.

**Review by luisg123v — APPROVED** [review]
/ocabot rebase

**Comment by luisg123v** [comment]
/ocabot merge patch

It will be rebased anyway when merging.

**Pull request merged**
