### PR TITLE
[MIG] crm_deduplicate_filter > partner_deduplicate_filter: Migration to 12.0

### PR DESCRIPTION
**Pull request by victor-ditay**
Depends on:

- [x] #721 - crm_deduplicate_acl

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Something has gone bad with the git filter-branch / rebase / am operation. Check the number of commits and files.

**Comment by victor-ditay** [comment]
Commit history fixed @pedrobaeza

**Comment by pedrobaeza** [comment]
You can rebase this one

**Comment by pedrobaeza** [comment]
You have done `pull` instead of `rebase`. Please check.

**Comment by victor-ditay** [comment]
I closed by mistake this one, not sure if possible to reopen but on the meanwhile I opened new one with same name #726

**Pull request closed without merging**
