### PR TITLE
[MIG][10.0] Migration of partner_contact_nationality

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by JonathanNEMRY — APPROVED** [review]
code review :+1

**Review by andhit-r — APPROVED** [review]
Tested functionality on runbot :+1:

**Comment by tafaRU** [comment]
@rousseldenis, thanks for the migration!
Could you please avoid conflicting files? Note that README.md will be updated automatically so it doesn't need to be changed.

Thank you in advance.

**Comment by dreispt** [comment]
Ping @rousseldenis

**Comment by rousseldenis** [comment]
@dreispt Done!

**Review by chienandalu — APPROVED** [review]

**Review by aming27 — COMMENTED** [review]
it's fine.

**Review by rafaelbn — APPROVED** [review]
Tested in runbot 👍

**Pull request merged**
