### PR TITLE
[17.0][MIG] partner_email_duplicate_warn: Migration to 17.0

### PR DESCRIPTION
**Pull request by V3st1g3**

### CODE REVIEW

**Review by gurneyalex — CHANGES_REQUESTED** [review]
Please redo the migration preserving the history of the module. You can find the detailed process in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Review by vvrossem — CHANGES_REQUESTED** [review]
Thank you for this PR :pray: 
Could you please 

1. Squash administrative commits with the previous commit for reducing commit noise. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.
2. Ensure to run pre-commit **before** in a separate commit before adapting the module to the 17.0 version (cf. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch)

:bow:

**Review by yankinmax — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
