### PR TITLE
[10.0] store field risk_exception

### PR DESCRIPTION
**Pull request by pedrocs-exo**
This way we can use the field in filters and quickly determine which partners are over their limits

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@carlosdauden any reason for not being stored?

**Comment by carlosdauden** [comment]
If store a compute hook is required when we install other related modules that extends this depends:
https://github.com/OCA/partner-contact/blob/4814218807e3ccc59378db7a46976f6362b711b2/partner_financial_risk/models/res_partner.py#L210

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Thanks for the clarification, Carlos.

Pedro, you should add these hooks (in post-init-hook for example) for this to be valid. And then we will have a problem of performance while installing the modules...

**Comment by NL66278** [comment]
PR seems to be abandoned by the developer.

**Pull request closed without merging**
