### PR TITLE
[17.0][MIG] animal: Migration to 17.0

### PR DESCRIPTION
**Pull request by santiagordz**

### CODE REVIEW

**Comment by santiagordz** [comment]
@max3903 can you check this?

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@santiagordz The default picture is not loaded when creating a new record...
http://oca-partner-contact-17-0-pr1787-298962bf9bc9.runboat.odoo-community.org/web#action=155&model=animal&view_type=kanban&cids=1&menu_id=110

It should default to animal/static/img/avatar.png

**Review by max3903 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@santiagordz Could you be a little bit more explicit in your commit message ? Thanks

image

**Review by bealdav — APPROVED** [review]

**Pull request closed without merging**
