### PR TITLE
Added portuguese translation files po

### PR DESCRIPTION
**Pull request by danimaribeiro**
I've requested a new idiom on transifex:
https://www.transifex.com/projects/p/OCA-partner-contact-8-0/
But I'm not sure if I should add the .po files here first to translate later, so in any case I'm sending this PR to add those files.

### CODE REVIEW

**Comment by danimaribeiro** [comment]
Brazilian Portuguese translated on transifex.
https://www.transifex.com/projects/p/OCA-partner-contact-8-0/language/pt_BR/

**Comment by gurneyalex** [comment]
@pedrobaeza not sure how transifex works for this. Do you have an idea what is needed here?

**Comment by danimaribeiro** [comment]
I think we can close this, I translated in Transifex, and the translations are ok.

**Comment by pedrobaeza** [comment]
Exactly, this is not needed, as an script push back the translations from Transifex periodically.

**Pull request closed without merging**
