### PR TITLE
[14.0][FIX] partner_pricelist_search: speedup search + Remove list type also from search arguments

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 13.0:
- https://github.com/OCA/partner-contact/pull/1351
- https://github.com/OCA/partner-contact/pull/1383

Please @chienandalu and @sergio-teruel can you review it?

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
