### PR TITLE
[10.0][MIG] partner_default_sale_discount: migrate to 10.0

### PR DESCRIPTION
**Pull request by lbelorgey**
Migrate the module "partner_default_sale_discount" from v9 to v10 (not yet in v10 branch because added after).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by lbelorgey** [comment]
Done!

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
