### PR TITLE
[14.0][FIX] partner_tier_validation: create does not need custom code, restart validation on controlled field changes

### PR DESCRIPTION
**Pull request by dreispt**
- [FIX] partner_tier_validation: create does not need custom code, restart validation on controlled field changes

### CODE REVIEW

**Comment by rafaelbn** [comment]
@Freni-OSI could you please review here? Thank you!

**Review by patrickrwilson — CHANGES_REQUESTED** [review]
Tested and works, can you fix that test that travis is complaining about?

**Review by patrickrwilson — CHANGES_REQUESTED** [review]
--- Removed incorrect comment

**Comment by dreispt** [comment]
@patrickrwilson This module does not add a "Can be Sold" field.
Perhaps that comment was for https://github.com/OCA/sale-workflow/pull/1932 ?

**Comment by patrickrwilson** [comment]
> @patrickrwilson This module does not add a "Can be Sold" field. Perhaps that comment was for [OCA/sale-workflow#1932](https://github.com/OCA/sale-workflow/pull/1932) ? Yes, sorry, I removed my comment and will redo my review.

**Review by patrickrwilson — CHANGES_REQUESTED** [review]
Tested and works, can you fix that test that travis is complaining about?

**Comment by dreispt** [comment]
Added a commit fixing the tests, and fixing a bug found while doing that.

**Review by patrickrwilson — APPROVED** [review]
Tested in runboat and works. LGTM

**Pull request merged**
