### PR TITLE
[FIX] pass load in load override

### LINKED ISSUE #154: [8.0] partner_relations - Error when deleting a res.partner
Tested in OCA's runbot
https://runbot.odoo-community.org/runbot/repo/github-com-oca-partner-contact-134
- Create a partner
- Don't select "is a company"
- Filled "firstname" and "lastname"
- Save partner
- Delete the partner we have created
- You get this error:

> AccessError
> No value found for res.partner(75,).birthdate_date

I have tested in Odoo's runbot and you can delete any res.partner if it hasn't any other relation with other objects.

Maybe this bug it not from this module partner_contact_birthdate

@pedrobaeza I think that any module in this project must at least pass test of creating, modifying and deleting a res.partner, if not shouldn't be merged.

cc @sysadminmatmoz @Yajo

### PR DESCRIPTION
**Pull request by hbrunn**
fixes #154

### CODE REVIEW

**Comment by pedrobaeza** [comment]
So this little argument is the origin of all the evil... let's fix it!

:+1:

**Comment by pedrobaeza** [comment]
@hbrunn, another thing you have to fixed as mention by @Yajo is the depends section of the module. You must depend at least from base.

**Comment by hbrunn** [comment]
@pedrobaeza elaborate please. The base dependency is implicit nowadays, isn't it?

**Comment by pedrobaeza** [comment]
No, it isn't, please see rationale here: https://github.com/OCA/maintainer-tools/pull/91#issuecomment-138841544

**Comment by hbrunn** [comment]
@pedrobaeza weird, what is described there shouldn't happend. Anyways: #173

**Comment by guewen** [comment]
:+1:

**Comment by yajo** [comment]
Sad to say, but this fix does not pass tests in #154.

**Comment by hbrunn** [comment]
well, it's not merged yet, so of course ci tests still fail in #154

**Comment by yajo** [comment]
I mean after merging this on top of #154. I'm going to try now on an empty DB, let's see.

**Comment by yajo** [comment]
Sorry, I meant #170.

**Comment by yajo** [comment]
Empty DB. Tests in #170 fail, manual tests too. Definitely not working, sorry.

**Comment by antespi** [comment]
:+1: Anyway this fix is neccesary, because it is needed in https://github.com/OCA/partner-contact/blob/8.0/partner_relations/model/res_partner_relation.py#L356

**Comment by pedrobaeza** [comment]
I merge this one and we can continue seeing unlink test in its issue/another PR

**Pull request merged**
