### PR TITLE
[14.0][MIG] partner_priority: Migration to 14.0

### PR DESCRIPTION
**Pull request by newtratip**
I removed priority sequence data. This is not neccessary to have it.

Reference: https://github.com/OCA/partner-contact/pull/870#discussion_r399216282

Ready for review.

cc: @NL66278 @patrickrwilson

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by HaraldPanten — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by flotho — APPROVED** [review]
LGTM
code review

**Comment by newtratip** [comment]
@NL66278, OCA Bot notify merge failed. Am I do something wrong ?

**Comment by NL66278** [comment]
@newtratip I think there was some hiccup in the merge process. I will just try to merge again.

**Pull request merged**
