### PR TITLE
[8.0][partner_contact_job_position] Add new module to categorize job positions in contacts

### PR DESCRIPTION
**Pull request by yajo**
Add a field for almost the same as the `function` field of `res.partner`, but allowing categorizations in tree form; without replacing `function`, so it remains usable as a kind of detailed/uncategorized job position.

@rafaelbn @JavierIniesta.

### CODE REVIEW

**Comment by elicoidal** [comment]
LGTM

**Comment by yajo** [comment]
Runbot is broken with https://github.com/odoo/odoo/issues/10159, not my fault.

**Comment by rafaelbn** [comment]
Tested in local :+1: 

Please review @JavierIniesta , thanks!

**Comment by JavierIniesta** [comment]
Tested in runbot :+1:

**Comment by JMODaERP** [comment]
I´ve tested in runbot :+1:

**Pull request merged**
