### PR TITLE
[12.0][MIG] partner_contact_gender: Migration to 12.0

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Review by alfredoavanzosc — APPROVED** [review]
:+1:

**Comment by oihane** [comment]
@Yajo @hbrunn @mvrodriguez can anyone please review?

**Review by hbrunn — APPROVED** [review]
@oihane nagging me for reviews is a certain way to get on my ignore list, don't do this again

**Comment by pedrobaeza** [comment]
@oihane you can review a couple of @hbrunn's PRs in exchange :wink:

**Pull request merged**
