### PR TITLE
[15.0] partner_multi_relation: Porting PR #1068 to 15.0

### PR DESCRIPTION
**Pull request by JonathanStein**
Forward porting "Check reverse overlapping symmetric relations" from 12.0 to 15.0

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by dreispt** [comment]
Looks like #1210 also did this migration and was merged.

**Comment by JonathanStein** [comment]
PR #1068 was made on 12.0 but never forward ported to 13.0 (or 14.0), so it wasn't included in PR #1210 (the migration from 14.0 to 15.0).

**Comment by JonathanStein** [comment]
I think this PR is still relevant. Can I do more?

**Pull request merged**
