### PR TITLE
[FIX] disable create position on contact

### LINKED ISSUE #573: odoo 11  Contacts in several partners
i just to install the module, but dont work

i go to the new tab into contact module (aplication) / create

AND........

Error:
Uncaught Error: Unknown field parent_id in domain

http://192.168.10.207:8069/web/static/src/js/core/domain.js:67
Rastreo de error:
Error: Unknown field parent_id in domain
    at Class.compute (http://192.168.10.207:8069/web/static/src/js/core/domain.js:67:23)
    at http://192.168.10.207:8069/web/static/src/js/core/domain.js:118:38
    at Function._.every._.all (http://192.168.10.207:8069/web/static/lib/underscore/underscore.js:237:12)
    at Class.compute (http://192.168.10.207:8069/web/static/src/js/core/domain.js:117:30)
    at evalModifier (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:1881:49)
    at Class._evalModifiers (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:1890:31)
    at Class._isFieldProtected (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:3084:34)
    at Class._generateChanges (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:2656:26)
    at http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:973:32
    at Object.<anonymous> (http://192.168.10.207:8069/web/static/src/js/core/concurrency.js:216:31)

i ´ve tried in runbot and the same

Error:
Uncaught Error: Unknown field parent_id in domain

http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:293
Traceback:
Error: Unknown field parent_id in domain
    at Class.compute (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:293:55)
    at http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:295:830
    at Function._.every._.all (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/476-980108a/web.assets_common.js:19:571)
    at Class.compute (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:295:780)
    at evalModifier (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1180:91)
    at Class._evalModifiers (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1183:44)
    at Class._isFieldProtected (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1238:237)
    at Class._generateChanges (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1206:358)
    at http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1133:18
    at Object.<anonymous> (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/476-980108a/web.assets_common.js:4009:295)

?????????????????????????

### PR DESCRIPTION
**Pull request by njeudy**
- This is just to see all positions
- If we want to add position go to one company and add contact linked to this partner

Issues:

- fixes #573

### CODE REVIEW

**Comment by njeudy** [comment]
@pedrobaeza @cesarsc79 I can work on a new wizard to add new position from contact directlly but that was not the case (you can not even select company in the form .. )

Think It is necessary to add a new wizard in this case to check if the new position does not exist, and to select company associated with new position .. new position is always in a new company

what do you think ?

@cesarsc79 is it ok for you ?

**Comment by cesarsc79** [comment]
@njeudy

that would be great!!!

**Comment by njeudy** [comment]
@cesarsc79 @pedrobaeza ok think we need to merge this one, and create a new issue to discuss about adding new wizard ? 

I can work on it middle of the next week i think.

**Comment by cesarsc79** [comment]
@njeudy 

I think that the opinion of others can enrich us, but from my point of view, you have been very successful in the solution ...
I think it is not necessary to a new issue

@pedrobaeza   what do you think about it?

**Comment by njeudy** [comment]
@pedrobaeza @cesarsc79 can we merge this and add add an issue to enable position creation from contact later ? I don't know if we could achieve this because we have to create a clean wizard for this ..

**Comment by pedrobaeza** [comment]
OK, I merge this for fixing the issue.

**Pull request merged**
