### PR TITLE
[9.0][MIG][WIP] partner_contact_birthdate + partner_contact_personal_information_page + passport migration to v9

### PR DESCRIPTION
**Pull request by jt-xx**

### CODE REVIEW

**Comment by kkarolis** [comment]
Hey,

Just some points which IMO could be improved with this PR.
- Wait for migration of `partner_contact_information_page`
- Change the title to a more informative one like _[9.0][MIG] partner_contact_birthdate: Port to v9.0._ or similar
- Couldn't comment on lines not changed but version should be bumped to 9.0.
- Add this module to a list of available addons

**Comment by gurneyalex** [comment]
:+1: 

@kkarolis can you rebase your PR?

**Comment by kkarolis** [comment]
@gurneyalex , this is not my PR, although I rebased mine at #215 anyways.

**Comment by gurneyalex** [comment]
@jt-xx can you rebase your PR please?

**Comment by jt-xx** [comment]
@gurneyalex I just rebased, I hope it's correct, I'm not used to this git verbosity yet

**Comment by yvaucher** [comment]
Don't forget to update the issue #184

**Comment by yvaucher** [comment]
Updated #184 

:-1: 

https://github.com/OCA/partner-contact/pull/193 is already there to port partner_contact_personal_information_page

**Comment by yvaucher** [comment]
@jt-xx please don't do commits with [WIP] in it

**Comment by yvaucher** [comment]
As partner_contact_birthdate needs a bit more work, this will be done in @leemannd in #243 

@jt-xx Could you change this PR or create a new one to do the port of `passport` only ?

**Comment by leemannd** [comment]
@jt-xx @pedrobaeza Is passport still beeing ported?
Or can we close this PR?

**Comment by leemannd** [comment]
@jt-xx @pedrobaeza Is passport still going to be ported or can we close this PR?

**Comment by pedrobaeza** [comment]
Having https://github.com/OCA/partner-contact/tree/9.0/partner_identification, I don't think so.

**Pull request closed without merging**
