### PR TITLE
6.1 meta

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by bwrsandman** [comment]
```
2014-07-19 01:04:39,496 19282 INFO openerp_test openerp.modules.module: module partner_address_ldap: creating or updating database tables

2014-07-19 01:04:39,548 19282 WARNING openerp_test openerp.loglevels: The netsvc.Logger API shouldn't be used anymore, please use the standard `logging.getLogger` API instead.

2014-07-19 01:04:39,548 19282 WARNING openerp_test openerp.loglevels: notifyChannel API shouldn't be used anymore, please use the standard `logging` module instead.

2014-07-19 01:04:39,548 19282 INFO openerp_test openerp.loglevels.deprecated.LDAP address init: try to ALTER TABLE res_partner_address RENAME column name to lastname ;

2014-07-19 01:04:39,549 19282 ERROR openerp_test openerp.sql_db: Programming error: column "lastname" of relation "res_partner_address" already exists

, in query ALTER TABLE res_partner_address RENAME column name to lastname ;
```

**Comment by pedrobaeza** [comment]
Thanks

:+1: (code review)

**Comment by bwrsandman** [comment]
[`base_partner_surname`](https://github.com/OCA/partner-contact/blob/6.1/base_partner_surname/partner.py#L29) and [`partner_address_ldap`](https://github.com/OCA/partner-contact/blob/6.1/partner_address_ldap/address.py#L166) are conflicting: they both want to add last name to 'res.partner.address'.

I think that field should be added in `base_partner_surname` and if `partner_address_ldap` wants to use it, make it depend on `base_partner_surname`

Anyone have thoughts about it?

**Comment by pedrobaeza** [comment]
Yeah, I also think `partner_address_ldap` must be dependant on `base_partner_surname`.

Regards.

**Pull request merged**
