### PR TITLE
Fix street3 hook override.

### PR DESCRIPTION
**Pull request by nbessi**
Street3 is not part of commercial fields

### CODE REVIEW

**Comment by nbessi** [comment]
fixes #46

**Comment by lepistone** [comment]
thanks :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by nbessi** [comment]
Ah it seems the addons should be tested aside as it interfer with partner first name

**Comment by alexis-via** [comment]
:+1:  Thanks for the fix Nicolas.

**Comment by yvaucher** [comment]
Travis fails on tests of partner_firstname

**Comment by alexis-via** [comment]
I don't understand what is blocking this merge. If travis fails in partner_firstname, it's a problem that needs to be fixed in partner_firstname, but it's not linked to this bug fix.

**Comment by pedrobaeza** [comment]
I can confirm that the failing test is not for this change, so I merge.

**Comment by alexis-via** [comment]
@pedrobaeza Thank you Pedro !

**Pull request merged**
