### PR TITLE
[16.0][MIG] partner helper + rename it partner_address_split

### PR DESCRIPTION
**Pull request by florian-dacosta**
@bealdav @rousseldenis Better late than never, I made the changes we talked about here : https://github.com/OCA/partner-contact/pull/1412
So, rename the module + add tests to improve coverage.

Finally, I have decided making a new PR because I want to keep the `partner_helper` original migration branch because this module is already used in production. and need to be kept until a clean transition is made.  I'll close this old PR though.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by bealdav — APPROVED** [review]
LGTM

Thanks a lot

**Pull request merged**
