### PR TITLE
[BACKPORT][8.0] partner_sale_risk

### PR DESCRIPTION
**Pull request by andhit-r**

### CODE REVIEW

**Review by rafaelbn — DISMISSED** [review]
tested in runbot 👍

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Hi @andhit-r , testing again this module I'm not able to set a credit limit:

- Create a new partner
- Save
- Edit
- Go to financial risk -> set credit limit -> save
- It doesn't change, limit still 0

Please take a look

Thanks

**Comment by andhit-r** [comment]
Hi @rafaelbn thanks for your review. It seems that **credit_limit** field appear twice on partner form. One field added by original **account** module and other by **partner_financial_risk** module. I will remove field form original **account** module since we want to move it to new tab. 

Can i put the revision in this PR or should i open new PR?

Many thanks.

**Comment by rafaelbn** [comment]
Same PR better

**Comment by rafaelbn** [comment]
@andhit-r , this PR better to view all history

**Comment by Daniel-CA** [comment]
Hi @andhit-r,
Could you do the change in this PR? Thanks.

**Comment by andhit-r** [comment]
@Daniel-CA thanks for your rev. I will rebase it when #449 is merge.

**Comment by Daniel-CA** [comment]
@rafaelbn Could you review the PR and check if all is ok, thanks!

**Comment by rafaelbn** [comment]
Hi @anajuaristi , please could you test this PR and tell us if it is working? Thanks!

**Review by rafaelbn — APPROVED** [review]

**Comment by anajuaristi** [comment]
:+1:

**Pull request merged**
