### PR TITLE
[FIX] [14.0] Removed external dependencies already defined in Odoo base

### PR DESCRIPTION
**Pull request by Shide**
Removed external dependencies already defined in Odoo base

https://github.com/odoo/odoo/blob/ae6f414ba41eee4e14235a1e82fd5ebd237dd97f/requirements.txt#L48

MT-282 @moduon

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by yajo — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This should be removed instead, as it's part of standard Odoo requirements:

https://github.com/odoo/odoo/blob/ae6f414ba41eee4e14235a1e82fd5ebd237dd97f/requirements.txt#L48

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
