### PR TITLE
Add partner-address-street3 

### PR DESCRIPTION
**Pull request by nbessi**
Add simple module that adds street3 in adresses and respect the use of parent address

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check pylint errors:

```
************* Module partner-contact.base_partner_merge.base_partner_merge
base_partner_merge/base_partner_merge.py:29: [W0102(dangerous-default-value), html_entity_decode_char] Dangerous default value htmlentitydefs.entitydefs ({}) as argument
************* Module partner-contact.passport.tests.test_passport
passport/tests/test_passport.py:36: [W0102(dangerous-default-value), Base_Test_passport.setUp] Dangerous default value {} as argument
```

But the rest LGTM.

**Comment by nbessi** [comment]
Ok I'll fix it even it is out of the PR.
We may froze the maintainer tools branch on the project.

**Comment by nbessi** [comment]
Correction applied

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by tafaRU** [comment]
Please use CamelCase naming for classes as already done in test_street_3. Thank you in advance.
The rest LGTM.

**Comment by nbessi** [comment]
AFAIK @tafaRU I do not think there was an official decision about CamelCasing of model derived class.

I try to stick as close as possible as original class name. If I had put the class in camel case some one would have asked me to lower it. 

That is a highly volatile with an elevated troll indice topic, so please let's not lose time on this.

Nicolas

**Comment by tafaRU** [comment]
Thanks for your explanation so :+1:

**Pull request merged**
