### PR TITLE
[ADD] partner_relations_in_tab

### PR DESCRIPTION
**Pull request by hbrunn**
This is an extension module for partner_relations from #15 - tests will fail until this one pulled.

### CODE REVIEW

**Comment by max3903** [comment]
Can you provide the pot file ?

:-1:

**Comment by hbrunn** [comment]
@max3903 thank for your hint, I forgot about all the translations

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
POT file issue is solved, so I merge.

**Pull request merged**
