### PR TITLE
[FIX] allow to change partner_id_display

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
I added a commit that also fixes a logic error

**Comment by guewen** [comment]
:+1:

**Comment by hbrunn** [comment]
and I added another commit that allows searching for translated relation names (res.partner.relation.type selection is a view on res.partner.relation.type, so we don't get openerp's translation mechanism on that model)

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
