### PR TITLE
[15.0][MIG] partner_address_street3

### PR DESCRIPTION
**Pull request by jcdrubay**

### CODE REVIEW

**Comment by Rad0van** [comment]
@jcdrubay you should probably squash the last 3 commits.

**Review by Rad0van — APPROVED** [review]
LGTM. Tested. Just squash the commits.

**Comment by jcdrubay** [comment]
@Rad0van Squash is done. 

@rousseldenis  Are we missing anything to merge?

Thanks

**Review by xhnilic3 — APPROVED** [review]
Tested.

**Comment by Sparad0x** [comment]
Is it good to merge now? Is there anything still blocking?

**Comment by Sparad0x** [comment]
Hello,
Any news about migration to v15?

**Review by theangryangel — APPROVED** [review]
Functionally tested.

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Pull request merged**
