### PR TITLE
[15.0][IMP] partner_manual_rank: Set default value based on res_partner_search_mode context

### PR DESCRIPTION
**Pull request by amarcosg**
Port to 15.0 of 14.0 PR https://github.com/OCA/partner-contact/pull/1533

- [ ] https://github.com/OCA/partner-contact/pull/1533

### CODE REVIEW

**Comment by luisg123v** [comment]
Let's wayt for #1533 to be merged first, as that one has comments.

**Comment by rafaelbn** [comment]
Travis 🔴 , previous PR 🔴 waiting to fix the first one and have all 🍏

**Review by ypapouin — APPROVED** [review]
Please rebase

**Review by luisg123v — APPROVED** [review]

**Comment by luisg123v** [comment]
/ocabot merge patch

It will be rebased anyway when merging.

**Pull request merged**
