### PR TITLE
[10.0][FIX]: Requirement email_validator >= 1.3 fail in partner_email_check

### PR DESCRIPTION
**Pull request by igallart**
https://github.com/OCA/partner-contact/issues/1358

### CODE REVIEW

**Comment by igallart** [comment]
@pedrobaeza , sorry for always coming to you, but I have no idea who manages this. Is there any way to know who is responsible for each repository?

**Comment by rousseldenis** [comment]
> @pedrobaeza , sorry for always coming to you, but I have no idea who manages this. Is there any way to know who is responsible for each repository?

@igallart You can look there https://odoo-community.org/psc-teams

**Comment by igallart** [comment]
Thanks @rousseldenis, I don't know. So, you are a member here, how can this commit move forward? Travis is broken.

**Comment by igallart** [comment]
Closed due to inactivity.

**Pull request closed without merging**
