### PR TITLE
[ADD] partner_purchase_manager

### PR DESCRIPTION
**Pull request by EmilioPascual**
Add purchase manager in partner model.

@rafaelbn @yajo @Shide review plz.

MT-4252 @moduon

https://www.loom.com/share/dcfd9ae7b7b7468e999afe36b81f96ad

### CODE REVIEW

**Review by Shide — APPROVED** [review]
LGTM

**Comment by rafaelbn** [comment]
Hello @yajo @sbidoul do you know is something is wrong with CI or runboat? Thank you very much 😄

**Comment by EmilioPascual** [comment]
CI is already ok

**Review by Gelojr — APPROVED** [review]
LGTM
It is also possible to change the purchasing manager in batches.
https://www.loom.com/share/39a46bea25ad45cb9924654c835f789d?sid=7f44b193-7034-47b5-9ba2-3c4e271ae83a

**Review by rafaelbn — APPROVED** [review]
Tested in runbot 👍🏼 

/ocabot merge patch

**Pull request merged**
