### PR TITLE
[17.0][MIG] partner_contact_personal_information_page: Migration to version 17.0

### PR DESCRIPTION
**Pull request by Daemo00**

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]
Test in runboat, Ok.

**Review by AntoniRomera — APPROVED** [review]
LGTM
Code Review OK

**Comment by pedrobaeza** [comment]
Please put the pre-commit auto fixes commit (before the migration one), and you can put it as maintainer in the same commit as the migration.

**Comment by Daemo00** [comment]
Thanks everyone for having a look!

> Please put the pre-commit auto fixes commit (before the migration one), and you can put it as maintainer in the same commit as the migration.

There is already a commit (https://github.com/OCA/partner-contact/pull/1608/commits/2e732bcac150066b87a78dcf8a02b70b3fb4e76b) dedicated to pre-commit auto fixes before the migration commit, but maybe I have misunderstood what you are suggesting.
I have squashed the migration and adoption commits.

Let me know if anything else is needed.

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
