### PR TITLE
[17.0][MIG] partner_identification_gln: Migration to 17.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
Standard migration to 17.0

### CODE REVIEW

**Comment by NICO-SOLUTIONS** [comment]
Depends on:

- [x] https://github.com/OCA/partner-contact/pull/1622

**Review by gurneyalex — APPROVED** [review]

**Review by Deriman-Alonso — APPROVED** [review]
LGTM👍

**Review by rousseldenis — APPROVED** [review]
Code review.

Great that this is still migrated ! Thanks

**Comment by NICO-SOLUTIONS** [comment]
@rousseldenis thx 🙏

**Pull request merged**
