### PR TITLE
[16.0][MIG] partner_contact_type_end_user

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `partner_contact_type_end_user`
Based on https://github.com/OCA/partner-contact/pull/1202

### CODE REVIEW

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Comment by acsonefho** [comment]
@rousseldenis A little review and a big merge please? If you have super-power here :muscle:

**Comment by rousseldenis** [comment]
@acsonefho For the next time, run pre-commit before migrating to put pre-commit stuff in its own commit

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

**Review by rousseldenis — APPROVED** [review]
Tested functionaly

**Review by leemannd — APPROVED** [review]

**Pull request merged**
