### PR TITLE
[10.0][FIX] Prevent flake8 error for non-critical bare except.

### PR DESCRIPTION
**Pull request by NL66278**
I am getting Travis errors on flake8 because of a bare except in the base_location_nuts module. The bare except in this particulare case should not be any problem. Added just a #noqa comment to ignore it.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can't we be more specific about the exception? Maybe it's `ValueError`

**Comment by Yajo** [comment]
Usually it's a TypeError:

```

**Comment by yajo** [comment]
Oops, butterfingers... Yep, I agree with @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this

**Pull request merged**
