### PR TITLE
[15.0][MIG] partner_contact_address_default

### PR DESCRIPTION
**Pull request by dhx**
Apparently works without changes

### CODE REVIEW

**Review by cesar-tecnativa — CHANGES_REQUESTED** [review]
Please run pre-commit command and add the first commit as [IMP] partner_contact_address_default: black, isort, prettier

**Comment by dhx** [comment]
> Please run pre-commit command and add the first commit as [IMP] partner_contact_address_default: black, isort, prettier

alright, @cesar-tecnativa thanks for the review

**Review by cesar-tecnativa — APPROVED** [review]

**Pull request merged**
