### PR TITLE
[15.0][MIG] partner_deduplicate_filter: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT37296

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please waiting for https://github.com/OCA/partner-contact/pull/1298

**Comment by cesar-tecnativa** [comment]
@pedrobaeza could you please review?

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review.

**Review by CarlosRoca13 — APPROVED** [review]
Code and functional review :+1:

**Comment by cesar-tecnativa** [comment]
@LudLaf please review

**Comment by LudLaf** [comment]
> 

Is it normal for the wizard "Deduplicate Contacts" to be automatically launched by just clicking on "Contacts"?

**Comment by pedrobaeza** [comment]
No, it isn't

**Comment by pedrobaeza** [comment]
@cesar-tecnativa maybe the change you did for the order of the menus?

**Comment by cesar-tecnativa** [comment]
> 
It is done here https://github.com/OCA/partner-contact/pull/1310

**Comment by cesar-tecnativa** [comment]
@LudLaf please review

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
