### PR TITLE
[18.0][MIG] partner_fax: Migration to 18.0

### PR DESCRIPTION
**Pull request by intero-als**

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Review by Sanazzzmi — APPROVED** [review]

**Comment by Sanazzzmi** [comment]
@pedrobaeza @OCA-git-bot @leemannd 
Hello. Could you please assist with migrating this module? I would greatly appreciate your help.

Thank you!

**Comment by mostafabarmshory** [comment]
@OCA-git-bot  @pedrobaeza @rousseldenis @ leemannd 

Hello. I need this module. Please merge it for version 18 as soon as possible. Thanks

**Comment by alexis-via** [comment]
FYI, I had this interesting PR to add fax number reformatting to the partner_fax module, just like for the fields "phone" and "mobile":
https://github.com/OCA/partner-contact/pull/1763

**Pull request merged**
