### PR TITLE
Danish translation of base_location

### PR DESCRIPTION
**Pull request by hhgabelgaard**

### CODE REVIEW

**Comment by yvaucher** [comment]
Thanks for your contribution

Technically :+1:

**Comment by hhgabelgaard** [comment]
Signed CLA submitted to cla AT odoo-community.org.

**Comment by bwrsandman** [comment]
I see you suggested the language on Transifex, we could either do this through pull request or through rights granting on Transifex.

We first need to setup the teams and define Coordinators for each language.

**Comment by bwrsandman** [comment]
Technically, the PR is :+1:

**Comment by tafaRU** [comment]
Technically :+1:

**Comment by hhgabelgaard** [comment]
I will be happy to join the Danish team

**Pull request merged**
