### PR TITLE
[17.0][MIG] base_location_nuts: Migration to 17.0

### PR DESCRIPTION
**Pull request by salvorapi**

### CODE REVIEW

**Review by TheMule71 — APPROVED** [review]
LGTM

**Review by Deriman-Alonso — APPROVED** [review]
LGTM 👍, code review.

**Comment by FernandoRomera** [comment]
@salvorapi Can you include this pr https://github.com/OCA/partner-contact/pull/1815

**Comment by salvorapi** [comment]
> @salvorapi Can you include this pr #1815

Sure! There is some specific procedure to include PR or just merge the commit from #1815 ?

**Comment by FernandoRomera** [comment]
@salvorapi just merge the commit.

**Review by FernandoRomera — APPROVED** [review]
LGTM.

**Comment by FernandoRomera** [comment]
Hi @rafaelbn, @edlopen,
Can you merge this PR.

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@salvorapi Please, check failures. You have other binary files added by mistake in this PR.

THX.

**Comment by salvorapi** [comment]
> @salvorapi Please, check failures. You have other binary files added by mistake in this PR.
> 
> THX.

done. I hope now it's ok. :)

**Comment by FernandoRomera** [comment]
@HaraldPanten Can you check and merge if all Ok?

**Comment by HaraldPanten** [comment]
> @HaraldPanten Can you check and merge if all Ok?

I still see the binary files:

Captura de Pantalla 2024-07-23 a las 10 08 26

**Comment by FernandoRomera** [comment]
@salvorapi 
can you meet @HaraldPanten requests?

**Comment by salvorapi** [comment]
> @salvorapi can you meet @HaraldPanten requests?

@FernandoRomera sorry, but I didn't understand. These files are just removed (see the minus icon) from the commit.

@HaraldPanten do you ask me to adds it again ?

Salvo.

**Pull request merged**
