### PR TITLE
[13.0][MIG] partner_create_by_vat

### PR DESCRIPTION
**Pull request by NL66278**
Migration done by @feketemihai. Just squashed the translation commits.

### CODE REVIEW

**Review by feketemihai — APPROVED** [review]

**Comment by feketemihai** [comment]
@NL66278 I think you can also add yourself to Contributors section. Thanks.

**Comment by dreispt** [comment]
Build failed because of base_location_geonames_import`.
Attempted to fix it with #1140

**Comment by pedrobaeza** [comment]
Explanation put on https://github.com/OCA/partner-contact/pull/1140#issuecomment-927285458

**Comment by pedrobaeza** [comment]
Geonames is up again, so

/ocabot merge nobump

**Pull request merged**
