### PR TITLE
[15.0] [MIG] partner_identification and partner_identification_gln

### PR DESCRIPTION
**Pull request by njeudy**
Here is my contribution to migration process of:

- partner_identification
- partner_identification_gln

to v15.0

### CODE REVIEW

**Comment by njeudy** [comment]
@sbidoul can you check this one ?

**Comment by njeudy** [comment]
I just see that some works have been done before but when I searched PR with "is:pr is:open identifi" nothing appear.

And I check manualy, and find: 

- https://github.com/OCA/partner-contact/pull/1436
- https://github.com/OCA/partner-contact/pull/1270

**Comment by rousseldenis** [comment]
> I just see that some works have been done before but when I searched PR with "is:pr is:open identifi" nothing appear.
> 
> And I check manualy, and find:
> 
> * [[MIG] partner_identification: Migration to 15.0 #1436](https://github.com/OCA/partner-contact/pull/1436)
> * [[15.0][MIG] partner_identification #1270](https://github.com/OCA/partner-contact/pull/1270)

@njeudy Do you mind we keep https://github.com/OCA/partner-contact/pull/1436 as that one is not so old ?

**Comment by njeudy** [comment]
I can separate the two modules and validate the #1436 , just keep partner_identification_gln here

**Pull request closed without merging**
