### PR TITLE
[13.0] Fix partner_company_group filter priority

### PR DESCRIPTION
**Pull request by guewen**
Search on company group shouldn't overwrite the default invoice number search
Port of #773

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
Apparently there's an issue with geonames.org : http://download.geonames.org/export/zip/ doesn't feature all the expected files. I suggest to wait for a couple of days.

**Comment by pedrobaeza** [comment]
Yeah, not sure why Geonames is having such problems lately with the exported data files...

**Review by rafaelbn — APPROVED** [review]
:+1:

**Pull request merged**
