### PR TITLE
11.0 mig partner contact personal information page

### PR DESCRIPTION
**Pull request by jprobineau**

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
Please squash all translation commits, including 41f30d9 

The rest seems OK

**Comment by njeudy** [comment]
@Yajo  I did this migration in https://github.com/OCA/partner-contact/pull/507

I should have create 2 merge requests ?

**Comment by yajo** [comment]
Usually it's the best approach: 1 PR per addon. 😉

**Comment by simoneversienti** [comment]
If squash all translation commits, it seems OK :+1:

**Review by OpenCode — APPROVED** [review]

**Comment by yajo** [comment]
#507 is merged, so I guess we don't need this anymore...

**Pull request closed without merging**
