### PR TITLE
[16.0][MIG] partner_contact_in_several_companies

### PR DESCRIPTION
**Pull request by stephansainleger**

### CODE REVIEW

**Comment by kwoychesko** [comment]
Hi @stephansainleger -- thank you very much for your work! 

@Highcooley @Rad0van I believe this needs your blessing to be merged? I would love to use it in a project I have on the go. Thank you! (Also, I hope I'm not being rude by asking. #noob)

**Review by Highcooley — APPROVED** [review]
LGTM Functionally, although the module could use some better readme on how to create other positions (had to analyse the code again to remember) :-)

**Comment by kwoychesko** [comment]
@Highcooley Thanks for taking a look! Did you need that readme fixed before the merge can occur?

**Comment by Highcooley** [comment]
@kwoychesko If possible, it would be great to have it before the merge.

**Comment by kwoychesko** [comment]
@Highcooley No problem, I'm happy to help with this!
@stephansainleger Below is an updated readme that helps to better explain the module. Could you either amend your code to include it (if you're satisfied with it) or tell me how I can proceed to have this included? (i.e. do I make a fork of your fork? sorry I'm not very Git-savvy but willing to learn)

====================================
Partner Contact in Several Companies
====================================

This module extends Odoo's Contacts app to allow one contact to have several job positions in different companies. It is an essential add-on for handling the 'gig economy' where people often work for several companies at a time (e.g., film and television industry, contract developers, construction, etc.)

Contacts are categorized as either:

* Standalone Contact (default): A normal contact (either an Individual or a Company), though only Individual Standalone contacts can be linked to.
* Attached to existing Contact: Usually used when adding a contact under a Company, this contact is linked to a source Standalone Contact. Source contacts can only be Individuals, not Companies, nor can an Attached contact serve as the source of another Attached contact.

Installation
============

1. Download the module from the OCA repository (ensure any dependencies are satisfied).
2. Place the module in your Odoo addons directory.
3. Restart the Odoo service.
4. In Odoo, go to Apps > Update Apps List.
5. Find and install the Partner Contact in Several Companies module.

After installation, all existing contacts will be of type Standalone (the default for the field contact_type).

Configuration
=============

No configuration is needed: new contacts will automatically be of type Standalone.

Usage
=====

To add a new Standalone contact, add a contact as usual, either by itself or under an existing contact's Contacts & Addresses tab (the Contact Type will be 'Standalone' by default). Any Standalone Individual contact can serve as the source for Attached contacts, whether that Standalone contact was added by itself or under an existing Company's or Individual's Contacts & Addresses tab.


To add a new Attached contact:

1. Ensure that the source Standalone contact is already created, though you can create the Standalone contact on-the-fly if needed.
2. Open the contact under which you would like to add the Attached contact (usually a Company, but it could be an Individual).
3. On the Contacts & Addresses tab, click the Add button.
4. Choose the type of contact you are adding (e.g. Contact, Delivery Address, Other Address, etc., though usually you will select Contact).
5. Select 'Attached to existing Contact' for the Contact Type.
6. Select the source Standalone contact in the Contact drop-down list (or create a new one on-the-fly). Only contacts that are Standalone and are Individuals will appear in the list.
7. Fill in the other informational fields (e.g. Address, Email, Phone, etc.) This data will not be copied or synchronized from the source Standalone contact.
8. Click the Save & Close button (or Save & New). The Attached contact will appear in the Contacts & Addresses tab of the parent Company, and in the Other Positions tab of the source Standalone contact.
9. If you later change the Name of either a Standalone or Attached contact, the Name will be synchronized between all related contacts. However, other information (e.g., Address, Email, Phone, etc.) will not be synchronized.

Searching for Contacts: 

When searching for Contacts, only the matching Standalone contacts are displayed, with the number of Attached contacts shown as '+ # other position(s)'. Open the Standalone contact and select the Other Positions tab to see the contacts that are 'Attached' to this Standalone contact.

NOTES:

1. This module merely sets up a relationship between the Standalone and Attached contacts — other than 'Name', there is no address, phone, email, etc. information synchronized or carried-over from one to the other. For example, an email address in the Standalone contact is not carried over to the Attached contact when created (and indeed they can both have different email addresses). The contact Name is however synchronized between Standalone and associated Attached contacts.
2. Attached contacts are not treated as duplicates when performing the Contact Merge action due to Attached contacts being specifically removed from the results of the res_partner.search() method (i.e. only Standalone contacts are returned during a res_partner.search()).
3. This module is compatible with the OCA's Partner Contact Access Link (partner_contact_access_link) module.
4. When you install this module, existing contacts will all become Standalone contacts. If there are any child contacts of Companies that you would like to convert to Attached to an existing contact, it is a manual process: create the new Standalone contact without any parent, and then change the child contact's Contact Type from 'Standalone' to 'Attached to existing Contact' and choose the new Standalone contact that you created without any parent.

**Comment by stephansainleger** [comment]
@kwoychesko Thanks a lot for you help, I have integrated your README.
I've kept this new file in a dedicated commit as it is not really a migration but an improvement of the add-on content. If you prefer me to merge it in the migration commit, just tell me :-)

**Comment by kwoychesko** [comment]
> @kwoychesko Thanks a lot for you help, I have integrated your README. I've kept this new file in a dedicated commit as it is not really a migration but an improvement of the add-on content. If you prefer me to merge it in the migration commit, just tell me :-)

@stephansainleger Happy to help! No worries -- separate commit is just fine with me. Thank you again for all your work!

**Comment by Highcooley** [comment]
Fantastic, thanks a lot for your work!

**Comment by stephansainleger** [comment]
@kwoychesko @Highcooley I'm not familiar with OCA processes yet. What are the next steps to get this PR merged in branch 16.0?

**Comment by Highcooley** [comment]
@stephansainleger Since all relevant checks are green, all you need is a second review for the PR to become ready to merge. They are sometimes hard to get, but basically every contributor can do them. After that, a PSC needs to merge it.

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. AFAIU, you migrated module from 14.0 to 16.0. right ? 
you have to respect git history. For that purpose, please follow the OCA convention here : 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

(replace 15.0 by 14.0 if the code comes from 14.0)
This way, it is easier for reviewer to review your diff, corresponding to your work during the migration.

Regards.

**Review by njeudy — APPROVED** [review]
Ok for me

**Comment by njeudy** [comment]
@pedrobaeza do you know how to force checks and actions ?

**Comment by pedrobaeza** [comment]
The original contributor should forced push the branch, rebasing.

**Pull request closed without merging**
