### PR TITLE
[8.0][BCK] Backport of partner_default_sale_discount from 9.0, adding a button t…

### PR DESCRIPTION
**Pull request by sergiocorato**
…o optionally update discount for all lines of quotation.

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Unfortunately how to debug ocabot failures is still a complete mistery to me.

**Comment by sergiocorato** [comment]
@NL66278 ~it was a generic failure of the process (database unavailable at port 5432), in this case you can retry the merge~ travis.yml is not in the last format, I update it asap

**Comment by NL66278** [comment]
I am going to force merge this.

**Pull request merged**
