### PR TITLE
[13.0][MIG] partner address street3

### PR DESCRIPTION
**Pull request by StephanRozendaal**

### CODE REVIEW

**Comment by remihb** [comment]
LGTM when using.
Travis build error doesn't seem to be related to module : 
```
odoo.addons.base_location_geonames_import.tests.test_base_location_geonames_import: ======================================================================
2019-12-11 11:13:19,629 5647 ERROR openerp_test odoo.addons.base_location_geonames_import.tests.test_base_location_geonames_import: ERROR: TestBaseLocationGeonamesImport.test_delete_old_entries
Traceback (most recent call last):
File "/home/travis/build/OCA/partner-contact/base_location_geonames_import/tests/test_base_location_geonames_import.py", line 67, in test_delete_old_entries
self.wizard.run_import()
File "/home/travis/build/OCA/partner-contact/base_location_geonames_import/wizard/geonames_import.py", line 185, in run_import
parsed_csv = self.get_and_parse_csv()
File "/home/travis/build/OCA/partner-contact/base_location_geonames_import/wizard/geonames_import.py", line 126, in get_and_parse_csv
% (res_request.status_code, url)
odoo.exceptions.UserError: ('Got an error 404 when trying to download the file http://download.geonames.org/export/zip/MC.zip.', '')
```

**Comment by NL66278** [comment]
Will close and open to rerun travis.

**Comment by rousseldenis** [comment]
@StephanRozendaal Could you check pre-commit ?

**Comment by ivantodorovich** [comment]
@StephanRozendaal lgtm, but pre-commit is failing.

**Comment by remihb** [comment]
It's about wrong tab indentation in [partner_address_street3/view/partner_view.xml](https://github.com/StephanRozendaal/partner-contact/blob/fcf78a370ddbf3066d505c4595b63e5b87d2fbd4/partner_address_street3/view/partner_view.xml#L4) (2 spaces instead of 4)

**Comment by NL66278** [comment]
@StephanRozendaal Will you run precommit to solve the travis errors?

**Comment by NL66278** [comment]
No action. so closing

**Pull request closed without merging**
