### PR TITLE
7.0 meta

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by bwrsandman** [comment]
```
TypeError: The model "res.partner.address" specifies an unexisting parent class "res.partner.address"

You may need to add a dependency on the parent class' module.
```

**Comment by pedrobaeza** [comment]
PEP8 correct. About the error, this must be an unported module with old res.partner.address.

:+1: (code review)

**Comment by bwrsandman** [comment]
Thanks @pedrobaeza, you were right.

**Comment by bwrsandman** [comment]
```
2014-07-19 15:16:16,308 19336 WARNING openerp_test openerp.modules.loading: The transient model base.partner.merge.line (base.partner.merge.line) should not have explicit access rules!

2014-07-19 15:16:16,308 19336 WARNING openerp_test openerp.modules.loading: The transient model base.partner.merge.automatic.wizard (base.partner.merge.automatic.wizard) should not have explicit access rules!
```

**Comment by eLBati** [comment]
:+1:

**Comment by eLBati** [comment]
As reference: https://github.com/OCA/partner-contact/issues/8

**Pull request merged**
