### PR TITLE
Get default value for firstname and lastname

### LINKED ISSUE #78: [8.0] partner_firstname and "create and edit" in M2O widget to res.partner
Here are the steps to reproduce the bug on odoo v8 with an up-to-date branch of OCA/partner-contact/8.0:

1) Create a new sale order
In the "Customer" field (M2O to res.partner), type "TOTOTEST1" (it should not be an existing partner) and then, in the down-drop list that appear, click on "Create and Edit..."
2) You get a pop-up that displays the form view of res.partner with:
Name = TOTOTEST1
Firstname = False
Lastname = False
3) in the partner pop-up, enter:
Lastname = de Lattre
Fistname =  Alexis
Street = 42 rue de la paix
and click on "Save" in the partner pop-up and save in the quotation form.
4) Go to the "Customers" menu. You will find a partner with:
Name = TOTOTEST1
Lastname = TOTOTEST1
Firstname = False
Street = 42 rue de la paix

Conclusion : when the module partner_firstname is installed, we have a bug with "Create and Edit..." in the M2O widget that point to res.partner.

### PR DESCRIPTION
**Pull request by yajo**
Fix #78.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@alexis-via, you can check this.

Thanks, @Yajo

**Comment by yajo** [comment]
Hmm seems tests for partner_second_lastname fail, let me see. And of course #154. :sleepy:

**Comment by yajo** [comment]
Nice! Got another bug fixed BTW.

**Comment by alexis-via** [comment]
You PR doesn't fix bug #78 : just execute exactly the scenario of my bug report and you will see that it's not fixed by your PR (in my PR, I change the name between what I write in the "Customer" field of the sale.order and the lastname/firstname of the form view of the partner)

But your PR is a very nice improvement and users will like it a lot, so I approve it :+1:  and I'll deploy it now ! Thanks very much for your contribution !

**Comment by rafaelbn** [comment]
:+1: , please @antespi review this

**Comment by pedrobaeza** [comment]
:+1: Merging this one and waiting for the final solution of the other issue

**Pull request merged**
