### PR TITLE
[16.0] [MIG] partner_contact_personal_information_page

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by marielejeune** [comment]
https://github.com/OCA/partner-contact/issues/1353

**Review by PierrickBrun — APPROVED** [review]
code review + test

**Review by AnizR — APPROVED** [review]
code review

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by carmenbianca — APPROVED** [review]
LGTM

**Comment by NL66278** [comment]
Fasttracking this, as it is a base for other modules and a straight migration.

/ocabot merge patch
/ocabot migration partner_contact_personal_information_page

**Comment by carmenbianca** [comment]
@NL66278 Do we rebase all the other open PRs on top of the new 16.0 when this is merged?

**Comment by NL66278** [comment]
@carmenbianca I think the modules that depend on partner_contact_personal_information_page should be rebased.

**Pull request merged**
