### PR TITLE
[FIX] base_location: Waadt state already exists in Odoo

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't get the motivation for this change. This is only a test. Is there any constraint to use such test data?

**Comment by yankinmax** [comment]
hello @pedrobaeza, you're too fast :smile:
This PR is needed to fix an error happening while migrating https://github.com/OCA/partner-contact/pull/1470
**UPDATE**
Failing test is gone after PR update
https://github.com/OCA/partner-contact/actions/runs/4201638823/jobs/7288843103#step:8:297

**Comment by yankinmax** [comment]
@pedrobaeza I hope I'm clear enough now, thanks

**Comment by yankinmax** [comment]
@pedrobaeza ping

**Review by pedrobaeza — APPROVED** [review]
OK, not sure why it didn't fail before (maybe they added the states later from the 16.0 release?).

In any case, let's fix it and it's not important to keep the manual record for the tests.

Fast-tracking it for fixing the CI:

/ocabot merge patch

**Pull request merged**
