### PR TITLE
[12.0][RMV] - Remove partner_brand module

### PR DESCRIPTION
**Pull request by sbejaoui**
partner_brand module is moved the new OCA repository OCA/brand.
PR: [OCA/brand#1](https://github.com/OCA/brand/pull/1)

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @sbidoul

**Review by sbidoul — APPROVED** [review]

**Comment by sbidoul** [comment]
As proposed on the Contributors mailing list.

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
ocabot /merge

**Pull request merged**
