### PR TITLE
[13] FIX - partner_external_map  fix view to better look Update res_partner_view.xml

### PR DESCRIPTION
**Pull request by sergioeix**
this way smart buttons looks better on partner form

### CODE REVIEW

**Comment by sergioeix** [comment]
@alexis-via @pedrobaeza @ernestotejeda are you agree with this small change to merge?

**Review by pedrobaeza — APPROVED** [review]

**Review by ernestotejeda — APPROVED** [review]

**Comment by alexis-via** [comment]
According to the logs, the pb was on VIES. Maybe we can try again later and it will become green.

**Comment by alexis-via** [comment]
OK, it seems we have to rely on "the real mans" for this merge.

**Pull request merged**
