### PR TITLE
[18.0][MIG] partner_ref_unique

### PR DESCRIPTION
**Pull request by samirGuesmi**

### CODE REVIEW

**Review by marielejeune — APPROVED** [review]
LGTM

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@pedrobaeza this PR is ready :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration partner_ref_unique

@samirGuesmi please next time put the proper title like the one I have put.

/ocabot merge nobump

**Pull request merged**
