### PR TITLE
[FIX] partner_contact: Fix Travis

### PR DESCRIPTION
**Pull request by pedrobaeza**
A try to fix Travis

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code OK, waiting for bots.

**Comment by Yajo** [comment]
Don't worry, I will squash at merge

**Comment by yajo** [comment]
Travis went ❌ again, although I still like the patch.

Is it possible that [the failure is just a timeout](https://travis-ci.org/OCA/partner-contact/jobs/237844771#L1081) due to #ocacodesprint overload?

**Comment by pedrobaeza** [comment]
No, the problem is with Travis test script. I try to fix it directly with this commit for not waiting the Travis queue: https://github.com/OCA/maintainer-quality-tools/commit/be28ef3ec0cb13c96b50b0a639f1bc316c64120c

**Comment by pedrobaeza** [comment]
This is not the real fix, but still approved by the original author as an improvement, so I merge.

**Pull request merged**
