### PR TITLE
[16.0][MIG] partner-label: Migration to 16.0

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Migration to 16.0

[ForgeFlow](https://github.com/ForgeFlow)

### CODE REVIEW

**Comment by tafaRU** [comment]
@AlexPForgeFlow thanks for your PR! Could you please https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate ?

**Review by tafaRU — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
