### PR TITLE
[ADD][14.0] partner_create_format_phone: initial commit

### PR DESCRIPTION
**Pull request by AshishHirapara**
The mobile number will be formatted with country code and spaces

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
I dont think it's the good place to add this lines.  This feature you add can be usefull without this module. Dont' you think ?

**Comment by francesco-ooops** [comment]
hi @legalsylvain , this need arises from automated creation of a partner record (eg: an automated action or a website form) which is not triggering correct phone number formatting:

image

Would you have any suggestions to overcome this behavior and/or somewhere else where this code could be useful?

Thanks!

**Comment by legalsylvain** [comment]
Create a dedicated module for that purpose ? Something like partner_create_format_phone. Dont you think ?

**Comment by francesco-ooops** [comment]
> Create a dedicated module for that purpose ? Something like partner_create_format_phone. Dont you think ?

Great!
@AshishHirapara can you do this?

**Comment by AshishHirapara** [comment]
> partner_create_format_phone

@francesco-ooops @legalsylvain sure, I will give it a try!

**Pull request closed without merging**
