### PR TITLE
[FIX] partner_contact_nutrition: correct lint error

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't there 2 errors?

**Comment by cubells** [comment]
There is one error in two different modules.

**Comment by pedrobaeza** [comment]
Yes, but you can include both in this PR. No need of 2 separate PRs. We won't see a green status in neither of both.

**Comment by cubells** [comment]
done!

**Comment by pedrobaeza** [comment]
You can now rebase the other

**Pull request merged**
