### PR TITLE
[16.0][MIG] partner_affiliate: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you spamming all your PRs threads if you don't have the permission to mark an addon to be migrated in any of them?

**Comment by FernandoRomera** [comment]
I thought that an action of simply notifying the rest of the community could be done by any contributor. I will not do it again.

**Comment by pedrobaeza** [comment]
No, it's not, as you may overwrite another legitimate pull request with the same migration. That has to be decided by a PSC or the module maintainer. Become maintainer of some modules.

**Comment by FernandoRomera** [comment]
But that is impossible to happen the first time you try to migrate the module. Therefore it would be legitimate, to inform the community of your action, to avoid duplication of work.

**Comment by pedrobaeza** [comment]
Not if you are maintainer on the previous version, but the way to inform that the community is not here, but on the migration issue as centralized place to do that, as for example: https://github.com/OCA/partner-contact/issues/1353#issuecomment-1293876384

**Comment by FernandoRomera** [comment]
#1353

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]
ok

**Pull request merged**
