### PR TITLE
[9.0][MIG] migrate module portal_partner_select_all

### PR DESCRIPTION
**Pull request by robinkeunen**
I'm reopening the PR #715  here because I cleaned up my repositories. I took @NL66278 and @chienandalu 's comments into account and removed commit [6af4c8b](https://github.com/OCA/partner-contact/pull/715/commits/6af4c8bb4a44606b950045f92ffd94f60c22ae32#diff-289746b6ae23cade5389d444b0dcac46L27) which seems useless to me.

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Review Travis

**Comment by NL66278** [comment]
Close and reopen to force travisi to run again.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by rousseldenis** [comment]
@chienandalu Could you udpate your review ? Travis is green (the red one is the former version)

**Review by HaraldPanten — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
What's with the red travis? A general error in this branch?

**Comment by rousseldenis** [comment]
> What's with the red travis? A general error in this branch?

@chienandalu As I said before, Travis is green. As we changed travis trigger recently, the old build is present.

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
