### PR TITLE
Fix pylint

### PR DESCRIPTION
**Pull request by gurneyalex**
rebased https://github.com/OCA/partner-contact/pull/51  on top of 7.0 branch, fixed the 2 remaining pylint warnings.

### CODE REVIEW

**Comment by lepistone** [comment]
maybe we want to revert the `fields` -> `field_names` renames?

**Comment by gurneyalex** [comment]
@lepistone these rename don't do any harm, do they?

**Comment by pedrobaeza** [comment]
I confirm that doesn't harm.

:+1:

**Comment by lepistone** [comment]
no problem then! I read a bit quickly your issue about renames forced by pylint.

:+1: then, thanks

**Comment by tafaRU** [comment]
:+1:

**Pull request merged**
