### PR TITLE
[16.0][FIX] partner_company_default: multi company creation

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Foward port of https://github.com/OCA/partner-contact/pull/1544

@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Code review.

**Review by wouitmil — APPROVED** [review]

**Comment by AungKoKoLin1997** [comment]
@partner-contact-maintainers
Can we get this PR merged?

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
