### PR TITLE
[ADD][14.0] partner_create_format_phone: initial commit

### PR DESCRIPTION
**Pull request by AshishHirapara**
Partner Phone number auto-format with country code and spaces

In response to PR https://github.com/OCA/partner-contact/pull/1406

### CODE REVIEW

**Comment by AshishHirapara** [comment]
cc @legalsylvain

**Review by legalsylvain — APPROVED** [review]
thanks !

**Review by francesco-ooops — APPROVED** [review]
functional ok!

@OCA/crm-sales-marketing-maintainers what do you say?

**Review by SicurSam — APPROVED** [review]
functional ok!

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers good for merge?

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers when you can :)

**Review by rafaelbn — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
