### PR TITLE
[ADD] migration of base_vat_sanitized

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's no commit history nor changes in version.

**Comment by hbrunn** [comment]
fixed

**Comment by rafaelbn** [comment]
Hi @hbrunn is the field hidden? I cannot found it in runbot

**Review by alexis-via — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexis-via** [comment]
Thanks for the merge @pedrobaeza , it will help for the work on the edi projct. Could you also merge my equivalent PR for v10 please ? https://github.com/OCA/partner-contact/pull/343

**Pull request merged**
