### PR TITLE
[FIX] partner_firstname: Change _id by id in the method copy_data

### PR DESCRIPTION
**Pull request by ghost**
When the method copy_data is call with the new API, the wrapper try to call the method with the argument cr, uid, id. In this case, the param _id are ignored the system raise a error:
TypeError: copy_data() takes at least 4 arguments (4 given)

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis fail has any relation with this change?

**Comment by ghost** [comment]
Hello, 

Can you tell me what I have to do ?
Do I have to fix test and create a new pull request ?

Thank for all,
Sylvain

**Comment by yvaucher** [comment]
@pedrobaeza The error was already there and seems unrelated with this PR

:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
