### PR TITLE
[MIG] partner_bank_code: Migration to 15.0

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Migrate to 15.0

cc: @Saran440 @newtratip

### CODE REVIEW

**Comment by Saran440** [comment]
@TheerayutEncoder 
This pr is not change pre-commit,
Should you rename commit from `[IMP] partner_bank_code: black, isort, prettier` to `[15.0][MIG] partner_bank_code` ?

**Review by newtratip — APPROVED** [review]
No major change :+1:

**Review by Saran440 — APPROVED** [review]

**Comment by ps-tubtim** [comment]
@TheerayutEncoder Please add your name to `CONTRIBUTORS.rst` :')

**Pull request merged**
