### PR TITLE
16.0 [MIG] base_country_state_translatable: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]
LGTM, squashing the bot commit would be a plus :)

**Review by rousseldenis — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This may be affected by https://twitter.com/stefan_opener/status/1603017051416707073?s=20&t=5Tne-FXHRzW5V7vv_tZ1sQ

**Pull request merged**
