### PR TITLE
16.0 mig partner contact department

### PR DESCRIPTION
**Pull request by aiendry-aktivsoftware**
[Migration to version 16.0](https://github.com/OCA/partner-contact/issues/1353)

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, Thank you @aiendry-aktivsoftware 

image

image

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
