### PR TITLE
[14.0] [MIG] partner_unique_email

### PR DESCRIPTION
**Pull request by AshishHirapara**
Migration of partner_unique_email to 14.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@AshishHirapara This is a duplicate functionality of https://github.com/OCA/partner-contact/tree/14.0/partner_email_check

@carmenbianca

**Comment by francesco-ooops** [comment]
> @AshishHirapara This is a duplicate functionality of https://github.com/OCA/partner-contact/tree/14.0/partner_email_check
> 
> @carmenbianca

@rousseldenis thanks for the heads up, we will propose a PR to change name to "Email Format and Duplicate Checker" to make it more immediate

btw, are you aware of a similar module for telephone or mobile fields? just the duplicate part

**Comment by AshishHirapara** [comment]
Will open a new PR to change the name of (https://github.com/OCA/partner-contact/tree/14.0/partner_email_check)

**Comment by AshishHirapara** [comment]
the PR link https://github.com/OCA/partner-contact/pull/1352

**Pull request closed without merging**
