### PR TITLE
[12.0][MIG] partner_email_unique

### PR DESCRIPTION
**Pull request by carmenbianca**
Migrated from 9.0.

Internal task: https://gestion.coopiteasy.be/web#view_type=form&model=project.task&id=7139&active_id=7139

### CODE REVIEW

**Comment by carmenbianca** [comment]
Tests conflict with [partner_deduplicate_filter](https://github.com/OCA/partner-contact/tree/12.0/partner_deduplicate_filter).

**Comment by carmenbianca** [comment]
[e9c2bf5](https://github.com/OCA/partner-contact/pull/1303/commits/e9c2bf5cb91afb979f3c492cb7a9d355160b63dd) should fix that, hopefully.

**Comment by carmenbianca** [comment]
I guess it didn't. Not sure how to debug this.

**Comment by rousseldenis** [comment]
@carmenbianca This duplicates functionality with https://github.com/OCA/partner-contact/tree/12.0/partner_email_check

**Comment by carmenbianca** [comment]
Bump. I'll look at this later.

**Comment by NL66278** [comment]
As this duplicates existing functionality I will close this.

**Pull request closed without merging**
