### PR TITLE
[15.0][MIG] partner_contact_department

### PR DESCRIPTION
**Pull request by Galoperd**

### CODE REVIEW

**Comment by Galoperd** [comment]
Hi ! anybody to review ? thanks !

**Comment by dhx** [comment]
@Galoperd thanks for your effort, please follow the migration guide to preserve the original commits of this module:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by Galoperd** [comment]
> @Galoperd thanks for your effort, please follow the migration guide to preserve the original commits of this module: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

So sorry, I am not sure to have understood well the migration guideline to preserve the original commits, but would be very happy to learn. It looks to me I have to re-start from zero a new Pull Request so the original commits are kept. Or, do you refer to any specific part of the migration guide so I can add them to this current PR 1308 ?

**Comment by dhx** [comment]
@Galoperd no need to create a new PR, just redo the migration and do a force push into the feature branch

**Comment by Galoperd** [comment]
> @Galoperd no need to create a new PR, just redo the migration and do a force push into the feature branch
Thanks! so when doing a local "git log" I confirm it shows all older commits. However, making a new commit and then "git push --force" seems not to work. If I am not wrong, history at my [REPO](https://github.com/Galoperd/partner-contact/commits/15.0/partner_contact_department) still show my commits only and not older ones. P.S. I am quite newbie, an step by step (=command by command) guideline for migration might be better for me and other newbies ?

**Comment by dhx** [comment]
@Galoperd when in your feature branch you'll have to do a "git reset --hard 15.0" before following the migration steps - otherwise you are just adding on top of your existing commits which does not preserve the original history of the module. (See also for more info on [git-reset](https://git-scm.com/docs/git-reset))

**Comment by Galoperd** [comment]
@dhx many thanks for your guidance, I think the git history is now ok.

**Comment by dhx** [comment]
> @dhx many thanks for your guidance, I think the git history is now ok.

glad to help, you might have to do another "git push --force" to see it here though.

**Comment by Galoperd** [comment]
it does not work

**Comment by dhx** [comment]
@Galoperd guess it might make sense to create a new PR then. Notice that when you set the variables in your shell before following the full process like that:
```
REPO=partner-contact
MODULE=partner_contact_department
USER_ORG=Galoperd
```
you can basically do a copy and paste ( https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch ). That should also give you a proper feature branch name (currently it seems you are doing the migration directly in the 15.0 branch).

**Pull request closed without merging**
