### PR TITLE
[10.0][MIG] Partner Contact Weight

### PR DESCRIPTION
**Pull request by woodbrettm**
Hi there,

This migrates partner_contact_weight to 10.0.

Thanks,
Brett

### CODE REVIEW

**Review by lasley — APPROVED** [review]
LGTM thanks @bmw95. Please squash the consecutive Transifexes into each other though please.

**Review by tarteo — APPROVED** [review]
LGTM. Thanks!

**Comment by woodbrettm** [comment]
@lasley squashed

**Review by rafaelbn — APPROVED** [review]
Tested in runbot

**Comment by dreispt** [comment]
I feel that this should also have added the height.
In fact, for health purposes, you height is important factor to consider when evaluating weight.

**Comment by woodbrettm** [comment]
@dreispt what about something like a partner_contact_size module for that? You could have height, foot size, leg length, waist size, etc.

**Comment by dreispt** [comment]
For some applications height weight and maybe IMC computation are enough.
Personally I' have use them as basic screening factors for applicants for security guard jobs.

**Comment by lasley** [comment]
@dreispt - While I do agree that height is necessity, there is already [`partner_contact_height`](https://github.com/OCA/partner-contact/tree/9.0/partner_contact_height) for this. Seems better to leave as two independent modules IMO, even though I can't really think of an instance where one would be relevant without the other.

**Comment by dreispt** [comment]
> even though I can't really think of an instance where one would be relevant without the other.

exactly my opinion 😉

**Comment by lasley** [comment]
@max3903 - Any thoughts on merging these two modules (weight & height) in v11?

**Comment by max3903** [comment]
@lasley Sure, why not.

**Pull request merged**
