### PR TITLE
Remove images from readme, update icon.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why removing images? Maybe better to put images zooming in the button part?

**Comment by feketemihai** [comment]
@pedrobaeza It seems that when you set images in manifest, apps.odoo.com is replacing the icon with the image...that's why...

**Comment by pedrobaeza** [comment]
Well, I'm seeing both:

seleccion_001

**Comment by feketemihai** [comment]
Yes...if you are on it, but in the search...
https://www.odoo.com/apps/modules/browse?search=create_by_vat

**Comment by pedrobaeza** [comment]
The trick then can be to put as first image the icon...

**Comment by feketemihai** [comment]
Ok...i will do it like this...Thanks. I will update the 10.0 the same.

**Comment by feketemihai** [comment]
Error is in partner_changeset:

2016-11-04 09:40:48,726 6506 ERROR openerp_test openerp.addons.partner_changeset.tests.test_changeset_field_type:

**Comment by yajo** [comment]
Travis' :x: is related?

**Comment by feketemihai** [comment]
@Yajo The error is in partner_changeset, just like my upper comment...

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
