### PR TITLE
[16.0][MIG] partner_fax: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-nfrancisco**

### CODE REVIEW

**Review by BT-anieto — APPROVED** [review]

**Review by flotho — APPROVED** [review]
code review
LGTM
thanks for the work

**Comment by rousseldenis** [comment]
@BT-nfrancisco Could you please fix your migration commit as version change should appear there and not in pre-commit one ? Thanks

**Review by BT-anieto — APPROVED** [review]

**Comment by BT-nfrancisco** [comment]
> @BT-nfrancisco Could you please fix your migration commit as version change should appear there and not in pre-commit one ? Thanks

Hello. I fixed the PR, thanks for your comment.

**Review by willer-mo — APPROVED** [review]

**Pull request merged**
