### PR TITLE
[12.0] [MIG] partner_employee_quantity

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
Employee quantity in partners
=============================
This module allows to set employee quantity for partners, and categorize them by ranges.

### CODE REVIEW

**Comment by Nikul-Chaudhary** [comment]
@pedrobaeza Can you please help here https://travis-ci.org/OCA/partner-contact/jobs/482533741#L414

**Comment by pedrobaeza** [comment]
Temporary Travis glitch. It happens sometimes. I have restarted the build.

**Comment by Nikul-Chaudhary** [comment]
@pedrobaeza Done

**Review by pedrobaeza — APPROVED** [review]
Please squash together your commits + 3 adjacent commits that are updating translations:

seleccion_019

**Comment by Nikul-Chaudhary** [comment]
@pedrobaeza squashed

**Comment by pedrobaeza** [comment]
Merging this easy one.

**Pull request merged**
