### PR TITLE
[FIX] Allow group_partner_manager to add relations in smartbutton partner relation tree

### PR DESCRIPTION
**Pull request by antespi**
Fix issue https://github.com/OCA/partner-contact/issues/122

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Includes the text "Fixes #122" on your commit message so that GitHub closes automatically the issue when PR is merged.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
