### PR TITLE
[17.0][MIG] partner_contact_birthdate: Migration to version 17.0

### PR DESCRIPTION
**Pull request by Daemo00**
Depends on:

- [x] https://github.com/OCA/partner-contact/pull/1608

### CODE REVIEW

**Comment by etobella** [comment]
/ocabot rebase

Can you remove the TESt-requirements commit now that we have it merged :smile:

**Review by etobella — APPROVED** [review]
Works as expected

You can put yourself as maintainer in the same commit as the migration.

**Comment by Daemo00** [comment]
> /ocabot rebase
> 
> Can you remove the TESt-requirements commit now that we have it merged 😄

Thanks for having a look!
Done

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
