### PR TITLE
[12.0][MIG] partner_identification_gln: Migration to 12.0

### PR DESCRIPTION
**Pull request by BT-aestebanez**

### CODE REVIEW

**Comment by BT-aestebanez** [comment]
Hello @nikul-serpentcs @rvalyi  @rousseldenis @NL66278 
I am writing you because you are reviewers of https://github.com/OCA/partner-contact/pull/666

I have migrated the module to 12.0 (including your comments).
Could you kindly review my code?

Thanks,
Alvaro

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by BT-aestebanez** [comment]
> Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Ok, I have not done it because my code is based on a WIP from 10.0 (the link of such PR is above).
But I will bring them from the already committed module in version 8.0

Thanks

**Comment by pedrobaeza** [comment]
Then you have to change to that origin and branch in the corresponding command.

**Comment by BT-aestebanez** [comment]
> Then you have to change to that origin and branch in the corresponding command.

done, thanks

**Comment by pedrobaeza** [comment]
Great, thanks. Now I let reviewers to do their job.

**Comment by BT-dchwalla** [comment]
@pedrobaeza 
@BT-aestebanez 

is there and update on that? 
who are the reviewers?

**Comment by pedrobaeza** [comment]
This needs reviewers:

https://odoo-community.org/page/review

**Review by StephanRozendaal — APPROVED** [review]
LGTM (code review)

**Review by BT-mgomez — APPROVED** [review]

**Comment by BT-aestebanez** [comment]
Any update?

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
