### PR TITLE
[15.0]  Migration of partner_vat_unique

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module partner_vat_unique.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by florenciafrigieri2** [comment]
Hi @alan196 ! Are you going to continue with this PR? Thanks!

**Comment by rousseldenis** [comment]
> Hi @alan196 ! Are you going to continue with this PR? Thanks!

I think it's ready

**Comment by alan196** [comment]
Hi @florenciafrigieri2 

This module is ready to review and get merged, I don't know how to proceed with this CLA issue, I don't know how this module was merged before with this CLA issue, maybe users remove their email address from their GitHub account.

**Comment by rousseldenis** [comment]
> Hi @florenciafrigieri2
> 
> This module is ready to review and get merged, I don't know how to proceed with this CLA issue, I don't know how this module was merged before with this CLA issue, maybe users remove their email address from their GitHub account.

No issue here as it should take into account active logins. I think an issue or PR exists about that.

**Comment by rousseldenis** [comment]
FYI https://github.com/OCA/oca-github-bot/issues/209

**Comment by rousseldenis** [comment]
@florenciafrigieri2 Could you review this ?

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review ok

**Review by pablontura — APPROVED** [review]
LGTM

**Comment by florenciafrigieri2** [comment]
Hi @rousseldenis ! Could you please merge this PR? Thanks!

**Comment by desdelinux** [comment]
Hi @alan196, you can regenerate runbot.

You can create a dummy commit for it

cc @rousseldenis

**Comment by alan196** [comment]
@desdelinux I rebased in order to regrenarte runboat. Could you help me to review 🙏

**Review by desdelinux — APPROVED** [review]
@alan196 LGTM, This Pr is ready for merged

cc @luisg123v @moylop260 @rousseldenis

**Pull request merged**
