### PR TITLE
[15.0][mig]partner_label

### PR DESCRIPTION
**Pull request by quannguyen1560**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@quannguyen1560 Could you squash your commits ?

**Review by bosd — APPROVED** [review]
Function Review.

Looks good,  :+1:

**Comment by NL66278** [comment]
@quannguyen1560 Could you take up the request to squash the migration commits? Then we can move forward with merging this.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM And standard migration.

**Pull request merged**
