### PR TITLE
Put contact type under name and add label in edit mode

### PR DESCRIPTION
**Pull request by bwrsandman**
Categories not having a label and being in a strange spot
## Current

capture d ecran de 2014-11-05 18 18 25
capture d ecran de 2014-11-05 18 18 16
## Fixed

capture d ecran de 2014-11-05 18 25 58
capture d ecran de 2014-11-05 18 25 48

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Seems OK, although I don't use this module. Too much complexity in the migration path from 6.1...

:+1:

**Comment by foutoucour** [comment]
The layout seems broken now. Maybe add the label to tag or take category down to next group to order a bit the layout

**Comment by bwrsandman** [comment]
> Maybe add the label to tag or take category down to next group to order a bit the layout

That would be hard to have it behave with other modules such as: #44 
I'm trying to be the most unobtrusive to the current code.

**Comment by foutoucour** [comment]
ok, sounds good then
:+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
