### PR TITLE
Fix admin merge contacts

### PR DESCRIPTION
**Pull request by cesarcruz**

### CODE REVIEW

**Comment by cesarcruz** [comment]
@mdietrichc2c I did split commits and left #128 with only Spanish related commits, but forgot to remove Spanish commit for this branch, so I'm fixing it

**Comment by cesarcruz** [comment]
@mdietrichc2c Fixed problem with commits, you can merge it, thanks for your tips

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Test for new condition would be welcome

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
