### PR TITLE
[16.0][MIG] partner_contact_in_several_companies

### PR DESCRIPTION
**Pull request by bfigueiredo-odoogap**
Migrating the Module partner_contact_in_several_companies from the v14.0 to the v16.0. 
Keeping all the logic and modifying just what was needed.

### CODE REVIEW

**Comment by Highcooley** [comment]
Did you see that this module was already migrated to 15.0 but never merged? https://github.com/OCA/partner-contact/pull/1425

**Comment by bfigueiredo-odoogap** [comment]
@Highcooley, actually i didn't see that migration for the v15. But helped me with the issues that i had on my side.

**Review by Highcooley — APPROVED** [review]
Functionally Approved

**Comment by Highcooley** [comment]
@bfigueiredo-odoogap Could you please rename the PR to `[16.0][MIG] partner_contact_in_several_companies` and also squash your fixes into the migration commit following https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests to make the migration a bit leaner.

**Comment by mmequignon** [comment]
you lost the history in the process.
Even if nothing was there in 15.0, this module was there in 14.0.
Please, follow this procedure: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to
And instead of using `origin/15.0`, you can use `origin/14.0` :blush:

**Comment by Highcooley** [comment]
@bfigueiredo-odoogap will you find the time soon to resolve the history issues and squash the commits? I am waiting for for this module to finish a migration project. Thanks a lot for your effort.

**Comment by bfigueiredo-odoogap** [comment]
@Highcooley, when i have some time i will do it, i was on holidays on the last week and that was the reason why i not answered to any message, sorry for that

**Comment by Highcooley** [comment]
@bfigueiredo-odoogap No worries and thanks a lot. Let me know if you need help.

**Comment by Rad0van** [comment]
Yeah, the history of commits has been lost. Please fix that and I'll review as I would be needing this.

**Comment by b0g** [comment]
Hello hello, newbie in OCA around, What’s the next step for this PR to be merge ? can I help ?

**Comment by stephansainleger** [comment]
@Highcooley @Rad0van I also need this addon to be migrated in 16.0. As this PR seems to be blocked, I have created a new one with commits squashed: https://github.com/OCA/partner-contact/pull/1703
If it is ok with OCA policy (I'm newby as contributor), could you please validate it? Thanks :-)

**Pull request closed without merging**
