### PR TITLE
[15.0][mig] partner_contact_age_range

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @BT-rfresco , thanks for this migration. Could you please review conflicts?

**Comment by ghost** [comment]
@rafaelbn I solved the conflicts. Can you please review? thank you

**Comment by rafaelbn** [comment]
I think this is wrong, could you fix it?

imagen

**Comment by ghost** [comment]
> I think this is wrong, could you fix it?
> 
> imagen

@rafaelbn can you please check again? Thank you

**Review by rafaelbn — APPROVED** [review]
Tested 👍

**Review by ghost — APPROVED** [review]
lgtm

**Review by BT-aestebanez — APPROVED** [review]

**Pull request merged**
