### PR TITLE
15.0 mig partner address street3

### PR DESCRIPTION
**Pull request by xhnilic3**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@xhnilic3 Please don't open a new migration PR before checking there is already one. #1273

**Comment by xhnilic3** [comment]
@rousseldenis I'm sorry, shall I close this one?

**Comment by rousseldenis** [comment]
> @rousseldenis I'm sorry, shall I close this one?

Yes, and please review the other one. thanks

**Comment by xhnilic3** [comment]
Closed - duplicate

**Pull request closed without merging**
