### PR TITLE
[17.0][MIG] partner_contact_nationality: Migration to 17.0

### PR DESCRIPTION
**Pull request by quoc-pn**

### CODE REVIEW

**Review by gurneyalex — DISMISSED** [review]

**Comment by gurneyalex** [comment]
can you check the CI @quoc-pn

**Comment by quoc-pn** [comment]
@gurneyalex the CI is green now

**Comment by tien-ld** [comment]
LGTM

**Review by Abranes — APPROVED** [review]
LGTM

**Review by cvinh — APPROVED** [review]
Works on our production

**Pull request merged**
