### PR TITLE
[ADD][10.0] add partner_address_two_lines module

### PR DESCRIPTION
**Pull request by Tonow-c2c**
Idem as https://github.com/OCA/partner-contact/pull/841

OCA/OCB :
* https://github.com/OCA/OCB/pull/903
* https://github.com/OCA/OCB/pull/904

### CODE REVIEW

**Comment by grindtildeath** [comment]
@Tonow-c2c Please state in the description that this module requires: 
 - [ ] https://github.com/OCA/OCB/pull/903
 - [ ] https://github.com/OCA/OCB/pull/904

**Comment by Tonow-c2c** [comment]
@grindtildeath @vrenaville it's ok for you ?

**Review by NL66278 — APPROVED** [review]
:+1:

**Review by dreispt — APPROVED** [review]

**Pull request merged**
