### PR TITLE
[FIX] partner_vat_unique: constrain on company change

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT24455

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by chienandalu** [comment]
ping @pedrobaeza

**Review by HaraldPanten — APPROVED** [review]
Small FIX, LGTM 👍

**Comment by pedrobaeza** [comment]
Let's fast-track it!

/ocabot merge patch

**Comment by chienandalu** [comment]
Do I fw port to 12 and 13 or will you just cherry-pick the change?

**Comment by pedrobaeza** [comment]
Cherry-picked for v12 in 8e7fe292737280c491bd0b515e62a775f042bafe.

Adjusted PR to Odoo for v13 as well: https://github.com/odoo/odoo/pull/53701

**Comment by AlejandroAladro** [comment]
Hello , with multicompany and option contact share , can create same contact with same VAT on both companys.
If you don't set the company field, the restriction works fine, but if you create or duplicate the contact with that mapped field, the same tub, and the shared contact, the restriction doesn't work.

**Pull request merged**
