### PR TITLE
[14.0][MIG] partner_industry_secondary: Migration to 14.0

### PR DESCRIPTION
**Pull request by skeller1**
Standard migration from V13 to V14

- [x] removed _check_parent_id constrains (but keep test to be sure that error is raised)
- [x] fixed docs

### CODE REVIEW

**Comment by skeller1** [comment]
AFAIU `@api.constrains("parent_id")` in `res.partner.industry.py` is not triggered in V13 and V14 (tested locally with latest dockerhub images), but Odoo is showing ORM specific "Recursion Detected" message (screenshot).
So maybe we could remove this code part in V14? Could somebody help/give some information to fix this?

recursionDetected

**Review by HaraldPanten — APPROVED** [review]

**Comment by kos94ok-3D** [comment]
https://github.com/OCA/partner-contact/pull/1079

**Comment by MiquelRForgeFlow** [comment]
@skeller1 Please, change Eficent to ForgeFlow like is done in https://github.com/OCA/partner-contact/pull/1082. You can cherry pick if you want.

**Comment by kos94ok-3D** [comment]
I think this PR can be closed as it was done already https://github.com/OCA/partner-contact/pull/1018

**Pull request closed without merging**
