### PR TITLE
[15.0] Migration partner_address_street3

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@OpenCode Same remarks as in https://github.com/OCA/partner-contact/pull/1174

**Comment by emagdalenaC2i** [comment]
@OpenCode Any plans to finish this PR?

**Comment by Sparad0x** [comment]
Hello, do you plan to release the street 3 for v15 in the near future?

**Comment by rousseldenis** [comment]
@OpenCode You did not answer. Can we close this in favor of #1273 ?

**Comment by OpenCode** [comment]
> @OpenCode You did not answer. Can we close this in favor of #1273 ?

Yep. Sure.

**Pull request closed without merging**
