### PR TITLE
7.0 - [IMP] Add unique constraint on res.better.zip

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds a uniq constraint on res.better.zip to prevent users from creating multiple times the same location.

The migration script is currently in a PR to OpenUpgrade. It has unittests to prove that it works.
https://github.com/OpenUpgrade/OpenUpgrade/pull/266

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the work on this. Only a minor issue at first sight: the migration script should be done before update (pre-migration), not after, because this way, constraint is not going to be applied.

**Comment by ghost** [comment]
@pedrobaeza I tested the migration and the constraint is applied even if the script is post-migration. A pre-migration script would be much more complex, because the orm could not be used to search an unlink res.better.zip records.

**Comment by pedrobaeza** [comment]
OK then

**Comment by bwrsandman** [comment]
:+1: used in prod

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
