### PR TITLE
[17.0] [IMP] partner_affiliate: add button in kanban to open form

### PR DESCRIPTION
**Pull request by Tisho99**
This PR adds the functionality of the partner_contact_access_link module of this repo to the kanban view added in the partner_affiliate module, without  altering the dependences

T-6101

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
