### PR TITLE
Bringing some module to odoo v. 13

### PR DESCRIPTION
**Pull request by ermannognan**
Hi, I've made some little change in order to make modules available for odoo v 13.
In the next few days I will carry on this work trying to update all the repository modules for version 13. I hope this is appreciated.

Best regards to all maintainers.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for contributing, but you need to follow certain guidelines when doing that:

- Only one module per pull request.
- Preserve commit history following technical steps on https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
- See what is already being migrated in pull requests.

**Comment by ermannognan** [comment]
Thanks Pedro,
I will check this guidelines!

**Comment by emagdalenaC2i** [comment]
> See what is already being migrated in pull requests.

See https://github.com/OCA/partner-contact/issues/783

**Comment by ermannognan** [comment]
Thanks Eduardo!

**Comment by NL66278** [comment]
@ermannognan Definitely valuing your contribution. But closing this in favour for one PR for each module. Please also follow guidelines on migration mentioned by @pedrobaeza .

**Pull request closed without merging**
