### PR TITLE
[17.0][MIG] partner_deduplicate_filter: Migration to 17.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Standard migration to v17.

Depends on:

- [partner_deduplicate_acl] https://github.com/OCA/partner-contact/pull/1805

@Tecnativa
TT49922
@pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Review by pilarvargas-tecnativa — APPROVED** [review]
Revised functionality, thanks

**Comment by carolinafernandez-tecnativa** [comment]
Rebase and remove test-requirements.txt commit as partner_deduplicate_acl is merged on branch 17.0

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
