### PR TITLE
partner_contact_address_default, error while updating module.

### PR DESCRIPTION
**Pull request by GSLabIt**
Fix https://github.com/OCA/partner-contact/issues/1237

### CODE REVIEW

**Comment by GSLabIt** [comment]
@pedrobaeza could u please review?

**Comment by pedrobaeza** [comment]
Which view on this module is depending on `base_setup`?

**Comment by GSLabIt** [comment]
> Which view on this module is depending on `base_setup`?

https://github.com/OCA/partner-contact/blob/901c267d8c786d3d894e4e8396b51a5f7c8bc792/partner_contact_address_default/views/res_config_settings_views.xml#L5-L28

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
