### PR TITLE
[15.0] Migration partner_ref_unique

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by hugho-ad** [comment]
its read because runbot right?

@pedrobaeza could you merge this?

**Comment by pedrobaeza** [comment]
Not really. The rebased branch gave some weird errors. Let's retry to see if it's something arbitrary:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
One more:

/ocabot merge nobump
/ocabot migration partner_ref_unique

**Pull request merged**
