### PR TITLE
[ADD] other gender as of 9.0

### PR DESCRIPTION
**Pull request by hbrunn**
cf https://github.com/OCA/partner-contact/blob/9.0/partner_contact_gender/models/res_partner.py#L11

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by elicoidal** [comment]
Not sure how to handle this: https://travis-ci.org/OCA/partner-contact/jobs/134321776

**Comment by hbrunn** [comment]
@elicoidal that looked a lot like a fluke on travis, so I restarted the build and now it's happy

**Comment by elicoidal** [comment]
Thanks!

**Pull request merged**
