### PR TITLE
[16.0][MIG] partner_deduplicate_filter: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
@Tecnativa TT45638

@pilarvargas-tecnativa @chienandalu please review!

### CODE REVIEW

**Review by pilarvargas-tecnativa — APPROVED** [review]
Tested locally, thanks :)

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pilarvargas-tecnativa** [comment]
@pedrobaeza  can this be merged?

**Pull request merged**
