### PR TITLE
[15.0][MIG] partner_pricelist_tracking: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc@Tecnativa TT41650

@chienandalu please review!

ping @pilarvargas-tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by pilarvargas-tecnativa — APPROVED** [review]
Tested locally

**Comment by pedrobaeza** [comment]
Please squash administrative commits with the generated one:

Selección_003

**Comment by chienandalu** [comment]
Ready to merge @pedrobaeza

**Pull request merged**
