### PR TITLE
Fixed mix content issue (http->https)

### PR DESCRIPTION
**Pull request by elicoidal**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Take the occasion to put the new README by fragments system.

**Comment by elicoidal** [comment]
@pedrobaeza OK!

**Comment by yajo** [comment]
I pushed https://github.com/OCA/partner-contact/commit/9c09dbc6c35b5b6a07abf722e804f482f46edd29 this morning, is it still needed? Why no conflict?

**Comment by pedrobaeza** [comment]
Closing then

**Pull request closed without merging**
