### PR TITLE
13.0 mig partner coc

### PR DESCRIPTION
**Pull request by ntsirintanis**
Migrating partner_coc from 12.0 to 13.0. This PR is based on [#815 ](https://github.com/OCA/partner-contact/pull/815)

### CODE REVIEW

**Comment by NL66278** [comment]
@ntsirintanis I you already use the OCA quality tools before submitting a MR, you can prevent these Travis errors.

**Comment by ntsirintanis** [comment]
@hbrunn @NL66278 @gfcapalbo

**Comment by NL66278** [comment]
@ntsirintanis I merged #815  SO you should rebase your branch. As the partner_firstname fixes have also been merged, it should be easy to merge this one as well.

**Comment by ntsirintanis** [comment]
@NL66278

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
