### PR TITLE
[MIG][13.0] partner_phonecall_schedule: Migration to v13.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
TT19785

### CODE REVIEW

**Comment by sergio-teruel** [comment]
partner_firstname tests are failing...

**Comment by rousseldenis** [comment]
@sergio-teruel I've created an issue here : https://github.com/OCA/partner-contact/issues/851

Due to an Odoo commit. @pedrobaeza Maybe can we attract people on this as you cannot use tests for form views anymore (at least on partner form)...

**Comment by pedrobaeza** [comment]
@rousseldenis thanks for the tracking

**Comment by sergio-teruel** [comment]
Thanks @rousseldenis

**Review by chienandalu — APPROVED** [review]
Code and functional review :+1:

**Review by HaraldPanten — APPROVED** [review]
Funtional review. 👍 

Just some minor changes: You should change `http` for `https` in License headers

**Comment by pedrobaeza** [comment]
As that's not mandatory and works the same, I'm merging:

/ocabot merge nobump

**Comment by HaraldPanten** [comment]
> As that's not mandatory and works the same, I'm merging:
> 
> /ocabot merge nobump

Hi @pedrobaeza I thought that this was not mandatory but "important", as some PSC's/reviewers told me to change this before approving some of my PR's.

By the way... I approved the module. Thanks for clarifying.

**Comment by pedrobaeza** [comment]
It depends on the picky things that each one consider. For sure this was something from Ronald Portier. Am I right?

**Comment by HaraldPanten** [comment]
> It depends on the picky things that each one consider. For sure this was something from Ronald Portier. Am I right?

Might be, or maybe not... 😁  You know that we have an expression like "_Name the sin and not the sinner"_ (literal translation)

**Pull request merged**
