### PR TITLE
[8.0][partner_contact_department] Add departments to contacts

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of the address book to support departments.

Department is a drop-down field in partner forms, and it refers to contact department in its own company.

@JavierIniesta @rafaelbn

### CODE REVIEW

**Comment by yajo** [comment]
@antespi

**Comment by pedrobaeza** [comment]
This should be hosted here: https://github.com/OCA/department

**Comment by yajo** [comment]
yikes.

**Comment by yajo** [comment]
Now here: https://github.com/OCA/department/pull/51

**Pull request closed without merging**
