### PR TITLE
[13.0][MIG] partner_industry_secondary: Migration to 13.0

### PR DESCRIPTION
**Pull request by skeller1**
**Standard Migration from partner_industry_secondary to 13.0**

Changes/Improvement:
- [x] add uniq name constraint per parent (removed it from roadmap in docs)
- [x] allow copying of industries
- [x] add tests for copy and uniq name constraint per parent

IndustrySecondarySettings

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The problem with storing `complete_name` is that the translations are not effective.

**Comment by skeller1** [comment]
> The problem with storing `complete_name` is that the translations are not effective.

Ok, understand this and changed back to the old implementation, thank you

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Comment by skeller1** [comment]
add tests for copy and uniq name constraint per parent (open roadmap entry in docs)

**Review by tonygalmiche — APPROVED** [review]
+1 LGTM

**Review by mamcode — APPROVED** [review]
LGTM. @skeller1  I think you should be added to the list of contributors.

**Comment by rousseldenis** [comment]
@NL66278 As I've already said, don't merge directly. Use ocabot. As you can see, module is not published on pypi : https://pypi.org/search/?q=odoo13-addon-partner-industry&o=

If you don't rely on it, maybe we could improve it or if you have questions about it, maybe I can answer. Thanks

**Pull request merged**
