### PR TITLE
[14.0][MIG] base_location_geonames_import

### PR DESCRIPTION
**Pull request by alexis-via**
Replaces PR #1016 

The Geonames service is currently down, cf https://download.geonames.org/export/zip/ that only has 1 zip file, so I could not test.

I removed the INSTALL part of README because requests is now required for the base module of odoo v14.

### CODE REVIEW

**Comment by alexis-via** [comment]
Geonames is back up and working. So I am now able to test the module... and it works well.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
As the migration is straight-forward, let's try directly to merge it:

/ocabot merge nobump

**Review by OsoTranquilo — APPROVED** [review]
It works properly.

**Review by OsoTranquilo — APPROVED** [review]
Works OK

**Review by HaraldPanten — APPROVED** [review]

**Comment by OsoTranquilo** [comment]
@pedrobaeza what's necessary for travis run again?

**Comment by pedrobaeza** [comment]
I'm afraid this is another problem: https://github.com/OCA/oca-addons-repo-template/issues/25

**Comment by OsoTranquilo** [comment]
> I'm afraid this is another problem: [OCA/oca-addons-repo-template#25](https://github.com/OCA/oca-addons-repo-template/issues/25)


Do I understand that this is already fixed?
Can you try passing Travis now?

**Comment by HaraldPanten** [comment]
What should be done here? Relaunch Travis?

**Comment by pedrobaeza** [comment]
Migration is not complete, so I have finished it in #1039.

**Pull request closed without merging**
