### PR TITLE
[9.0] [MIG] partner_contact_lang

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa

### CODE REVIEW

**Review by rousseldenis — COMMENTED** [review]
Can you change icon to OCA ?

**Comment by pedrobaeza** [comment]
@rousseldenis thanks for your reviews. The icon is a custom one I prepared for the module. I think it's more convenient than the generic one :wink:

**Comment by rousseldenis** [comment]
@pedrobaeza I thought it was the convention to use OCA icon in every module

**Review by rousseldenis — APPROVED** [review]
:+1: Code review + tested on runbot

**Comment by pedrobaeza** [comment]
No, the only convention is to not put any commercial trademark or logo, but you can:

* Not put any icon.
* Put generic OCA icon.
* Put custom icon.

I always try to put some icons when I have the inspiration for a clear concept, hehe. Also with the raise of the mobile interface (web_responsive OCA module or web_enterprise module), the icon for the main app is starting to be important. For example, I plan to create an icon for connector, queue and custom info apps.

**Comment by pedrobaeza** [comment]
@cubells, please review

**Review by cubells — APPROVED** [review]
:+1: 

Review code and test in runbot.

**Review by leemannd — APPROVED** [review]

**Pull request merged**
