### PR TITLE
[15.0][FIX] partner_firstname:  Bug in required conditions for contacts

### PR DESCRIPTION
**Pull request by BT-rmartin**

### CODE REVIEW

**Comment by BT-rmartin** [comment]
@gurneyalex @bjornbillen @houssine78 @ajaniszewska-dev I already reported this during the migration of the module, and today I realized it wasn't changed. Could you please double check if you see this also like a bug? Thanks

**Review by leemannd — APPROVED** [review]
Seems legit

**Review by NL66278 — APPROVED** [review]
:+1:  LGTM

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
thanks for the fix @BT-rmartin. @NL66278 could you merge the PR ?

**Pull request merged**
