### PR TITLE
[FIX] Remove pylint-odoo submodule (Fixes #448)

### LINKED ISSUE #448: fatal: No url found for submodule path 'pylint-odoo' in .gitmodules
```
~ » git clone --recursive https://github.com/OCA/partner-contact.git -b 10.0                                                              vladislavshepilov@Vladislavs-MacBook-Pro
Cloning into 'partner-contact'...
remote: Counting objects: 17718, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 17718 (delta 5), reused 5 (delta 3), pack-reused 17689
Receiving objects: 100% (17718/17718), 5.68 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (12862/12862), done.
fatal: No url found for submodule path 'pylint-odoo' in .gitmodules
```

### PR DESCRIPTION
**Pull request by WohthaN**

### CODE REVIEW

**Review by leemannd — COMMENTED** [review]
Hello, thanks for the PR, but according #448 isn't the goal to remove this submodule?

**Comment by WohthaN** [comment]
Oh, I didn't get that part, sorry. The last commit should do then!

**Review by leemannd — APPROVED** [review]
Thank you for the fix. LGTM!
In order to have a clean history it would be great if you have the time to squash the commits togheter.

**Comment by WohthaN** [comment]
There you have 👍

**Comment by pedrobaeza** [comment]
Is the CLA signed?

**Comment by WohthaN** [comment]
@pedrobaeza : just sent

**Pull request merged**
