### PR TITLE
13.0 mig base country state translatable

### PR DESCRIPTION
**Pull request by leemannd**
Replaces https://github.com/OCA/partner-contact/pull/824
Included the required fix about licenses

### CODE REVIEW

**Comment by leemannd** [comment]
@NL66278 This is a takeover of a PR that you have been already reviewing. Unfortunately, the PR has been closed without merging.
It would be great if you have some time to review this one.

**Review by yostashiro — APPROVED** [review]
LGTM 👍

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by leemannd** [comment]
Thanks for the reviews.
@HaraldPanten is it possible to have it merged?

**Comment by leemannd** [comment]
Hello @pedrobaeza do you have time to check an merge this PR ?

**Comment by pedrobaeza** [comment]
Well, not too much, but for you there's always a bit :wink: 

/ocabot merge nobump

**Comment by leemannd** [comment]
@pedrobaeza Thank you.

**Comment by HaraldPanten** [comment]
> Thanks for the reviews.
> @HaraldPanten is it possible to have it merged?

Sorry @leemannd , I didn't see your message! 🙏

**Pull request merged**
