### PR TITLE
[10.0][BUG] partner_create_by_vat - Update res_partner_view.xml

### PR DESCRIPTION
**Pull request by idealisconsultingbe**
The field vat is in base_vat.view_partner_form and not base.view_partner_form

### CODE REVIEW

**Review by feketemihai — APPROVED** [review]

**Comment by feketemihai** [comment]
@idealisconsultingbe can you please change the title to add BUG, it will be reviewed faster.

**Comment by feketemihai** [comment]
@pedrobaeza Can i have your review here, it's a bug, and should be merged..

**Review by pedrobaeza — APPROVED** [review]

**Comment by feketemihai** [comment]
@pedrobaeza Thanks.

**Comment by idealisconsultingbe** [comment]
@pedrobaeza Thanks for the merge and approval. KR

**Pull request merged**
