### PR TITLE
Slovene translations added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically :+1:

**Comment by yvaucher** [comment]
Technically :+1:

**Comment by tafaRU** [comment]
Technically LGTM too, so :+1:

**Comment by tafaRU** [comment]
Just noticed po headers still refer to OpenERP instead Odoo, but it's quite irrilevant as error.
@yvaucher @pedrobaeza what's your opinion?

**Comment by pedrobaeza** [comment]
That comments are ignored, so it's only for reference. We know all what OpenERP is :wink:

**Comment by tafaRU** [comment]
@pedrobaeza thanks for your clarification. I proceed with the merge then.

**Pull request merged**
